package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class a66 {
    public final ks2 A;
    public final wr2 A0;
    public final ks2 B;
    public final wr2 B0;
    public final wr2 C;
    public final ks2 C0;
    public final wr2 D;
    public final ls2 D0;
    public final wr2 E;
    public final ks2 E0;
    public final wr2 F;
    public final ks2 F0;
    public final ur2 G;
    public final ls2 G0;
    public final wr2 H;
    public final wr2 H0;
    public final ur2 I;
    public final wr2 I0;
    public final wr2 J;
    public final wr2 J0;
    public final ur2 K;
    public final wr2 K0;
    public final wr2 L;
    public final ks2 L0;
    public final ur2 M;
    public final ks2 M0;
    public final wr2 N;
    public final ks2 N0;
    public final ks2 O;
    public final wr2 O0;
    public final ks2 P;
    public final wr2 P0;
    public final ks2 Q;
    public final wr2 Q0;
    public final ks2 R;
    public final ms2 R0;
    public final ks2 S;
    public final os2 S0;
    public final wr2 T;
    public final ls2 T0;
    public final ks2 U;
    public final ls2 U0;
    public final ks2 V;
    public final ms2 V0;
    public final ks2 W;
    public final ns2 W0;
    public final ks2 X;
    public final ps2 X0;
    public final ks2 Y;
    public final ks2 Y0;
    public final ks2 Z;
    public final ls2 Z0;
    public final ur2 a;
    public final ks2 a0;
    public final ls2 a1;
    public final wr2 b;
    public final ks2 b0;
    public final ns2 b1;
    public final ks2 c;
    public final ks2 c0;
    public final wr2 c1;
    public final wr2 d;
    public final wr2 d0;
    public final wr2 d1;
    public final ks2 e;
    public final wr2 e0;
    public final ks2 e1;
    public final ur2 f;
    public final ks2 f0;
    public final wr2 f1;
    public final ur2 g;
    public final ks2 g0;
    public final wr2 g1;
    public final ur2 h;
    public final ks2 h0;
    public final long h1;
    public final wr2 i;
    public final ls2 i0;
    public final ks2 i1;
    public final ur2 j;
    public final ms2 j0;
    public final wr2 j1;
    public final ur2 k;
    public final ls2 k0;
    public final wr2 k1;
    public final ks2 l;
    public final ls2 l0;
    public final wr2 l1;
    public final wr2 m;
    public final ks2 m0;
    public final wr2 m1;
    public final ur2 n;
    public final ks2 n0;
    public final ur2 n1;
    public final ur2 o;
    public final ur2 o0;
    public final wr2 o1;
    public final ur2 p;
    public final wr2 p0;
    public final ur2 p1;
    public final wr2 q;
    public final wr2 q0;
    public final wr2 r;
    public final wr2 r0;
    public final wr2 s;
    public final ks2 s0;
    public final wr2 t;
    public final wr2 t0;
    public final ks2 u;
    public final ks2 u0;
    public final wr2 v;
    public final wr2 v0;
    public final ks2 w;
    public final ks2 w0;
    public final wr2 x;
    public final ks2 x0;
    public final wr2 y;
    public final ks2 y0;
    public final wr2 z;
    public final ks2 z0;

    public a66(ur2 ur2Var, wr2 wr2Var, ks2 ks2Var, wr2 wr2Var2, ks2 ks2Var2, ur2 ur2Var2, ur2 ur2Var3, ur2 ur2Var4, wr2 wr2Var3, ur2 ur2Var5, ur2 ur2Var6, ks2 ks2Var3, wr2 wr2Var4, ur2 ur2Var7, ur2 ur2Var8, ur2 ur2Var9, wr2 wr2Var5, wr2 wr2Var6, wr2 wr2Var7, wr2 wr2Var8, ks2 ks2Var4, wr2 wr2Var9, ks2 ks2Var5, wr2 wr2Var10, wr2 wr2Var11, wr2 wr2Var12, ks2 ks2Var6, ks2 ks2Var7, wr2 wr2Var13, wr2 wr2Var14, wr2 wr2Var15, wr2 wr2Var16, ur2 ur2Var10, wr2 wr2Var17, ur2 ur2Var11, wr2 wr2Var18, ur2 ur2Var12, wr2 wr2Var19, ur2 ur2Var13, wr2 wr2Var20, ks2 ks2Var8, ks2 ks2Var9, ks2 ks2Var10, ks2 ks2Var11, ks2 ks2Var12, wr2 wr2Var21, ks2 ks2Var13, ks2 ks2Var14, ks2 ks2Var15, ks2 ks2Var16, ks2 ks2Var17, ks2 ks2Var18, ks2 ks2Var19, ks2 ks2Var20, ks2 ks2Var21, wr2 wr2Var22, wr2 wr2Var23, ks2 ks2Var22, ks2 ks2Var23, ks2 ks2Var24, ls2 ls2Var, ms2 ms2Var, ls2 ls2Var2, ls2 ls2Var3, ks2 ks2Var25, ks2 ks2Var26, ur2 ur2Var14, wr2 wr2Var24, wr2 wr2Var25, wr2 wr2Var26, ks2 ks2Var27, wr2 wr2Var27, ks2 ks2Var28, wr2 wr2Var28, ks2 ks2Var29, ks2 ks2Var30, ks2 ks2Var31, ks2 ks2Var32, wr2 wr2Var29, wr2 wr2Var30, ks2 ks2Var33, ls2 ls2Var4, ks2 ks2Var34, ks2 ks2Var35, ls2 ls2Var5, wr2 wr2Var31, wr2 wr2Var32, wr2 wr2Var33, wr2 wr2Var34, ks2 ks2Var36, ks2 ks2Var37, ks2 ks2Var38, wr2 wr2Var35, wr2 wr2Var36, wr2 wr2Var37, ms2 ms2Var2, os2 os2Var, ls2 ls2Var6, ls2 ls2Var7, ms2 ms2Var3, ns2 ns2Var, ps2 ps2Var, ks2 ks2Var39, ls2 ls2Var8, ls2 ls2Var9, ns2 ns2Var2, wr2 wr2Var38, wr2 wr2Var39, ks2 ks2Var40, wr2 wr2Var40, wr2 wr2Var41, long j, ks2 ks2Var41, wr2 wr2Var42, wr2 wr2Var43, wr2 wr2Var44, wr2 wr2Var45, ur2 ur2Var15, wr2 wr2Var46, ur2 ur2Var16) {
        wr2Var22.getClass();
        wr2Var23.getClass();
        this.a = ur2Var;
        this.b = wr2Var;
        this.c = ks2Var;
        this.d = wr2Var2;
        this.e = ks2Var2;
        this.f = ur2Var2;
        this.g = ur2Var3;
        this.h = ur2Var4;
        this.i = wr2Var3;
        this.j = ur2Var5;
        this.k = ur2Var6;
        this.l = ks2Var3;
        this.m = wr2Var4;
        this.n = ur2Var7;
        this.o = ur2Var8;
        this.p = ur2Var9;
        this.q = wr2Var5;
        this.r = wr2Var6;
        this.s = wr2Var7;
        this.t = wr2Var8;
        this.u = ks2Var4;
        this.v = wr2Var9;
        this.w = ks2Var5;
        this.x = wr2Var10;
        this.y = wr2Var11;
        this.z = wr2Var12;
        this.A = ks2Var6;
        this.B = ks2Var7;
        this.C = wr2Var13;
        this.D = wr2Var14;
        this.E = wr2Var15;
        this.F = wr2Var16;
        this.G = ur2Var10;
        this.H = wr2Var17;
        this.I = ur2Var11;
        this.J = wr2Var18;
        this.K = ur2Var12;
        this.L = wr2Var19;
        this.M = ur2Var13;
        this.N = wr2Var20;
        this.O = ks2Var8;
        this.P = ks2Var9;
        this.Q = ks2Var10;
        this.R = ks2Var11;
        this.S = ks2Var12;
        this.T = wr2Var21;
        this.U = ks2Var13;
        this.V = ks2Var14;
        this.W = ks2Var15;
        this.X = ks2Var16;
        this.Y = ks2Var17;
        this.Z = ks2Var18;
        this.a0 = ks2Var19;
        this.b0 = ks2Var20;
        this.c0 = ks2Var21;
        this.d0 = wr2Var22;
        this.e0 = wr2Var23;
        this.f0 = ks2Var22;
        this.g0 = ks2Var23;
        this.h0 = ks2Var24;
        this.i0 = ls2Var;
        this.j0 = ms2Var;
        this.k0 = ls2Var2;
        this.l0 = ls2Var3;
        this.m0 = ks2Var25;
        this.n0 = ks2Var26;
        this.o0 = ur2Var14;
        this.p0 = wr2Var24;
        this.q0 = wr2Var25;
        this.r0 = wr2Var26;
        this.s0 = ks2Var27;
        this.t0 = wr2Var27;
        this.u0 = ks2Var28;
        this.v0 = wr2Var28;
        this.w0 = ks2Var29;
        this.x0 = ks2Var30;
        this.y0 = ks2Var31;
        this.z0 = ks2Var32;
        this.A0 = wr2Var29;
        this.B0 = wr2Var30;
        this.C0 = ks2Var33;
        this.D0 = ls2Var4;
        this.E0 = ks2Var34;
        this.F0 = ks2Var35;
        this.G0 = ls2Var5;
        this.H0 = wr2Var31;
        this.I0 = wr2Var32;
        this.J0 = wr2Var33;
        this.K0 = wr2Var34;
        this.L0 = ks2Var36;
        this.M0 = ks2Var37;
        this.N0 = ks2Var38;
        this.O0 = wr2Var35;
        this.P0 = wr2Var36;
        this.Q0 = wr2Var37;
        this.R0 = ms2Var2;
        this.S0 = os2Var;
        this.T0 = ls2Var6;
        this.U0 = ls2Var7;
        this.V0 = ms2Var3;
        this.W0 = ns2Var;
        this.X0 = ps2Var;
        this.Y0 = ks2Var39;
        this.Z0 = ls2Var8;
        this.a1 = ls2Var9;
        this.b1 = ns2Var2;
        this.c1 = wr2Var38;
        this.d1 = wr2Var39;
        this.e1 = ks2Var40;
        this.f1 = wr2Var40;
        this.g1 = wr2Var41;
        this.h1 = j;
        this.i1 = ks2Var41;
        this.j1 = wr2Var42;
        this.k1 = wr2Var43;
        this.l1 = wr2Var44;
        this.m1 = wr2Var45;
        this.n1 = ur2Var15;
        this.o1 = wr2Var46;
        this.p1 = ur2Var16;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof a66)) {
            return false;
        }
        a66 a66Var = (a66) obj;
        return this.a.equals(a66Var.a) && this.b.equals(a66Var.b) && this.c.equals(a66Var.c) && this.d.equals(a66Var.d) && this.e.equals(a66Var.e) && this.f.equals(a66Var.f) && this.g.equals(a66Var.g) && this.h.equals(a66Var.h) && this.i.equals(a66Var.i) && this.j.equals(a66Var.j) && this.k.equals(a66Var.k) && this.l.equals(a66Var.l) && this.m.equals(a66Var.m) && this.n.equals(a66Var.n) && this.o.equals(a66Var.o) && this.p.equals(a66Var.p) && this.q.equals(a66Var.q) && this.r.equals(a66Var.r) && this.s.equals(a66Var.s) && this.t.equals(a66Var.t) && this.u.equals(a66Var.u) && this.v.equals(a66Var.v) && this.w.equals(a66Var.w) && this.x.equals(a66Var.x) && this.y.equals(a66Var.y) && this.z.equals(a66Var.z) && this.A.equals(a66Var.A) && this.B.equals(a66Var.B) && this.C.equals(a66Var.C) && this.D.equals(a66Var.D) && this.E.equals(a66Var.E) && this.F.equals(a66Var.F) && this.G.equals(a66Var.G) && this.H.equals(a66Var.H) && this.I.equals(a66Var.I) && this.J.equals(a66Var.J) && this.K.equals(a66Var.K) && this.L.equals(a66Var.L) && this.M.equals(a66Var.M) && this.N.equals(a66Var.N) && this.O.equals(a66Var.O) && this.P.equals(a66Var.P) && this.Q.equals(a66Var.Q) && this.R.equals(a66Var.R) && this.S.equals(a66Var.S) && this.T.equals(a66Var.T) && this.U.equals(a66Var.U) && this.V.equals(a66Var.V) && this.W.equals(a66Var.W) && this.X.equals(a66Var.X) && this.Y.equals(a66Var.Y) && this.Z.equals(a66Var.Z) && this.a0.equals(a66Var.a0) && this.b0.equals(a66Var.b0) && this.c0.equals(a66Var.c0) && ye4.p(this.d0, a66Var.d0) && ye4.p(this.e0, a66Var.e0) && this.f0.equals(a66Var.f0) && this.g0.equals(a66Var.g0) && this.h0.equals(a66Var.h0) && this.i0.equals(a66Var.i0) && this.j0.equals(a66Var.j0) && this.k0.equals(a66Var.k0) && this.l0.equals(a66Var.l0) && this.m0.equals(a66Var.m0) && this.n0.equals(a66Var.n0) && this.o0.equals(a66Var.o0) && this.p0.equals(a66Var.p0) && this.q0.equals(a66Var.q0) && this.r0.equals(a66Var.r0) && this.s0.equals(a66Var.s0) && this.t0.equals(a66Var.t0) && this.u0.equals(a66Var.u0) && this.v0.equals(a66Var.v0) && this.w0.equals(a66Var.w0) && this.x0.equals(a66Var.x0) && this.y0.equals(a66Var.y0) && this.z0.equals(a66Var.z0) && this.A0.equals(a66Var.A0) && this.B0.equals(a66Var.B0) && this.C0.equals(a66Var.C0) && this.D0.equals(a66Var.D0) && this.E0.equals(a66Var.E0) && this.F0.equals(a66Var.F0) && this.G0.equals(a66Var.G0) && this.H0.equals(a66Var.H0) && this.I0.equals(a66Var.I0) && this.J0.equals(a66Var.J0) && this.K0.equals(a66Var.K0) && this.L0.equals(a66Var.L0) && this.M0.equals(a66Var.M0) && this.N0.equals(a66Var.N0) && this.O0.equals(a66Var.O0) && this.P0.equals(a66Var.P0) && this.Q0.equals(a66Var.Q0) && this.R0.equals(a66Var.R0) && this.S0.equals(a66Var.S0) && this.T0.equals(a66Var.T0) && this.U0.equals(a66Var.U0) && this.V0.equals(a66Var.V0) && this.W0.equals(a66Var.W0) && this.X0.equals(a66Var.X0) && this.Y0.equals(a66Var.Y0) && this.Z0.equals(a66Var.Z0) && this.a1.equals(a66Var.a1) && this.b1.equals(a66Var.b1) && this.c1.equals(a66Var.c1) && this.d1.equals(a66Var.d1) && this.e1.equals(a66Var.e1) && this.f1.equals(a66Var.f1) && this.g1.equals(a66Var.g1) && this.h1 == a66Var.h1 && this.i1.equals(a66Var.i1) && this.j1.equals(a66Var.j1) && this.k1.equals(a66Var.k1) && this.l1.equals(a66Var.l1) && this.m1.equals(a66Var.m1) && this.n1.equals(a66Var.n1) && this.o1.equals(a66Var.o1) && this.p1.equals(a66Var.p1);
    }

    public final int hashCode() {
        return this.p1.hashCode() + pk0.b(rx1.f(this.n1, pk0.b(pk0.b(pk0.b(pk0.b(rx1.d(j55.d(this.h1, pk0.b(pk0.b(rx1.d(pk0.b(pk0.b((this.b1.hashCode() + rx1.g(this.a1, rx1.g(this.Z0, rx1.d((this.X0.hashCode() + ((this.W0.hashCode() + ((this.V0.hashCode() + rx1.g(this.U0, rx1.g(this.T0, (this.S0.hashCode() + ((this.R0.hashCode() + pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(rx1.g(this.G0, rx1.d(rx1.d(rx1.g(this.D0, rx1.d(pk0.b(pk0.b(rx1.d(rx1.d(rx1.d(rx1.d(pk0.b(rx1.d(pk0.b(rx1.d(pk0.b(pk0.b(pk0.b(rx1.f(this.o0, rx1.d(rx1.d(rx1.g(this.l0, rx1.g(this.k0, (this.j0.hashCode() + rx1.g(this.i0, rx1.d(rx1.d(rx1.d(pk0.b(pk0.b(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(pk0.b(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(pk0.b(rx1.f(this.M, pk0.b(rx1.f(this.K, pk0.b(rx1.f(this.I, pk0.b(rx1.f(this.G, pk0.b(pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(pk0.b(pk0.b(pk0.b(rx1.d(pk0.b(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.p, rx1.f(this.o, rx1.f(this.n, pk0.b(rx1.d(rx1.f(this.k, rx1.f(this.j, pk0.b(rx1.f(this.h, rx1.f(this.g, rx1.f(this.f, rx1.d(pk0.b(rx1.d(pk0.b(this.a.hashCode() * 31, this.b, 31), 31, this.c), this.d, 31), 31, this.e), 31), 31), 31), this.i, 31), 31), 31), 31, this.l), this.m, 31), 31), 31), 31), this.q, 31), this.r, 31), this.s, 31), this.t, 31), 31, this.u), this.v, 31), 31, this.w), this.x, 31), this.y, 31), this.z, 31), 31, this.A), 31, this.B), this.C, 31), this.D, 31), this.E, 31), this.F, 31), 31), this.H, 31), 31), this.J, 31), 31), this.L, 31), 31), this.N, 31), 31, this.O), 31, this.P), 31, this.Q), 31, this.R), 31, this.S), this.T, 31), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), 31, this.b0), 31, this.c0), this.d0, 31), this.e0, 31), 31, this.f0), 31, this.g0), 31, this.h0), 31)) * 31, 31), 31), 31, this.m0), 31, this.n0), 31), this.p0, 31), this.q0, 31), this.r0, 31), 31, this.s0), this.t0, 31), 31, this.u0), this.v0, 31), 31, this.w0), 31, this.x0), 31, this.y0), 31, this.z0), this.A0, 31), this.B0, 31), 31, this.C0), 31), 31, this.E0), 31, this.F0), 31), this.H0, 31), this.I0, 31), this.J0, 31), this.K0, 31), 31, this.L0), 31, this.M0), 31, this.N0), this.O0, 31), this.P0, 31), this.Q0, 31)) * 31)) * 31, 31), 31)) * 31)) * 31)) * 31, 31, this.Y0), 31), 31)) * 31, this.c1, 31), this.d1, 31), 31, this.e1), this.f1, 31), this.g1, 31), 31), 31, this.i1), this.j1, 31), this.k1, 31), this.l1, 31), this.m1, 31), 31), this.o1, 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("PlatformContextMenuCallbacks(onAddConsole=");
        sb.append(this.a);
        sb.append(", onEditConsole=");
        sb.append(this.b);
        sb.append(", onSetConsoleCustomLabel=");
        f33.u(sb, this.c, ", onGeneratePsVitaFiles=", this.d, ", onToggleRomShortcut=");
        sb.append(this.e);
        sb.append(", onSearch=");
        sb.append(this.f);
        sb.append(", onOpenGlobalSearch=");
        pk0.w(this.g, this.h, ", onClearSearch=", ", onApplyRomSearch=", sb);
        f33.t(sb, this.i, ", onIncreaseDensity=", this.j, ", onDecreaseDensity=");
        sb.append(this.k);
        sb.append(", onChangeLayout=");
        sb.append(this.l);
        sb.append(", onChangeCategoryLayout=");
        f33.t(sb, this.m, ", onToggleEditMode=", this.n, ", onIncreaseCategoryGridDensity=");
        pk0.w(this.o, this.p, ", onDecreaseCategoryGridDensity=", ", onSetCategoryGridRows=", sb);
        rx1.B(sb, this.q, ", onSetCategoryGridColumns=", this.r, ", onSetCategoryListRows=");
        rx1.B(sb, this.s, ", onSetCategoryXmbIconSizeLevel=", this.t, ", onSetCategoryHorizontalGridEnabled=");
        f33.u(sb, this.u, ", onSetCategoryHorizontalGridOverrideEnabled=", this.v, ", onSetHorizontalGridEnabled=");
        f33.u(sb, this.w, ", onSetHorizontalGridOverrideEnabled=", this.x, ", onSetRomBrowserGridRows=");
        rx1.B(sb, this.y, ", onSetRomBrowserGridColumns=", this.z, ", onSetRomBrowserGridRowsForTab=");
        f33.v(sb, this.A, ", onSetRomBrowserGridColumnsForTab=", this.B, ", onSetRomBrowserCompactRows=");
        rx1.B(sb, this.C, ", onSetRomBrowserHorizontalIconSizeLevel=", this.D, ", onSetRomBrowserVerticalNeighbors=");
        rx1.B(sb, this.E, ", onSetRomBrowserXmbIconSizeLevel=", this.F, ", isMinimalModeEnabled=");
        f33.s(sb, this.G, ", onSetMinimalModeEnabled=", this.H, ", isHideEmptyConsolesEnabled=");
        f33.s(sb, this.I, ", onSetHideEmptyConsolesEnabled=", this.J, ", isPersistentNavBarOnPlatforms=");
        f33.s(sb, this.K, ", onSetPersistentNavBarOnPlatforms=", this.L, ", isPersistentNavBarOnGames=");
        f33.s(sb, this.M, ", onSetPersistentNavBarOnGames=", this.N, ", onSetPreferZoomedArtwork=");
        f33.v(sb, this.O, ", onSetArtworkAlignment=", this.P, ", onSetTitleSectionMode=");
        f33.v(sb, this.Q, ", onSetTrophyIconCorner=", this.R, ", onSetTrophyIconAlpha=");
        f33.u(sb, this.S, ", onShowTrophyAlphaEditor=", this.T, ", onSetTabHideDiscFiles=");
        f33.v(sb, this.U, ", onSetTabPreferNativeRomIconSize=", this.V, ", onSetTabsPreferNativeRomIconSize=");
        f33.v(sb, this.W, ", onSetTabRomIconAspectRatioPresetId=", this.X, ", onSetRomPreferNativeRomIconSize=");
        f33.v(sb, this.Y, ", onSetRomIconAspectRatioPresetId=", this.Z, ", onSetRomArtworkAlignment=");
        f33.v(sb, this.a0, ", onSetRomTitleSectionMode=", this.b0, ", onSetRomCustomName=");
        f33.u(sb, this.c0, ", onStartRomIconReanchor=", this.d0, ", onStartRomBackgroundReanchor=");
        sb.append(this.e0);
        sb.append(", onSetRomTrophyIconCorner=");
        sb.append(this.f0);
        sb.append(", onSetRomTrophyIconAlpha=");
        f33.v(sb, this.g0, ", onUpdateRomLaunchPreference=", this.h0, ", onUpdateRomLinkedPreference=");
        sb.append(this.i0);
        sb.append(", onUpdateRomCommandPreference=");
        sb.append(this.j0);
        sb.append(", onSetRomInCollection=");
        sb.append(this.k0);
        sb.append(", onToggleRomVisibility=");
        sb.append(this.l0);
        sb.append(", onToggleAppVisibility=");
        f33.v(sb, this.m0, ", onShowGameInfo=", this.n0, ", onShowRetroAchievements=");
        f33.s(sb, this.o0, ", onShowRetroAchievementsForRom=", this.p0, ", onChangeRetroAchievementsTitleForRom=");
        rx1.B(sb, this.q0, ", onDownloadRommRom=", this.r0, ", onDownloadAllRommRoms=");
        f33.u(sb, this.s0, ", onDeleteRommRom=", this.t0, ", onDeleteAllRommRoms=");
        f33.u(sb, this.u0, ", isRommRomDownloaded=", this.v0, ", onManageConsoleMedia=");
        f33.v(sb, this.w0, ", onResetConsoleMedia=", this.x0, ", onManageFolderMedia=");
        f33.v(sb, this.y0, ", onResetFolderMedia=", this.z0, ", onResetAllConsoleMedia=");
        rx1.B(sb, this.A0, ", onDeleteConsoleMedia=", this.B0, ", onManageRomMedia=");
        sb.append(this.C0);
        sb.append(", onManageRomMediaAtIndex=");
        sb.append(this.D0);
        sb.append(", onDeleteConsoleRomsMedia=");
        f33.v(sb, this.E0, ", onDeleteRomMedia=", this.F0, ", onDeleteRomMediaAtIndex=");
        sb.append(this.G0);
        sb.append(", onSetRomSoundbite=");
        sb.append(this.H0);
        sb.append(", onDeleteRomSoundbite=");
        rx1.B(sb, this.I0, ", onManageRomQuickAccessIcon=", this.J0, ", onDeleteRomQuickAccessIcon=");
        sb.append(this.K0);
        sb.append(", onGenerateHashes=");
        sb.append(this.L0);
        sb.append(", onRefreshRetroData=");
        f33.v(sb, this.M0, ", onRefreshRommRetroData=", this.N0, ", onGenerateHashesAllConsoles=");
        rx1.B(sb, this.O0, ", onRefreshRetroDataAllConsoles=", this.P0, ", onRefreshRommRetroDataAllConsoles=");
        sb.append(this.Q0);
        sb.append(", onScrapeConsole=");
        sb.append(this.R0);
        sb.append(", onScrapeConsoleWithMode=");
        sb.append(this.S0);
        sb.append(", onScrapeConsoleMedia=");
        sb.append(this.T0);
        sb.append(", onScrapeFolderMedia=");
        sb.append(this.U0);
        sb.append(", onScrapeRom=");
        sb.append(this.V0);
        sb.append(", onScrapeRomWithMode=");
        sb.append(this.W0);
        sb.append(", onScrapeRomWithQueryMode=");
        sb.append(this.X0);
        sb.append(", onScrapeSelectedHomeIcon=");
        sb.append(this.Y0);
        sb.append(", onScrapeRomCustom=");
        sb.append(this.Z0);
        sb.append(", onScrapeAllConsoles=");
        sb.append(this.a1);
        sb.append(", onScrapeAllConsolesWithMode=");
        sb.append(this.b1);
        sb.append(", isScraperSourceConfigured=");
        rx1.B(sb, this.c1, ", onConfigureScraperSource=", this.d1, ", onShowScraperSelectionMenu=");
        f33.u(sb, this.e1, ", onShowScraperProgressMenu=", this.f1, ", setScraperContextMenuPinned=");
        sb.append(this.g1);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.h1);
        sb.append(", buildBackgroundTaskDetailItems=");
        sb.append(this.i1);
        sb.append(", canContinueBackgroundTask=");
        sb.append(this.j1);
        rx1.C(sb, ", canCancelBackgroundTask=", this.k1, ", onContinueBackgroundTask=", this.l1);
        sb.append(", onCancelBackgroundTask=");
        sb.append(this.m1);
        sb.append(", onShowBackgroundTaskUnavailable=");
        sb.append(this.n1);
        sb.append(", onRefreshConsoleMetadata=");
        sb.append(this.o1);
        sb.append(", onDismiss=");
        sb.append(this.p1);
        sb.append(")");
        return sb.toString();
    }
}
