package defpackage;

import java.util.LinkedHashMap;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class aq0 {
    public static final ej7 b;
    public static final lj2 c;
    public static final LinkedHashMap d;
    public static final aq0 e;
    public static final aq0 f;
    public static final aq0 g;
    public static final aq0 h;
    public static final aq0 i;
    public static final aq0 j;
    public static final aq0 k;
    public static final aq0 l;
    public static final aq0 m;
    public static final aq0 n;
    public static final aq0 o;
    public static final aq0 p;
    public static final aq0 q;
    public static final aq0 r;
    public static final aq0 s;
    public static final aq0 t;
    public final String a;

    static {
        ej7 ej7Var = new ej7(24);
        b = ej7Var;
        c = new lj2(29);
        d = new LinkedHashMap();
        ej7.s(ej7Var, "SSL_RSA_WITH_NULL_MD5");
        ej7.s(ej7Var, "SSL_RSA_WITH_NULL_SHA");
        ej7.s(ej7Var, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        ej7.s(ej7Var, "SSL_RSA_WITH_RC4_128_MD5");
        ej7.s(ej7Var, "SSL_RSA_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        ej7.s(ej7Var, "SSL_RSA_WITH_DES_CBC_SHA");
        e = ej7.s(ej7Var, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        ej7.s(ej7Var, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        ej7.s(ej7Var, "SSL_DH_anon_WITH_RC4_128_MD5");
        ej7.s(ej7Var, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        ej7.s(ej7Var, "SSL_DH_anon_WITH_DES_CBC_SHA");
        ej7.s(ej7Var, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_KRB5_WITH_DES_CBC_SHA");
        ej7.s(ej7Var, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_KRB5_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_KRB5_WITH_DES_CBC_MD5");
        ej7.s(ej7Var, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        ej7.s(ej7Var, "TLS_KRB5_WITH_RC4_128_MD5");
        ej7.s(ej7Var, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        ej7.s(ej7Var, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        ej7.s(ej7Var, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        ej7.s(ej7Var, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        f = ej7.s(ej7Var, "TLS_RSA_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        g = ej7.s(ej7Var, "TLS_RSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_RSA_WITH_NULL_SHA256");
        ej7.s(ej7Var, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        ej7.s(ej7Var, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_PSK_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_PSK_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_PSK_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_RSA_WITH_SEED_CBC_SHA");
        h = ej7.s(ej7Var, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        i = ej7.s(ej7Var, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        ej7.s(ej7Var, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        ej7.s(ej7Var, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        ej7.s(ej7Var, "TLS_FALLBACK_SCSV");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_NULL_SHA");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        j = ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        k = ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_anon_WITH_NULL_SHA");
        ej7.s(ej7Var, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        ej7.s(ej7Var, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        l = ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        m = ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        ej7.s(ej7Var, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        n = ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        o = ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        ej7.s(ej7Var, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        ej7.s(ej7Var, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        ej7.s(ej7Var, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        p = ej7.s(ej7Var, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        q = ej7.s(ej7Var, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        ej7.s(ej7Var, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        ej7.s(ej7Var, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        r = ej7.s(ej7Var, "TLS_AES_128_GCM_SHA256");
        s = ej7.s(ej7Var, "TLS_AES_256_GCM_SHA384");
        t = ej7.s(ej7Var, "TLS_CHACHA20_POLY1305_SHA256");
        ej7.s(ej7Var, "TLS_AES_128_CCM_SHA256");
        ej7.s(ej7Var, "TLS_AES_128_CCM_8_SHA256");
    }

    public aq0(String str) {
        this.a = str;
    }

    public final String toString() {
        return this.a;
    }
}
