package defpackage;

import android.content.Context;
import android.view.View;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class bm3 {
    public final r43 A;
    public final bw3 B;
    public final n63 C;
    public final pp8 D;
    public final String E;
    public final xk8 F;
    public final ur2 G;
    public final ur2 H;
    public final ur2 I;
    public final r93 J;
    public final r93 K;
    public final r93 L;
    public final wr2 M;
    public final wr2 N;
    public final wr2 O;
    public final wr2 P;
    public final wr2 Q;
    public final ur2 R;
    public final ur2 S;
    public final ur2 T;
    public final wr2 U;
    public final wr2 V;
    public final ur2 W;
    public final int X;
    public final boolean Y;
    public final boolean Z;
    public final x5 a;
    public final boolean a0;
    public final tu3 b;
    public final boolean b0;
    public final ft3 c;
    public final boolean c0;
    public final Context d;
    public final boolean d0;
    public final Context e;
    public final jf8 e0;
    public final nb1 f;
    public final boolean f0;
    public final View g;
    public final boolean g0;
    public final mi2 h;
    public final boolean h0;
    public final lp3 i;
    public final AtomicBoolean i0;
    public final ze0 j;
    public final x03 j0;
    public final bt2 k;
    public final fb3 l;
    public final ww6 m;
    public final p32 n;
    public final jm3 o;
    public final jd3 p;
    public final gr3 q;
    public final uk3 r;
    public final k93 s;
    public final dg3 t;
    public final dj3 u;
    public final bj3 v;
    public final h33 w;
    public final Map x;
    public final Map y;
    public final rk3 z;

    public bm3(x5 x5Var, tu3 tu3Var, ft3 ft3Var, Context context, Context context2, nb1 nb1Var, View view, mi2 mi2Var, lp3 lp3Var, ze0 ze0Var, bt2 bt2Var, fb3 fb3Var, ww6 ww6Var, p32 p32Var, jm3 jm3Var, jd3 jd3Var, gr3 gr3Var, uk3 uk3Var, k93 k93Var, dg3 dg3Var, dj3 dj3Var, bj3 bj3Var, h33 h33Var, Map map, Map map2, rk3 rk3Var, r43 r43Var, bw3 bw3Var, n63 n63Var, p83 p83Var, pp8 pp8Var, String str, xk8 xk8Var, ur2 ur2Var, ur2 ur2Var2, ur2 ur2Var3, r93 r93Var, r93 r93Var2, r93 r93Var3, de3 de3Var, de3 de3Var2, f43 f43Var, f43 f43Var2, de3 de3Var3, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, wr2 wr2Var, wr2 wr2Var2, ur2 ur2Var7, int i, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, jf8 jf8Var, boolean z7, boolean z8, boolean z9, AtomicBoolean atomicBoolean, x03 x03Var) {
        view.getClass();
        ze0Var.getClass();
        bt2Var.getClass();
        ww6Var.getClass();
        p32Var.getClass();
        gr3Var.getClass();
        dg3Var.getClass();
        bj3Var.getClass();
        map2.getClass();
        rk3Var.getClass();
        r43Var.getClass();
        bw3Var.getClass();
        n63Var.getClass();
        xk8Var.getClass();
        ur2Var.getClass();
        ur2Var2.getClass();
        ur2Var3.getClass();
        de3Var.getClass();
        de3Var2.getClass();
        f43Var.getClass();
        f43Var2.getClass();
        de3Var3.getClass();
        ur2Var4.getClass();
        ur2Var5.getClass();
        ur2Var6.getClass();
        wr2Var.getClass();
        wr2Var2.getClass();
        ur2Var7.getClass();
        jf8Var.getClass();
        atomicBoolean.getClass();
        this.a = x5Var;
        this.b = tu3Var;
        this.c = ft3Var;
        this.d = context;
        this.e = context2;
        this.f = nb1Var;
        this.g = view;
        this.h = mi2Var;
        this.i = lp3Var;
        this.j = ze0Var;
        this.k = bt2Var;
        this.l = fb3Var;
        this.m = ww6Var;
        this.n = p32Var;
        this.o = jm3Var;
        this.p = jd3Var;
        this.q = gr3Var;
        this.r = uk3Var;
        this.s = k93Var;
        this.t = dg3Var;
        this.u = dj3Var;
        this.v = bj3Var;
        this.w = h33Var;
        this.x = map;
        this.y = map2;
        this.z = rk3Var;
        this.A = r43Var;
        this.B = bw3Var;
        this.C = n63Var;
        this.D = pp8Var;
        this.E = str;
        this.F = xk8Var;
        this.G = ur2Var;
        this.H = ur2Var2;
        this.I = ur2Var3;
        this.J = r93Var;
        this.K = r93Var2;
        this.L = r93Var3;
        this.M = de3Var;
        this.N = de3Var2;
        this.O = f43Var;
        this.P = f43Var2;
        this.Q = de3Var3;
        this.R = ur2Var4;
        this.S = ur2Var5;
        this.T = ur2Var6;
        this.U = wr2Var;
        this.V = wr2Var2;
        this.W = ur2Var7;
        this.X = i;
        this.Y = z;
        this.Z = z2;
        this.a0 = z3;
        this.b0 = z4;
        this.c0 = z5;
        this.d0 = z6;
        this.e0 = jf8Var;
        this.f0 = z7;
        this.g0 = z8;
        this.h0 = z9;
        this.i0 = atomicBoolean;
        this.j0 = x03Var;
    }
}
