package defpackage;

import java.util.ArrayList;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class d84 {
    public final boolean A;
    public final yc3 A0;
    public final boolean A1;
    public final lp A2;
    public final boolean B;
    public final yc3 B0;
    public final boolean B1;
    public final iz2 C;
    public final int C0;
    public final boolean C1;
    public final float D;
    public final float D0;
    public final boolean D1;
    public final boolean E;
    public final int E0;
    public final boolean E1;
    public final boolean F;
    public final boolean F0;
    public final boolean F1;
    public final List G;
    public final int G0;
    public final v45 G1;
    public final List H;
    public final int H0;
    public final o45 H1;
    public final float I;
    public final boolean I0;
    public final boolean I1;
    public final boolean J;
    public final boolean J0;
    public final l15 J1;
    public final float K;
    public final boolean K0;
    public final String K1;
    public final String L;
    public final boolean L0;
    public final String L1;
    public final boolean M;
    public final boolean M0;
    public final boolean M1;
    public final List N;
    public final boolean N0;
    public final boolean N1;
    public final String O;
    public final boolean O0;
    public final boolean O1;
    public final jf8 P;
    public final boolean P0;
    public final boolean P1;
    public final nl4 Q;
    public final boolean Q0;
    public final String Q1;
    public final pl4 R;
    public final boolean R0;
    public final Long R1;
    public final pl4 S;
    public final float S0;
    public final Integer S1;
    public final boolean T;
    public final boolean T0;
    public final Integer T1;
    public final String U;
    public final boolean U0;
    public final String U1;
    public final List V;
    public final boolean V0;
    public final boolean V1;
    public final List W;
    public final boolean W0;
    public final int W1;
    public final boolean X;
    public final boolean X0;
    public final int X1;
    public final boolean Y;
    public final float Y0;
    public final Long Y1;
    public final mg8 Z;
    public final float Z0;
    public final boolean Z1;
    public final hn a;
    public final boolean a0;
    public final float a1;
    public final String a2;
    public final boolean b;
    public final boolean b0;
    public final pq b1;
    public final String b2;
    public final tg3 c;
    public final boolean c0;
    public final ye7 c1;
    public final Long c2;
    public final xw d;
    public final boolean d0;
    public final zc8 d1;
    public final boolean d2;
    public final boolean e;
    public final boolean e0;
    public final e08 e1;
    public final boolean e2;
    public final boolean f;
    public final boolean f0;
    public final su1 f1;
    public final String f2;
    public final b32 g;
    public final boolean g0;
    public final aw1 g1;
    public final Long g2;
    public final c32 h;
    public final boolean h0;
    public final String h1;
    public final Integer h2;
    public final boolean i;
    public final boolean i0;
    public final String i1;
    public final Integer i2;
    public final boolean j;
    public final boolean j0;
    public final boolean j1;
    public final ArrayList j2;
    public final boolean k;
    public final int k0;
    public final boolean k1;
    public final int k2;
    public final boolean l;
    public final int l0;
    public final boolean l1;
    public final boolean l2;
    public final boolean m;
    public final boolean m0;
    public final boolean m1;
    public final boolean m2;
    public final boolean n;
    public final la0 n0;
    public final boolean n1;
    public final boolean n2;
    public final boolean o;
    public final boolean o0;
    public final boolean o1;
    public final nr8 o2;
    public final boolean p;
    public final boolean p0;
    public final boolean p1;
    public final dy1 p2;
    public final boolean q;
    public final int q0;
    public final boolean q1;
    public final boolean q2;
    public final boolean r;
    public final boolean r0;
    public final boolean r1;
    public final String r2;
    public final boolean s;
    public final v93 s0;
    public final boolean s1;
    public final hr8 s2;
    public final xk8 t;
    public final boolean t0;
    public final boolean t1;
    public final boolean t2;
    public final boolean u;
    public final fs7 u0;
    public final boolean u1;
    public final String u2;
    public final eo4 v;
    public final gs7 v0;
    public final boolean v1;
    public final String v2;
    public final ul4 w;
    public final boolean w0;
    public final int w1;
    public final boolean w2;
    public final ul4 x;
    public final boolean x0;
    public final ev4 x1;
    public final lp x2;
    public final ul4 y;
    public final yc3 y0;
    public final List y1;
    public final lp y2;
    public final boolean z;
    public final yc3 z0;
    public final int z1;
    public final lp z2;

    public d84(hn hnVar, boolean z, tg3 tg3Var, xw xwVar, boolean z2, boolean z3, b32 b32Var, c32 c32Var, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, xk8 xk8Var, boolean z15, eo4 eo4Var, ul4 ul4Var, ul4 ul4Var2, ul4 ul4Var3, boolean z16, boolean z17, boolean z18, iz2 iz2Var, float f, boolean z19, boolean z20, List list, List list2, float f2, boolean z21, float f3, String str, boolean z22, List list3, String str2, jf8 jf8Var, nl4 nl4Var, pl4 pl4Var, pl4 pl4Var2, boolean z23, String str3, List list4, List list5, boolean z24, boolean z25, mg8 mg8Var, boolean z26, boolean z27, boolean z28, boolean z29, boolean z30, boolean z31, boolean z32, boolean z33, boolean z34, boolean z35, int i, int i2, boolean z36, la0 la0Var, boolean z37, boolean z38, int i3, boolean z39, v93 v93Var, boolean z40, fs7 fs7Var, gs7 gs7Var, boolean z41, boolean z42, yc3 yc3Var, yc3 yc3Var2, yc3 yc3Var3, yc3 yc3Var4, int i4, float f4, int i5, boolean z43, int i6, int i7, boolean z44, boolean z45, boolean z46, boolean z47, boolean z48, boolean z49, boolean z50, boolean z51, boolean z52, boolean z53, float f5, boolean z54, boolean z55, boolean z56, boolean z57, boolean z58, float f6, float f7, float f8, pq pqVar, ye7 ye7Var, zc8 zc8Var, e08 e08Var, su1 su1Var, aw1 aw1Var, String str4, String str5, boolean z59, boolean z60, boolean z61, boolean z62, boolean z63, boolean z64, boolean z65, boolean z66, boolean z67, boolean z68, boolean z69, boolean z70, boolean z71, int i8, ev4 ev4Var, List list6, int i9, boolean z72, boolean z73, boolean z74, boolean z75, boolean z76, boolean z77, v45 v45Var, o45 o45Var, boolean z78, l15 l15Var, String str6, String str7, boolean z79, boolean z80, boolean z81, boolean z82, String str8, Long l, Integer num, Integer num2, String str9, boolean z83, int i10, int i11, Long l2, boolean z84, String str10, String str11, Long l3, boolean z85, boolean z86, String str12, Long l4, Integer num3, Integer num4, ArrayList arrayList, int i12, boolean z87, boolean z88, boolean z89, nr8 nr8Var, dy1 dy1Var, boolean z90, String str13, hr8 hr8Var, boolean z91, String str14, String str15, boolean z92, lp lpVar, lp lpVar2, lp lpVar3, lp lpVar4) {
        hnVar.getClass();
        tg3Var.getClass();
        c32Var.getClass();
        xk8Var.getClass();
        eo4Var.getClass();
        ul4Var.getClass();
        ul4Var2.getClass();
        ul4Var3.getClass();
        iz2Var.getClass();
        list.getClass();
        list2.getClass();
        list3.getClass();
        str2.getClass();
        jf8Var.getClass();
        nl4Var.getClass();
        pl4Var.getClass();
        pl4Var2.getClass();
        list4.getClass();
        list5.getClass();
        mg8Var.getClass();
        la0Var.getClass();
        v93Var.getClass();
        fs7Var.getClass();
        gs7Var.getClass();
        yc3Var.getClass();
        yc3Var2.getClass();
        yc3Var3.getClass();
        yc3Var4.getClass();
        pqVar.getClass();
        ye7Var.getClass();
        zc8Var.getClass();
        e08Var.getClass();
        su1Var.getClass();
        aw1Var.getClass();
        str4.getClass();
        str5.getClass();
        v45Var.getClass();
        o45Var.getClass();
        hr8Var.getClass();
        lpVar.getClass();
        lpVar2.getClass();
        lpVar3.getClass();
        lpVar4.getClass();
        this.a = hnVar;
        this.b = z;
        this.c = tg3Var;
        this.d = xwVar;
        this.e = z2;
        this.f = z3;
        this.g = b32Var;
        this.h = c32Var;
        this.i = z4;
        this.j = z5;
        this.k = z6;
        this.l = z7;
        this.m = z8;
        this.n = z9;
        this.o = z10;
        this.p = z11;
        this.q = z12;
        this.r = z13;
        this.s = z14;
        this.t = xk8Var;
        this.u = z15;
        this.v = eo4Var;
        this.w = ul4Var;
        this.x = ul4Var2;
        this.y = ul4Var3;
        this.z = z16;
        this.A = z17;
        this.B = z18;
        this.C = iz2Var;
        this.D = f;
        this.E = z19;
        this.F = z20;
        this.G = list;
        this.H = list2;
        this.I = f2;
        this.J = z21;
        this.K = f3;
        this.L = str;
        this.M = z22;
        this.N = list3;
        this.O = str2;
        this.P = jf8Var;
        this.Q = nl4Var;
        this.R = pl4Var;
        this.S = pl4Var2;
        this.T = z23;
        this.U = str3;
        this.V = list4;
        this.W = list5;
        this.X = z24;
        this.Y = z25;
        this.Z = mg8Var;
        this.a0 = z26;
        this.b0 = z27;
        this.c0 = z28;
        this.d0 = z29;
        this.e0 = z30;
        this.f0 = z31;
        this.g0 = z32;
        this.h0 = z33;
        this.i0 = z34;
        this.j0 = z35;
        this.k0 = i;
        this.l0 = i2;
        this.m0 = z36;
        this.n0 = la0Var;
        this.o0 = z37;
        this.p0 = z38;
        this.q0 = i3;
        this.r0 = z39;
        this.s0 = v93Var;
        this.t0 = z40;
        this.u0 = fs7Var;
        this.v0 = gs7Var;
        this.w0 = z41;
        this.x0 = z42;
        this.y0 = yc3Var;
        this.z0 = yc3Var2;
        this.A0 = yc3Var3;
        this.B0 = yc3Var4;
        this.C0 = i4;
        this.D0 = f4;
        this.E0 = i5;
        this.F0 = z43;
        this.G0 = i6;
        this.H0 = i7;
        this.I0 = z44;
        this.J0 = z45;
        this.K0 = z46;
        this.L0 = z47;
        this.M0 = z48;
        this.N0 = z49;
        this.O0 = z50;
        this.P0 = z51;
        this.Q0 = z52;
        this.R0 = z53;
        this.S0 = f5;
        this.T0 = z54;
        this.U0 = z55;
        this.V0 = z56;
        this.W0 = z57;
        this.X0 = z58;
        this.Y0 = f6;
        this.Z0 = f7;
        this.a1 = f8;
        this.b1 = pqVar;
        this.c1 = ye7Var;
        this.d1 = zc8Var;
        this.e1 = e08Var;
        this.f1 = su1Var;
        this.g1 = aw1Var;
        this.h1 = str4;
        this.i1 = str5;
        this.j1 = z59;
        this.k1 = z60;
        this.l1 = z61;
        this.m1 = z62;
        this.n1 = z63;
        this.o1 = z64;
        this.p1 = z65;
        this.q1 = z66;
        this.r1 = z67;
        this.s1 = z68;
        this.t1 = z69;
        this.u1 = z70;
        this.v1 = z71;
        this.w1 = i8;
        this.x1 = ev4Var;
        this.y1 = list6;
        this.z1 = i9;
        this.A1 = z72;
        this.B1 = z73;
        this.C1 = z74;
        this.D1 = z75;
        this.E1 = z76;
        this.F1 = z77;
        this.G1 = v45Var;
        this.H1 = o45Var;
        this.I1 = z78;
        this.J1 = l15Var;
        this.K1 = str6;
        this.L1 = str7;
        this.M1 = z79;
        this.N1 = z80;
        this.O1 = z81;
        this.P1 = z82;
        this.Q1 = str8;
        this.R1 = l;
        this.S1 = num;
        this.T1 = num2;
        this.U1 = str9;
        this.V1 = z83;
        this.W1 = i10;
        this.X1 = i11;
        this.Y1 = l2;
        this.Z1 = z84;
        this.a2 = str10;
        this.b2 = str11;
        this.c2 = l3;
        this.d2 = z85;
        this.e2 = z86;
        this.f2 = str12;
        this.g2 = l4;
        this.h2 = num3;
        this.i2 = num4;
        this.j2 = arrayList;
        this.k2 = i12;
        this.l2 = z87;
        this.m2 = z88;
        this.n2 = z89;
        this.o2 = nr8Var;
        this.p2 = dy1Var;
        this.q2 = z90;
        this.r2 = str13;
        this.s2 = hr8Var;
        this.t2 = z91;
        this.u2 = str14;
        this.v2 = str15;
        this.w2 = z92;
        this.x2 = lpVar;
        this.y2 = lpVar2;
        this.z2 = lpVar3;
        this.A2 = lpVar4;
    }

    public final List a() {
        return this.V;
    }

    public final boolean b() {
        return this.F0;
    }

    public final int c() {
        return this.G0;
    }

    public final int d() {
        return this.H0;
    }

    public final v45 e() {
        return this.G1;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof d84)) {
            return false;
        }
        d84 d84Var = (d84) obj;
        return this.a == d84Var.a && this.b == d84Var.b && this.c == d84Var.c && this.d.equals(d84Var.d) && this.e == d84Var.e && this.f == d84Var.f && this.g == d84Var.g && this.h == d84Var.h && this.i == d84Var.i && this.j == d84Var.j && this.k == d84Var.k && this.l == d84Var.l && this.m == d84Var.m && this.n == d84Var.n && this.o == d84Var.o && this.p == d84Var.p && this.q == d84Var.q && this.r == d84Var.r && this.s == d84Var.s && this.t == d84Var.t && this.u == d84Var.u && this.v == d84Var.v && this.w == d84Var.w && this.x == d84Var.x && this.y == d84Var.y && this.z == d84Var.z && this.A == d84Var.A && this.B == d84Var.B && this.C == d84Var.C && Float.compare(this.D, d84Var.D) == 0 && this.E == d84Var.E && this.F == d84Var.F && ye4.p(this.G, d84Var.G) && ye4.p(this.H, d84Var.H) && Float.compare(this.I, d84Var.I) == 0 && this.J == d84Var.J && Float.compare(this.K, d84Var.K) == 0 && this.L.equals(d84Var.L) && this.M == d84Var.M && ye4.p(this.N, d84Var.N) && ye4.p(this.O, d84Var.O) && this.P == d84Var.P && this.Q == d84Var.Q && this.R == d84Var.R && this.S == d84Var.S && this.T == d84Var.T && ye4.p(this.U, d84Var.U) && ye4.p(this.V, d84Var.V) && ye4.p(this.W, d84Var.W) && this.X == d84Var.X && this.Y == d84Var.Y && this.Z == d84Var.Z && this.a0 == d84Var.a0 && this.b0 == d84Var.b0 && this.c0 == d84Var.c0 && this.d0 == d84Var.d0 && this.e0 == d84Var.e0 && this.f0 == d84Var.f0 && this.g0 == d84Var.g0 && this.h0 == d84Var.h0 && this.i0 == d84Var.i0 && this.j0 == d84Var.j0 && this.k0 == d84Var.k0 && this.l0 == d84Var.l0 && this.m0 == d84Var.m0 && this.n0 == d84Var.n0 && this.o0 == d84Var.o0 && this.p0 == d84Var.p0 && this.q0 == d84Var.q0 && this.r0 == d84Var.r0 && this.s0 == d84Var.s0 && this.t0 == d84Var.t0 && this.u0 == d84Var.u0 && this.v0 == d84Var.v0 && this.w0 == d84Var.w0 && this.x0 == d84Var.x0 && this.y0 == d84Var.y0 && this.z0 == d84Var.z0 && this.A0 == d84Var.A0 && this.B0 == d84Var.B0 && this.C0 == d84Var.C0 && Float.compare(this.D0, d84Var.D0) == 0 && this.E0 == d84Var.E0 && this.F0 == d84Var.F0 && this.G0 == d84Var.G0 && this.H0 == d84Var.H0 && this.I0 == d84Var.I0 && this.J0 == d84Var.J0 && this.K0 == d84Var.K0 && this.L0 == d84Var.L0 && this.M0 == d84Var.M0 && this.N0 == d84Var.N0 && this.O0 == d84Var.O0 && this.P0 == d84Var.P0 && this.Q0 == d84Var.Q0 && this.R0 == d84Var.R0 && Float.compare(this.S0, d84Var.S0) == 0 && this.T0 == d84Var.T0 && this.U0 == d84Var.U0 && this.V0 == d84Var.V0 && this.W0 == d84Var.W0 && this.X0 == d84Var.X0 && Float.compare(this.Y0, d84Var.Y0) == 0 && Float.compare(this.Z0, d84Var.Z0) == 0 && Float.compare(this.a1, d84Var.a1) == 0 && this.b1 == d84Var.b1 && ye4.p(this.c1, d84Var.c1) && ye4.p(this.d1, d84Var.d1) && ye4.p(this.e1, d84Var.e1) && ye4.p(this.f1, d84Var.f1) && ye4.p(this.g1, d84Var.g1) && ye4.p(this.h1, d84Var.h1) && ye4.p(this.i1, d84Var.i1) && this.j1 == d84Var.j1 && this.k1 == d84Var.k1 && this.l1 == d84Var.l1 && this.m1 == d84Var.m1 && this.n1 == d84Var.n1 && this.o1 == d84Var.o1 && this.p1 == d84Var.p1 && this.q1 == d84Var.q1 && this.r1 == d84Var.r1 && this.s1 == d84Var.s1 && this.t1 == d84Var.t1 && this.u1 == d84Var.u1 && this.v1 == d84Var.v1 && this.w1 == d84Var.w1 && ye4.p(this.x1, d84Var.x1) && this.y1.equals(d84Var.y1) && this.z1 == d84Var.z1 && this.A1 == d84Var.A1 && this.B1 == d84Var.B1 && this.C1 == d84Var.C1 && this.D1 == d84Var.D1 && this.E1 == d84Var.E1 && this.F1 == d84Var.F1 && ye4.p(this.G1, d84Var.G1) && ye4.p(this.H1, d84Var.H1) && this.I1 == d84Var.I1 && ye4.p(this.J1, d84Var.J1) && ye4.p(this.K1, d84Var.K1) && ye4.p(this.L1, d84Var.L1) && this.M1 == d84Var.M1 && this.N1 == d84Var.N1 && this.O1 == d84Var.O1 && this.P1 == d84Var.P1 && ye4.p(this.Q1, d84Var.Q1) && ye4.p(this.R1, d84Var.R1) && ye4.p(this.S1, d84Var.S1) && ye4.p(this.T1, d84Var.T1) && ye4.p(this.U1, d84Var.U1) && this.V1 == d84Var.V1 && this.W1 == d84Var.W1 && this.X1 == d84Var.X1 && ye4.p(this.Y1, d84Var.Y1) && this.Z1 == d84Var.Z1 && ye4.p(this.a2, d84Var.a2) && ye4.p(this.b2, d84Var.b2) && ye4.p(this.c2, d84Var.c2) && this.d2 == d84Var.d2 && this.e2 == d84Var.e2 && ye4.p(this.f2, d84Var.f2) && ye4.p(this.g2, d84Var.g2) && ye4.p(this.h2, d84Var.h2) && ye4.p(this.i2, d84Var.i2) && this.j2.equals(d84Var.j2) && this.k2 == d84Var.k2 && this.l2 == d84Var.l2 && this.m2 == d84Var.m2 && this.n2 == d84Var.n2 && ye4.p(this.o2, d84Var.o2) && ye4.p(this.p2, d84Var.p2) && this.q2 == d84Var.q2 && ye4.p(this.r2, d84Var.r2) && this.s2 == d84Var.s2 && this.t2 == d84Var.t2 && ye4.p(this.u2, d84Var.u2) && ye4.p(this.v2, d84Var.v2) && this.w2 == d84Var.w2 && ye4.p(this.x2, d84Var.x2) && ye4.p(this.y2, d84Var.y2) && ye4.p(this.z2, d84Var.z2) && ye4.p(this.A2, d84Var.A2);
    }

    public final int hashCode() {
        int iD = a68.d((this.S.hashCode() + ((this.R.hashCode() + ((this.Q.hashCode() + ((this.P.hashCode() + a68.c(a68.e(this.N, a68.d(a68.c(rx1.c(this.K, a68.d(rx1.c(this.I, a68.e(this.H, a68.e(this.G, a68.d(a68.d(rx1.c(this.D, (this.C.hashCode() + a68.d(a68.d(a68.d((this.y.hashCode() + ((this.x.hashCode() + ((this.w.hashCode() + ((this.v.hashCode() + a68.d((this.t.hashCode() + a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d((this.h.hashCode() + ((this.g.hashCode() + a68.d(a68.d((this.d.hashCode() + ((this.c.hashCode() + a68.d(this.a.hashCode() * 31, 31, this.b)) * 31)) * 31, 31, this.e), 31, this.f)) * 31)) * 31, 31, this.i), 31, this.j), 31, this.k), 31, this.l), 31, this.m), 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31, this.s)) * 31, 31, this.u)) * 31)) * 31)) * 31)) * 31, 31, this.z), 31, this.A), 31, this.B)) * 31, 31), 31, this.E), 31, this.F), 31), 31), 31), 31, this.J), 31), 31, this.L), 31, this.M), 31), 31, this.O)) * 31)) * 31)) * 31)) * 31, 31, this.T);
        String str = this.U;
        int iA = f33.a(this.w1, a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.c(a68.c((this.g1.hashCode() + ((this.f1.hashCode() + ((this.e1.hashCode() + ((this.d1.hashCode() + ((this.c1.hashCode() + ((this.b1.hashCode() + rx1.c(this.a1, rx1.c(this.Z0, rx1.c(this.Y0, a68.d(a68.d(a68.d(a68.d(a68.d(rx1.c(this.S0, a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(f33.a(this.H0, f33.a(this.G0, a68.d(f33.a(this.E0, rx1.c(this.D0, f33.a(this.C0, (this.B0.hashCode() + ((this.A0.hashCode() + ((this.z0.hashCode() + ((this.y0.hashCode() + a68.d(a68.d((this.v0.hashCode() + ((this.u0.hashCode() + a68.d((this.s0.hashCode() + a68.d(f33.a(this.q0, a68.d(a68.d((this.n0.hashCode() + a68.d(f33.a(this.l0, f33.a(this.k0, a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d((this.Z.hashCode() + a68.d(a68.d(a68.e(this.W, a68.e(this.V, (iD + (str == null ? 0 : str.hashCode())) * 31, 31), 31), 31, this.X), 31, this.Y)) * 31, 31, this.a0), 31, this.b0), 31, true), 31, this.c0), 31, this.d0), 31, this.e0), 31, this.f0), 31, this.g0), 31, this.h0), 31, this.i0), 31, this.j0), 31), 31), 31, this.m0)) * 31, 31, this.o0), 31, this.p0), 31), 31, this.r0)) * 31, 31, this.t0)) * 31)) * 31, 31, this.w0), 31, this.x0)) * 31)) * 31)) * 31)) * 31, 31), 31), 31), 31, this.F0), 31), 31), 31, this.I0), 31, this.J0), 31, this.K0), 31, this.L0), 31, this.M0), 31, this.N0), 31, this.O0), 31, this.P0), 31, this.Q0), 31, this.R0), 31), 31, this.T0), 31, this.U0), 31, this.V0), 31, this.W0), 31, this.X0), 31), 31), 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31, this.h1), 31, this.i1), 31, this.j1), 31, this.k1), 31, this.l1), 31, this.m1), 31, this.n1), 31, this.o1), 31, this.p1), 31, this.q1), 31, this.r1), 31, this.s1), 31, this.t1), 31, this.u1), 31, this.v1), 31);
        ev4 ev4Var = this.x1;
        int iD2 = a68.d((this.H1.hashCode() + ((this.G1.hashCode() + a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(f33.a(this.z1, a68.e(this.y1, (iA + (ev4Var == null ? 0 : ev4Var.hashCode())) * 31, 31), 31), 31, this.A1), 31, this.B1), 31, this.C1), 31, this.D1), 31, this.E1), 31, this.F1)) * 31)) * 31, 31, this.I1);
        l15 l15Var = this.J1;
        int iHashCode = (iD2 + (l15Var == null ? 0 : l15Var.hashCode())) * 31;
        String str2 = this.K1;
        int iHashCode2 = (iHashCode + (str2 == null ? 0 : str2.hashCode())) * 31;
        String str3 = this.L1;
        int iD3 = a68.d(a68.d(a68.d(a68.d((iHashCode2 + (str3 == null ? 0 : str3.hashCode())) * 31, 31, this.M1), 31, this.N1), 31, this.O1), 31, this.P1);
        String str4 = this.Q1;
        int iHashCode3 = (iD3 + (str4 == null ? 0 : str4.hashCode())) * 31;
        Long l = this.R1;
        int iHashCode4 = (iHashCode3 + (l == null ? 0 : l.hashCode())) * 31;
        Integer num = this.S1;
        int iHashCode5 = (iHashCode4 + (num == null ? 0 : num.hashCode())) * 31;
        Integer num2 = this.T1;
        int iHashCode6 = (iHashCode5 + (num2 == null ? 0 : num2.hashCode())) * 31;
        String str5 = this.U1;
        int iA2 = f33.a(this.X1, f33.a(this.W1, a68.d((iHashCode6 + (str5 == null ? 0 : str5.hashCode())) * 31, 31, this.V1), 31), 31);
        Long l2 = this.Y1;
        int iD4 = a68.d((iA2 + (l2 == null ? 0 : l2.hashCode())) * 31, 31, this.Z1);
        String str6 = this.a2;
        int iHashCode7 = (iD4 + (str6 == null ? 0 : str6.hashCode())) * 31;
        String str7 = this.b2;
        int iHashCode8 = (iHashCode7 + (str7 == null ? 0 : str7.hashCode())) * 31;
        Long l3 = this.c2;
        int iD5 = a68.d(a68.d((iHashCode8 + (l3 == null ? 0 : l3.hashCode())) * 31, 31, this.d2), 31, this.e2);
        String str8 = this.f2;
        int iHashCode9 = (iD5 + (str8 == null ? 0 : str8.hashCode())) * 31;
        Long l4 = this.g2;
        int iHashCode10 = (iHashCode9 + (l4 == null ? 0 : l4.hashCode())) * 31;
        Integer num3 = this.h2;
        int iHashCode11 = (iHashCode10 + (num3 == null ? 0 : num3.hashCode())) * 31;
        Integer num4 = this.i2;
        int iD6 = a68.d(a68.d(a68.d(f33.a(this.k2, j55.e(this.j2, (iHashCode11 + (num4 == null ? 0 : num4.hashCode())) * 31, 31), 31), 31, this.l2), 31, this.m2), 31, this.n2);
        nr8 nr8Var = this.o2;
        int iHashCode12 = (iD6 + (nr8Var == null ? 0 : nr8Var.hashCode())) * 31;
        dy1 dy1Var = this.p2;
        int iD7 = a68.d((iHashCode12 + (dy1Var == null ? 0 : dy1Var.hashCode())) * 31, 31, this.q2);
        String str9 = this.r2;
        int iD8 = a68.d((this.s2.hashCode() + ((iD7 + (str9 == null ? 0 : str9.hashCode())) * 31)) * 31, 31, this.t2);
        String str10 = this.u2;
        int iHashCode13 = (iD8 + (str10 == null ? 0 : str10.hashCode())) * 31;
        String str11 = this.v2;
        return this.A2.hashCode() + ((this.z2.hashCode() + ((this.y2.hashCode() + ((this.x2.hashCode() + a68.d((iHashCode13 + (str11 != null ? str11.hashCode() : 0)) * 31, 31, this.w2)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("IisuSettingsSnapshot(appLanguage=");
        sb.append(this.a);
        sb.append(", forceIiSuOnLaunch=");
        sb.append(this.b);
        sb.append(", defaultLaunchPage=");
        sb.append(this.c);
        sb.append(", backups=");
        sb.append(this.d);
        sb.append(", blackOutUnusedDisplayOnLaunch=");
        a68.u(", profileNudgeEnabled=", ", dualDisplayHomeLocation=", sb, this.e, this.f);
        sb.append(this.g);
        sb.append(", dualDisplayInactiveSurface=");
        sb.append(this.h);
        sb.append(", hasDualDisplay=");
        a68.u(", alwaysShowRomsTitleSection=", ", neverShowRomsTitleSection=", sb, this.i, this.j);
        a68.u(", showConsolesTitleSection=", ", showAppsTitleSection=", sb, this.k, this.l);
        a68.u(", horizontalGridOnSingleScreen=", ", horizontalGridOnDualScreen=", sb, this.m, this.n);
        a68.u(", horizontalGridOverrideOnHome=", ", horizontalGridOverrideOnPlatforms=", sb, this.o, this.p);
        a68.u(", horizontalGridOverrideOnGames=", ", horizontalGridOverrideOnApps=", sb, this.q, this.r);
        sb.append(this.s);
        sb.append(", touchContextMenuGestureMode=");
        sb.append(this.t);
        sb.append(", browser2TapToSelect=");
        sb.append(this.u);
        sb.append(", launcherRightStickMode=");
        sb.append(this.v);
        sb.append(", retroAchievementsShortcutButton=");
        sb.append(this.w);
        sb.append(", screenSwapShortcutButton=");
        sb.append(this.x);
        sb.append(", appDrawerShortcutButton=");
        sb.append(this.y);
        sb.append(", swapAbXy=");
        sb.append(this.z);
        sb.append(", swapAbXyGlyphs=");
        a68.u(", uiSoundsEnabled=", ", hapticFeedbackLevel=", sb, this.A, this.B);
        sb.append(this.C);
        sb.append(", globalMusicVolume=");
        sb.append(this.D);
        sb.append(", useTimeBasedMusic=");
        a68.u(", shuffleTimeBasedMusic=", ", timeBasedMusicEntries=", sb, this.E, this.F);
        pk0.z(", importedMusicTracks=", ", soundbiteVolume=", sb, this.G, this.H);
        sb.append(this.I);
        sb.append(", homeSoundbitesEnabled=");
        sb.append(this.J);
        sb.append(", uiEffectsVolume=");
        sb.append(this.K);
        sb.append(", globalThemeMusicLabel=");
        sb.append(this.L);
        sb.append(", hasCustomGlobalThemeMusic=");
        sb.append(this.M);
        sb.append(", homeMusicPresetOptions=");
        sb.append(this.N);
        sb.append(", selectedHomeMusicPresetId=");
        sb.append(this.O);
        sb.append(", themeMode=");
        sb.append(this.P);
        sb.append(", launcherFontChoice=");
        sb.append(this.Q);
        sb.append(", launcherStandardTextWeightChoice=");
        sb.append(this.R);
        sb.append(", launcherBoldTextWeightChoice=");
        sb.append(this.S);
        sb.append(", multiWeightFontCompactSpacingEnabled=");
        sb.append(this.T);
        sb.append(", customThemeName=");
        qv7.w(sb, this.U, ", availableThemes=", this.V, ", availablePlatformPacks=");
        sb.append(this.W);
        sb.append(", disableThemeVideos=");
        sb.append(this.X);
        sb.append(", preferCompatibleBundledThemeVideos=");
        sb.append(this.Y);
        sb.append(", themeVideoFrameRateCap=");
        sb.append(this.Z);
        sb.append(", bundledThemeVideoFallbackForced=");
        a68.u(", disableDarkModePlatformIcons=", ", playMediaOnGamesPage=true, disableAllHeroes=", sb, this.a0, this.b0);
        a68.u(", disableHeroesOnHome=", ", disableHeroesOnGamesGrid=", sb, this.c0, this.d0);
        a68.u(", disableHeroesOnSecondaryDisplay=", ", disableHeroesOnBottomScreenInSingleScreenMode=", sb, this.e0, this.f0);
        a68.u(", animateHeroes=", ", pauseAnimationsWhenIdle=", sb, this.g0, this.h0);
        a68.u(", categoryTitleWobbleEnabled=", ", warmHeroCount=", sb, this.i0, this.j0);
        pk0.r(this.k0, this.l0, ", committedTargetPostIdleSettleDelayMs=", ", pageSwipeAnimationsEnabled=", sb);
        sb.append(this.m0);
        sb.append(", browserPageTransitionMode=");
        sb.append(this.n0);
        sb.append(", focusRingAnimationsEnabled=");
        a68.u(", gridDominoAnimationsEnabled=", ", rendererColumnReduction=", sb, this.o0, this.p0);
        rx1.u(this.q0, ", performanceMetricsOverlayEnabled=", ", homeGlassCardStyle=", sb, this.r0);
        sb.append(this.s0);
        sb.append(", removeLargePanelContainers=");
        sb.append(this.t0);
        sb.append(", singleScreenHomeDashboardMode=");
        sb.append(this.u0);
        sb.append(", singleScreenHomeGlassMode=");
        sb.append(this.v0);
        sb.append(", contextMenuGlassEnabled=");
        a68.u(", glassOutlineEnabled=", ", homeGridIconBorderStyle=", sb, this.w0, this.x0);
        sb.append(this.y0);
        sb.append(", categoryGridIconBorderStyle=");
        sb.append(this.z0);
        sb.append(", romBrowserIconBorderStyle=");
        sb.append(this.A0);
        sb.append(", appGridIconBorderStyle=");
        sb.append(this.B0);
        sb.append(", homeGlassBlurRadiusDp=");
        sb.append(this.C0);
        sb.append(", homeGlassOpacity=");
        sb.append(this.D0);
        sb.append(", homeGlassTintColorArgb=");
        rx1.u(this.E0, ", customSelectionGradientEnabled=", ", focusIndicatorPrimaryColorArgb=", sb, this.F0);
        pk0.r(this.G0, this.H0, ", focusIndicatorSecondaryColorArgb=", ", tooltipUseTitleImage=", sb);
        a68.u(", tooltipUseForOneRow=", ", tooltipUseForGrids=", sb, this.I0, this.J0);
        a68.u(", tooltipUseForRomsApps=", ", tooltipUseForQuickAccess=", sb, this.K0, this.L0);
        a68.u(", titleImageForHorizontalCarousel=", ", titleImageForXmb=", sb, this.M0, this.N0);
        a68.u(", consoleTitleImageForXmb=", ", xmbHorizontalPath=", sb, this.O0, this.P0);
        a68.u(", xmbDropShadowEnabled=", ", xmbHeroMask=", sb, this.Q0, this.R0);
        sb.append(this.S0);
        sb.append(", forceSingleScreenViewOnInternalScreen=");
        sb.append(this.T0);
        sb.append(", forceOldLayout=");
        a68.u(", showFocusedTitleOnHome=", ", showFocusedTitleInSingleScreenHud=", sb, this.U0, this.V0);
        a68.u(", titleImageForFocusedInSingleScreenHud=", ", backgroundSkrimOpacity=", sb, this.W0, this.X0);
        j55.A(sb, this.Y0, ", dualScreenBackgroundSkrimMask=", this.Z0, ", dualScreenBackgroundSkrimFeather=");
        sb.append(this.a1);
        sb.append(", assetStorageLocation=");
        sb.append(this.b1);
        sb.append(", screenScraperCredentials=");
        sb.append(this.c1);
        sb.append(", theGamesDbCredentials=");
        sb.append(this.d1);
        sb.append(", steamGridDbCredentials=");
        sb.append(this.e1);
        sb.append(", discordIntegration=");
        sb.append(this.f1);
        sb.append(", discordUiState=");
        sb.append(this.g1);
        sb.append(", scraperPreferredRegion=");
        sb.append(this.h1);
        sb.append(", scraperPreferredLanguage=");
        f33.x(sb, this.i1, ", aggressiveScrapingEnabled=", this.j1, ", preferRetroAchievementsIcon=");
        a68.u(", useNativeRetroAchievementsMenuIcons=", ", showSoftcoreRetroAchievements=", sb, this.k1, this.l1);
        a68.u(", retroAchievementsHeroesEnabled=", ", showDualDetailSystemStatus=", sb, this.m1, this.n1);
        a68.u(", showDualDetailConnectedFriends=", ", showDualDetailAchievementsSummary=", sb, this.o1, this.p1);
        a68.u(", showDualDetailButtonHint=", ", showDualDetailGameplaySlides=", sb, this.q1, this.r1);
        a68.u(", dualDetailMakeTitleBigger=", ", dualDetailShowHomeBackgroundOnIdle=", sb, this.s1, this.t1);
        a68.u(", showHiddenFiles=", ", romScanDepth=", sb, this.u1, this.v1);
        sb.append(this.w1);
        sb.append(", libraryScanProgress=");
        sb.append(this.x1);
        sb.append(", gameLibraryRoots=");
        sb.append(this.y1);
        sb.append(", notificationHistoryLimit=");
        sb.append(this.z1);
        sb.append(", notificationPopupPreviewsEnabled=");
        a68.u(", notificationIisuPopupPreviewsEnabled=", ", notificationSystemPopupPreviewsEnabled=", sb, this.A1, this.B1);
        a68.u(", notificationPopupSoundEnabled=", ", romImportWarningNotificationsEnabled=", sb, this.C1, this.D1);
        a68.u(", starterPackUpdateNotificationsEnabled=", ", managedMediaCacheState=", sb, this.E1, this.F1);
        sb.append(this.G1);
        sb.append(", managedAllMediaState=");
        sb.append(this.H1);
        sb.append(", useManagedImageCache=");
        sb.append(this.I1);
        sb.append(", lowPowerModeRestoreSnapshot=");
        sb.append(this.J1);
        sb.append(", esDeRootTreeUri=");
        a68.v(sb, this.K1, ", esDeRootPath=", this.L1, ", esDeUsePhysicalMediaAsIcon=");
        a68.u(", esDePrecacheRomIconThumbnailsOnSync=", ", esDeLinkedAndAccessible=", sb, this.M1, this.N1);
        a68.u(", esDeSyncInProgress=", ", esDeLastSyncMessage=", sb, this.O1, this.P1);
        sb.append(this.Q1);
        sb.append(", esDeLastSyncAt=");
        sb.append(this.R1);
        sb.append(", esDeSyncProgressCurrent=");
        sb.append(this.S1);
        sb.append(", esDeSyncProgressTotal=");
        sb.append(this.T1);
        sb.append(", esDeSyncCurrentTabLabel=");
        f33.x(sb, this.U1, ", esDePrecacheInProgress=", this.V1, ", esDePrecacheCompletedCount=");
        pk0.r(this.W1, this.X1, ", esDePrecacheQueuedCount=", ", esDePrecacheLastCompletedAt=", sb);
        sb.append(this.Y1);
        sb.append(", rommEnabled=");
        sb.append(this.Z1);
        sb.append(", rommBaseUrl=");
        a68.v(sb, this.a2, ", rommUsername=", this.b2, ", rommLinkedAt=");
        sb.append(this.c2);
        sb.append(", rommLinked=");
        sb.append(this.d2);
        sb.append(", rommSyncInProgress=");
        f33.y(sb, this.e2, ", rommLastSyncMessage=", this.f2, ", rommLastSyncAt=");
        sb.append(this.g2);
        sb.append(", rommSyncProgressCurrent=");
        sb.append(this.h2);
        sb.append(", rommSyncProgressTotal=");
        sb.append(this.i2);
        sb.append(", rommCollectionOptions=");
        sb.append(this.j2);
        sb.append(", rommEnabledCollectionCount=");
        rx1.u(this.k2, ", rommMergeConsolesWithLocal=", ", updateHasCheckedForUpdates=", sb, this.l2);
        a68.u(", updateIsChecking=", ", updateAvailable=", sb, this.m2, this.n2);
        sb.append(this.o2);
        sb.append(", updateDownloadProgress=");
        sb.append(this.p2);
        sb.append(", updateIsDownloading=");
        f33.y(sb, this.q2, ", updateError=", this.r2, ", updateChannel=");
        sb.append(this.s2);
        sb.append(", supporterUpdatesEnabled=");
        sb.append(this.t2);
        sb.append(", supporterUpdatesDisplayName=");
        a68.v(sb, this.u2, ", supporterUpdatesGrantedAt=", this.v2, ", supporterAuthInProgress=");
        sb.append(this.w2);
        sb.append(", emuladoresJsonUpdateState=");
        sb.append(this.x2);
        sb.append(", supportedEmulatorsJsonUpdateState=");
        sb.append(this.y2);
        sb.append(", emulatorOptionsJsonUpdateState=");
        sb.append(this.z2);
        sb.append(", starterPackUpdateState=");
        sb.append(this.A2);
        sb.append(")");
        return sb.toString();
    }
}
