package defpackage;

import android.content.Context;
import java.util.List;
import java.util.Map;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class e63 {
    public final e73 A;
    public final l23 B;
    public final bw3 C;
    public final v33 D;
    public final ur2 E;
    public final ur2 F;
    public final ur2 G;
    public final ur2 H;
    public final ur2 I;
    public final ur2 J;
    public final ur2 K;
    public final ur2 L;
    public final ur2 M;
    public final ur2 N;
    public final wr2 O;
    public final ks2 P;
    public final ks2 Q;
    public final ls2 R;
    public final ls2 S;
    public final ks2 T;
    public final ks2 U;
    public final ks2 V;
    public final ks2 W;
    public final ks2 X;
    public final ks2 Y;
    public final ks2 Z;
    public final Context a;
    public final ks2 a0;
    public final Context b;
    public final wr2 b0;
    public final lp3 c;
    public final wr2 c0;
    public final ze0 d;
    public final wr2 d0;
    public final ze0 e;
    public final ls2 e0;
    public final bt2 f;
    public final ls2 f0;
    public final ft3 g;
    public final ks2 g0;
    public final dj3 h;
    public final ks2 h0;
    public final bj3 i;
    public final wr2 i0;
    public final kw3 j;
    public final wr2 j0;
    public final um3 k;
    public final wr2 k0;
    public final ww6 l;
    public final wr2 l0;
    public final Map m;
    public final wr2 m0;
    public final Map n;
    public final ks2 n0;
    public final List o;
    public final ks2 o0;
    public final lc7 p;
    public final ur2 p0;
    public final Map q;
    public final ur2 q0;
    public final boolean r;
    public final ur2 r0;
    public final boolean s;
    public final wr2 s0;
    public final boolean t;
    public final ur2 t0;
    public final boolean u;
    public final wr2 u0;
    public final long v;
    public final ur2 v0;
    public final String w;
    public final ur2 w0;
    public final List x;
    public final ur2 x0;
    public final lg3 y;
    public final ur2 y0;
    public final u83 z;

    public e63(Context context, Context context2, lp3 lp3Var, ze0 ze0Var, ze0 ze0Var2, bt2 bt2Var, ft3 ft3Var, dj3 dj3Var, bj3 bj3Var, kw3 kw3Var, um3 um3Var, ww6 ww6Var, Map map, Map map2, List list, lc7 lc7Var, Map map3, boolean z, boolean z2, boolean z3, boolean z4, long j, String str, List list2, lg3 lg3Var, u83 u83Var, e73 e73Var, l23 l23Var, bw3 bw3Var, v33 v33Var, ur2 ur2Var, ur2 ur2Var2, ur2 ur2Var3, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, ur2 ur2Var7, ur2 ur2Var8, ur2 ur2Var9, ur2 ur2Var10, wr2 wr2Var, ks2 ks2Var, ks2 ks2Var2, ls2 ls2Var, ls2 ls2Var2, ks2 ks2Var3, ks2 ks2Var4, ks2 ks2Var5, ks2 ks2Var6, ks2 ks2Var7, ks2 ks2Var8, ks2 ks2Var9, ks2 ks2Var10, wr2 wr2Var2, wr2 wr2Var3, wr2 wr2Var4, ls2 ls2Var3, ls2 ls2Var4, ks2 ks2Var11, ks2 ks2Var12, wr2 wr2Var5, wr2 wr2Var6, wr2 wr2Var7, wr2 wr2Var8, wr2 wr2Var9, ks2 ks2Var13, ks2 ks2Var14, ur2 ur2Var11, ur2 ur2Var12, ur2 ur2Var13, wr2 wr2Var10, ur2 ur2Var14, wr2 wr2Var11, ur2 ur2Var15, ur2 ur2Var16, ur2 ur2Var17, ur2 ur2Var18) {
        ze0Var.getClass();
        ze0Var2.getClass();
        bt2Var.getClass();
        kw3Var.getClass();
        um3Var.getClass();
        ww6Var.getClass();
        map.getClass();
        map2.getClass();
        list.getClass();
        lc7Var.getClass();
        map3.getClass();
        list2.getClass();
        l23Var.getClass();
        bw3Var.getClass();
        v33Var.getClass();
        f33.q(ur2Var, ur2Var2, ur2Var3, ur2Var4, ur2Var5);
        f33.q(ur2Var6, ur2Var7, ur2Var8, ur2Var9, ur2Var10);
        wr2Var.getClass();
        ks2Var.getClass();
        ks2Var2.getClass();
        ls2Var.getClass();
        ls2Var2.getClass();
        ks2Var3.getClass();
        ks2Var4.getClass();
        ks2Var5.getClass();
        ks2Var6.getClass();
        ks2Var7.getClass();
        ks2Var8.getClass();
        ks2Var9.getClass();
        ks2Var10.getClass();
        wr2Var2.getClass();
        wr2Var3.getClass();
        wr2Var4.getClass();
        ls2Var3.getClass();
        ls2Var4.getClass();
        ks2Var11.getClass();
        ks2Var12.getClass();
        f33.r(wr2Var5, wr2Var6, wr2Var7, wr2Var8, wr2Var9);
        ks2Var13.getClass();
        ks2Var14.getClass();
        ur2Var11.getClass();
        ur2Var12.getClass();
        ur2Var13.getClass();
        wr2Var10.getClass();
        ur2Var14.getClass();
        wr2Var11.getClass();
        ur2Var15.getClass();
        ur2Var16.getClass();
        ur2Var17.getClass();
        ur2Var18.getClass();
        this.a = context;
        this.b = context2;
        this.c = lp3Var;
        this.d = ze0Var;
        this.e = ze0Var2;
        this.f = bt2Var;
        this.g = ft3Var;
        this.h = dj3Var;
        this.i = bj3Var;
        this.j = kw3Var;
        this.k = um3Var;
        this.l = ww6Var;
        this.m = map;
        this.n = map2;
        this.o = list;
        this.p = lc7Var;
        this.q = map3;
        this.r = z;
        this.s = z2;
        this.t = z3;
        this.u = z4;
        this.v = j;
        this.w = str;
        this.x = list2;
        this.y = lg3Var;
        this.z = u83Var;
        this.A = e73Var;
        this.B = l23Var;
        this.C = bw3Var;
        this.D = v33Var;
        this.E = ur2Var;
        this.F = ur2Var2;
        this.G = ur2Var3;
        this.H = ur2Var4;
        this.I = ur2Var5;
        this.J = ur2Var6;
        this.K = ur2Var7;
        this.L = ur2Var8;
        this.M = ur2Var9;
        this.N = ur2Var10;
        this.O = wr2Var;
        this.P = ks2Var;
        this.Q = ks2Var2;
        this.R = ls2Var;
        this.S = ls2Var2;
        this.T = ks2Var3;
        this.U = ks2Var4;
        this.V = ks2Var5;
        this.W = ks2Var6;
        this.X = ks2Var7;
        this.Y = ks2Var8;
        this.Z = ks2Var9;
        this.a0 = ks2Var10;
        this.b0 = wr2Var2;
        this.c0 = wr2Var3;
        this.d0 = wr2Var4;
        this.e0 = ls2Var3;
        this.f0 = ls2Var4;
        this.g0 = ks2Var11;
        this.h0 = ks2Var12;
        this.i0 = wr2Var5;
        this.j0 = wr2Var6;
        this.k0 = wr2Var7;
        this.l0 = wr2Var8;
        this.m0 = wr2Var9;
        this.n0 = ks2Var13;
        this.o0 = ks2Var14;
        this.p0 = ur2Var11;
        this.q0 = ur2Var12;
        this.r0 = ur2Var13;
        this.s0 = wr2Var10;
        this.t0 = ur2Var14;
        this.u0 = wr2Var11;
        this.v0 = ur2Var15;
        this.w0 = ur2Var16;
        this.x0 = ur2Var17;
        this.y0 = ur2Var18;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof e63) {
            e63 e63Var = (e63) obj;
            if (this.a.equals(e63Var.a) && this.b.equals(e63Var.b) && this.c == e63Var.c && ye4.p(this.d, e63Var.d) && ye4.p(this.e, e63Var.e) && ye4.p(this.f, e63Var.f) && this.g == e63Var.g && this.h == e63Var.h && this.i.equals(e63Var.i) && ye4.p(this.j, e63Var.j) && ye4.p(this.k, e63Var.k) && ye4.p(this.l, e63Var.l) && ye4.p(this.m, e63Var.m) && ye4.p(this.n, e63Var.n) && ye4.p(this.o, e63Var.o) && ye4.p(this.p, e63Var.p) && ye4.p(this.q, e63Var.q) && this.r == e63Var.r && this.s == e63Var.s && this.t == e63Var.t && this.u == e63Var.u && this.v == e63Var.v && ye4.p(this.w, e63Var.w) && ye4.p(this.x, e63Var.x) && this.y == e63Var.y && this.z == e63Var.z && this.A.equals(e63Var.A) && ye4.p(this.B, e63Var.B) && ye4.p(this.C, e63Var.C) && ye4.p(this.D, e63Var.D) && ye4.p(this.E, e63Var.E) && ye4.p(this.F, e63Var.F) && ye4.p(this.G, e63Var.G) && ye4.p(this.H, e63Var.H) && ye4.p(this.I, e63Var.I) && ye4.p(this.J, e63Var.J) && ye4.p(this.K, e63Var.K) && ye4.p(this.L, e63Var.L) && ye4.p(this.M, e63Var.M) && ye4.p(this.N, e63Var.N) && ye4.p(this.O, e63Var.O) && ye4.p(this.P, e63Var.P) && ye4.p(this.Q, e63Var.Q) && ye4.p(this.R, e63Var.R) && ye4.p(this.S, e63Var.S) && ye4.p(this.T, e63Var.T) && ye4.p(this.U, e63Var.U) && ye4.p(this.V, e63Var.V) && ye4.p(this.W, e63Var.W) && ye4.p(this.X, e63Var.X) && ye4.p(this.Y, e63Var.Y) && ye4.p(this.Z, e63Var.Z) && ye4.p(this.a0, e63Var.a0) && ye4.p(this.b0, e63Var.b0) && ye4.p(this.c0, e63Var.c0) && ye4.p(this.d0, e63Var.d0) && ye4.p(this.e0, e63Var.e0) && ye4.p(this.f0, e63Var.f0) && ye4.p(this.g0, e63Var.g0) && ye4.p(this.h0, e63Var.h0) && ye4.p(this.i0, e63Var.i0) && ye4.p(this.j0, e63Var.j0) && ye4.p(this.k0, e63Var.k0) && ye4.p(this.l0, e63Var.l0) && ye4.p(this.m0, e63Var.m0) && ye4.p(this.n0, e63Var.n0) && ye4.p(this.o0, e63Var.o0) && ye4.p(this.p0, e63Var.p0) && ye4.p(this.q0, e63Var.q0) && ye4.p(this.r0, e63Var.r0) && ye4.p(this.s0, e63Var.s0) && ye4.p(this.t0, e63Var.t0) && ye4.p(this.u0, e63Var.u0) && ye4.p(this.v0, e63Var.v0) && ye4.p(this.w0, e63Var.w0) && ye4.p(this.x0, e63Var.x0) && ye4.p(this.y0, e63Var.y0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int iD = j55.d(this.v, a68.d(a68.d(a68.d(a68.d(a68.f(this.q, rx1.j(this.p, a68.e(this.o, a68.f(this.n, a68.f(this.m, f33.c(this.l, (this.k.hashCode() + ((this.j.hashCode() + ((this.i.hashCode() + f33.b(this.h, rx1.i(this.g, (this.f.hashCode() + rx1.e(this.e, rx1.e(this.d, rx1.h(this.c, (this.b.hashCode() + (this.a.hashCode() * 31)) * 31, 31), 31), 31)) * 31, 31), 31)) * 31)) * 31)) * 31, 31), 31), 31), 31), 31), 31), 31, this.r), 31, this.s), 31, this.t), 31, this.u), 31);
        String str = this.w;
        return this.y0.hashCode() + rx1.f(this.x0, rx1.f(this.w0, rx1.f(this.v0, pk0.b(rx1.f(this.t0, pk0.b(rx1.f(this.r0, rx1.f(this.q0, rx1.f(this.p0, rx1.d(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(rx1.g(this.f0, rx1.g(this.e0, pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.g(this.S, rx1.g(this.R, rx1.d(rx1.d(pk0.b(rx1.f(this.N, rx1.f(this.M, rx1.f(this.L, rx1.f(this.K, rx1.f(this.J, rx1.f(this.I, rx1.f(this.H, rx1.f(this.G, rx1.f(this.F, rx1.f(this.E, (this.D.hashCode() + ((this.C.hashCode() + ((this.B.hashCode() + ((this.A.hashCode() + ((this.z.hashCode() + ((this.y.hashCode() + a68.e(this.x, (iD + (str == null ? 0 : str.hashCode())) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), 31), 31), 31), 31), 31), 31), 31), 31), 31), this.O, 31), 31, this.P), 31, this.Q), 31), 31), 31, this.T), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), this.b0, 31), this.c0, 31), this.d0, 31), 31), 31), 31, this.g0), 31, this.h0), this.i0, 31), this.j0, 31), this.k0, 31), this.l0, 31), this.m0, 31), 31, this.n0), 31, this.o0), 31), 31), 31), this.s0, 31), 31), this.u0, 31), 31), 31), 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomeDialogContextOwnerAssemblyDeps(context=");
        sb.append(this.a);
        sb.append(", stableContext=");
        sb.append(this.b);
        sb.append(", runtimeState=");
        sb.append(this.c);
        sb.append(", browserState=");
        sb.append(this.d);
        sb.append(", rawBrowserState=");
        sb.append(this.e);
        sb.append(", selectionState=");
        sb.append(this.f);
        sb.append(", callbacks=");
        sb.append(this.g);
        sb.append(", quickAccessWidgetState=");
        sb.append(this.h);
        sb.append(", quickAccessWidgetRuntimeOwner=");
        sb.append(this.i);
        sb.append(", taskScraperOperations=");
        sb.append(this.j);
        sb.append(", scraperTaskCoordinator=");
        sb.append(this.k);
        sb.append(", retroAchievementsState=");
        sb.append(this.l);
        sb.append(", retroHashesByRomId=");
        qv7.x(sb, this.m, ", retroAchievementGameIdsForRoms=", this.n, ", allConsolesRoms=");
        sb.append(this.o);
        sb.append(", scraperState=");
        sb.append(this.p);
        sb.append(", tabLabelById=");
        sb.append(this.q);
        sb.append(", allowEditing=");
        sb.append(this.r);
        sb.append(", isCollectionPopupOpen=");
        a68.u(", isExternalDisplay=", ", hasSteamGridDbApiKey=", sb, this.s, this.t);
        sb.append(this.u);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.v);
        sb.append(", emptyLabel=");
        sb.append(this.w);
        sb.append(", appTabs=");
        sb.append(this.x);
        sb.append(", platformAppBrowserCallbacks=");
        sb.append(this.y);
        sb.append(", dialogSystemCallbacks=");
        sb.append(this.z);
        sb.append(", dialogLayerSetup=");
        sb.append(this.A);
        sb.append(", addEditConsoleDialogOwner=");
        sb.append(this.B);
        sb.append(", activeTaskMenuBindings=");
        sb.append(this.C);
        sb.append(", backgroundTaskActions=");
        sb.append(this.D);
        rx1.x(this.E, this.F, ", clearSelectionAction=", ", clearTopLevelMenuIfVisible=", sb);
        rx1.x(this.G, this.H, ", persistUiSessionNow=", ", bumpQuickAccessFocusSignal=", sb);
        rx1.x(this.I, this.J, ", bumpAppsCategoryFocusSignal=", ", onDismiss=", sb);
        rx1.x(this.K, this.L, ", onIncreaseQuickAccessDensity=", ", onDecreaseQuickAccessDensity=", sb);
        rx1.x(this.M, this.N, ", onIncreaseAppCategoryGridDensity=", ", onDecreaseAppCategoryGridDensity=", sb);
        sb.append(", onSetMinimalModeEnabled=");
        sb.append(this.O);
        sb.append(", onToggleAppShortcut=");
        sb.append(this.P);
        sb.append(", onToggleRomShortcut=");
        sb.append(this.Q);
        sb.append(", onUpdateAppLinkedPreference=");
        sb.append(this.R);
        sb.append(", onUpdateRomLinkedPreference=");
        sb.append(this.S);
        sb.append(", onUpdateAppLaunchPreference=");
        sb.append(this.T);
        f33.w(sb, ", onUpdateAppClassification=", this.U, ", onSetAppCustomName=", this.V);
        f33.w(sb, ", onUpdateRomLaunchPreference=", this.W, ", onSetRomTitleSectionMode=", this.X);
        f33.w(sb, ", onSetRomTrophyIconCorner=", this.Y, ", onSetRomTrophyIconAlpha=", this.Z);
        sb.append(", onSetRomCustomName=");
        sb.append(this.a0);
        sb.append(", onCreateCollection=");
        sb.append(this.b0);
        rx1.C(sb, ", onDeleteCollection=", this.c0, ", onSetCollectionByNameRows=", this.d0);
        sb.append(", onSetCollectionColumns=");
        sb.append(this.e0);
        sb.append(", onSetRomInCollection=");
        sb.append(this.f0);
        f33.w(sb, ", onManageCollectionMedia=", this.g0, ", onDeleteCollectionMedia=", this.h0);
        rx1.C(sb, ", onManageAppQuickAccessIcon=", this.i0, ", onManageRomQuickAccessIcon=", this.j0);
        rx1.C(sb, ", onDeleteAppQuickAccessIcon=", this.k0, ", onDeleteRomQuickAccessIcon=", this.l0);
        sb.append(", requestHomeLayoutImport=");
        sb.append(this.m0);
        sb.append(", requestHomeLayoutExport=");
        sb.append(this.n0);
        sb.append(", onScrapeSelectedHomeIcon=");
        sb.append(this.o0);
        sb.append(", onScrapeAllHomeIcons=");
        sb.append(this.p0);
        rx1.x(this.q0, this.r0, ", onRefreshMetadata=", ", onRefreshHome=", sb);
        sb.append(", onRetroAchievementsRomFocused=");
        sb.append(this.s0);
        sb.append(", onRetroAchievementsShowDetails=");
        sb.append(this.t0);
        sb.append(", onCategoryLayoutModeChange=");
        sb.append(this.u0);
        sb.append(", onRefreshCategoryMetadata=");
        sb.append(this.v0);
        rx1.x(this.w0, this.x0, ", onOpenGlobalSearch=", ", onRetroAchievementsRefresh=", sb);
        sb.append(", onRetroAchievementsLogout=");
        sb.append(this.y0);
        sb.append(")");
        return sb.toString();
    }
}
