package defpackage;

import android.content.Context;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class f93 {
    public final fa0 A;
    public final ur2 A0;
    public final ia0 B;
    public final wr2 B0;
    public final boolean C;
    public final wr2 C0;
    public final boolean D;
    public final wr2 D0;
    public final g43 E;
    public final wr2 E0;
    public final ur2 F;
    public final ks2 F0;
    public final wr2 G;
    public final wr2 G0;
    public final wr2 H;
    public final wr2 H0;
    public final wr2 I;
    public final ks2 I0;
    public final wr2 J;
    public final ls2 J0;
    public final ur2 K;
    public final ks2 K0;
    public final ur2 L;
    public final ks2 L0;
    public final ks2 M;
    public final ks2 M0;
    public final ks2 N;
    public final ur2 O;
    public final ur2 P;
    public final ur2 Q;
    public final ur2 R;
    public final ks2 S;
    public final ks2 T;
    public final ks2 U;
    public final ks2 V;
    public final ks2 W;
    public final ks2 X;
    public final ks2 Y;
    public final ks2 Z;
    public final Context a;
    public final ks2 a0;
    public final lp3 b;
    public final ks2 b0;
    public final ft3 c;
    public final ks2 c0;
    public final av3 d;
    public final ks2 d0;
    public final f8 e;
    public final ks2 e0;
    public final ze0 f;
    public final ks2 f0;
    public final lc7 g;
    public final ks2 g0;
    public final aj3 h;
    public final ks2 h0;
    public final ni3 i;
    public final ls2 i0;
    public final bw3 j;
    public final ms2 j0;
    public final sa3 k;
    public final ls2 k0;
    public final fb3 l;
    public final ls2 l0;
    public final ta3 m;
    public final ks2 m0;
    public final d84 n;
    public final ur2 n0;
    public final m64 o;
    public final wr2 o0;
    public final rw3 p;
    public final ks2 p0;
    public final ww6 q;
    public final wr2 q0;
    public final rk3 r;
    public final ks2 r0;
    public final p83 s;
    public final wr2 s0;
    public final qw3 t;
    public final wr2 t0;
    public final i93 u;
    public final wr2 u0;
    public final z33 v;
    public final ur2 v0;
    public final n63 w;
    public final ur2 w0;
    public final k93 x;
    public final wr2 x0;
    public final long y;
    public final wr2 y0;
    public final boolean z;
    public final wr2 z0;

    public f93(Context context, lp3 lp3Var, ft3 ft3Var, av3 av3Var, f8 f8Var, ze0 ze0Var, lc7 lc7Var, aj3 aj3Var, ni3 ni3Var, bw3 bw3Var, sa3 sa3Var, fb3 fb3Var, ta3 ta3Var, d84 d84Var, m64 m64Var, rw3 rw3Var, ww6 ww6Var, rk3 rk3Var, p83 p83Var, qw3 qw3Var, i93 i93Var, z33 z33Var, n63 n63Var, k93 k93Var, long j, boolean z, fa0 fa0Var, ia0 ia0Var, boolean z2, boolean z3, g43 g43Var, ur2 ur2Var, wr2 wr2Var, wr2 wr2Var2, wr2 wr2Var3, wr2 wr2Var4, ur2 ur2Var2, ur2 ur2Var3, ks2 ks2Var, ks2 ks2Var2, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, ur2 ur2Var7, ks2 ks2Var3, ks2 ks2Var4, ks2 ks2Var5, ks2 ks2Var6, ks2 ks2Var7, ks2 ks2Var8, ks2 ks2Var9, ks2 ks2Var10, ks2 ks2Var11, ks2 ks2Var12, ks2 ks2Var13, ks2 ks2Var14, ks2 ks2Var15, ks2 ks2Var16, ks2 ks2Var17, ks2 ks2Var18, ls2 ls2Var, ms2 ms2Var, ls2 ls2Var2, ls2 ls2Var3, ks2 ks2Var19, ur2 ur2Var8, wr2 wr2Var5, ks2 ks2Var20, wr2 wr2Var6, ks2 ks2Var21, wr2 wr2Var7, wr2 wr2Var8, wr2 wr2Var9, ur2 ur2Var9, ur2 ur2Var10, wr2 wr2Var10, wr2 wr2Var11, wr2 wr2Var12, ur2 ur2Var11, wr2 wr2Var13, wr2 wr2Var14, wr2 wr2Var15, wr2 wr2Var16, ks2 ks2Var22, wr2 wr2Var17, wr2 wr2Var18, ks2 ks2Var23, ls2 ls2Var4, ks2 ks2Var24, ks2 ks2Var25, ks2 ks2Var26) {
        f8Var.getClass();
        ze0Var.getClass();
        lc7Var.getClass();
        aj3Var.getClass();
        sa3Var.getClass();
        d84Var.getClass();
        m64Var.getClass();
        rw3Var.getClass();
        ww6Var.getClass();
        ur2Var.getClass();
        wr2Var.getClass();
        wr2Var2.getClass();
        wr2Var3.getClass();
        wr2Var4.getClass();
        ur2Var2.getClass();
        ur2Var3.getClass();
        ks2Var.getClass();
        ks2Var2.getClass();
        ur2Var4.getClass();
        ur2Var5.getClass();
        ur2Var6.getClass();
        ur2Var7.getClass();
        ks2Var3.getClass();
        ks2Var4.getClass();
        ks2Var5.getClass();
        ks2Var6.getClass();
        ks2Var7.getClass();
        ks2Var8.getClass();
        ks2Var9.getClass();
        ks2Var10.getClass();
        ks2Var11.getClass();
        ks2Var12.getClass();
        ks2Var13.getClass();
        ks2Var14.getClass();
        ks2Var15.getClass();
        ks2Var16.getClass();
        ks2Var17.getClass();
        ks2Var18.getClass();
        ls2Var.getClass();
        ms2Var.getClass();
        ls2Var2.getClass();
        ls2Var3.getClass();
        ks2Var19.getClass();
        ur2Var8.getClass();
        wr2Var5.getClass();
        ks2Var20.getClass();
        wr2Var6.getClass();
        ks2Var21.getClass();
        wr2Var7.getClass();
        wr2Var8.getClass();
        wr2Var9.getClass();
        ur2Var9.getClass();
        ur2Var10.getClass();
        wr2Var10.getClass();
        wr2Var11.getClass();
        wr2Var12.getClass();
        ur2Var11.getClass();
        wr2Var13.getClass();
        wr2Var14.getClass();
        wr2Var15.getClass();
        wr2Var16.getClass();
        ks2Var22.getClass();
        wr2Var17.getClass();
        wr2Var18.getClass();
        ks2Var23.getClass();
        ls2Var4.getClass();
        ks2Var24.getClass();
        ks2Var25.getClass();
        ks2Var26.getClass();
        this.a = context;
        this.b = lp3Var;
        this.c = ft3Var;
        this.d = av3Var;
        this.e = f8Var;
        this.f = ze0Var;
        this.g = lc7Var;
        this.h = aj3Var;
        this.i = ni3Var;
        this.j = bw3Var;
        this.k = sa3Var;
        this.l = fb3Var;
        this.m = ta3Var;
        this.n = d84Var;
        this.o = m64Var;
        this.p = rw3Var;
        this.q = ww6Var;
        this.r = rk3Var;
        this.s = p83Var;
        this.t = qw3Var;
        this.u = i93Var;
        this.v = z33Var;
        this.w = n63Var;
        this.x = k93Var;
        this.y = j;
        this.z = z;
        this.A = fa0Var;
        this.B = ia0Var;
        this.C = z2;
        this.D = z3;
        this.E = g43Var;
        this.F = ur2Var;
        this.G = wr2Var;
        this.H = wr2Var2;
        this.I = wr2Var3;
        this.J = wr2Var4;
        this.K = ur2Var2;
        this.L = ur2Var3;
        this.M = ks2Var;
        this.N = ks2Var2;
        this.O = ur2Var4;
        this.P = ur2Var5;
        this.Q = ur2Var6;
        this.R = ur2Var7;
        this.S = ks2Var3;
        this.T = ks2Var4;
        this.U = ks2Var5;
        this.V = ks2Var6;
        this.W = ks2Var7;
        this.X = ks2Var8;
        this.Y = ks2Var9;
        this.Z = ks2Var10;
        this.a0 = ks2Var11;
        this.b0 = ks2Var12;
        this.c0 = ks2Var13;
        this.d0 = ks2Var14;
        this.e0 = ks2Var15;
        this.f0 = ks2Var16;
        this.g0 = ks2Var17;
        this.h0 = ks2Var18;
        this.i0 = ls2Var;
        this.j0 = ms2Var;
        this.k0 = ls2Var2;
        this.l0 = ls2Var3;
        this.m0 = ks2Var19;
        this.n0 = ur2Var8;
        this.o0 = wr2Var5;
        this.p0 = ks2Var20;
        this.q0 = wr2Var6;
        this.r0 = ks2Var21;
        this.s0 = wr2Var7;
        this.t0 = wr2Var8;
        this.u0 = wr2Var9;
        this.v0 = ur2Var9;
        this.w0 = ur2Var10;
        this.x0 = wr2Var10;
        this.y0 = wr2Var11;
        this.z0 = wr2Var12;
        this.A0 = ur2Var11;
        this.B0 = wr2Var13;
        this.C0 = wr2Var14;
        this.D0 = wr2Var15;
        this.E0 = wr2Var16;
        this.F0 = ks2Var22;
        this.G0 = wr2Var17;
        this.H0 = wr2Var18;
        this.I0 = ks2Var23;
        this.J0 = ls2Var4;
        this.K0 = ks2Var24;
        this.L0 = ks2Var25;
        this.M0 = ks2Var26;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof f93) {
            f93 f93Var = (f93) obj;
            if (this.a.equals(f93Var.a) && this.b == f93Var.b && this.c == f93Var.c && this.d.equals(f93Var.d) && ye4.p(this.e, f93Var.e) && ye4.p(this.f, f93Var.f) && ye4.p(this.g, f93Var.g) && ye4.p(this.h, f93Var.h) && this.i == f93Var.i && this.j.equals(f93Var.j) && ye4.p(this.k, f93Var.k) && this.l == f93Var.l && this.m.equals(f93Var.m) && ye4.p(this.n, f93Var.n) && ye4.p(this.o, f93Var.o) && ye4.p(this.p, f93Var.p) && ye4.p(this.q, f93Var.q) && this.r.equals(f93Var.r) && this.s.equals(f93Var.s) && this.t == f93Var.t && this.u == f93Var.u && this.v.equals(f93Var.v) && this.w == f93Var.w && this.x == f93Var.x && this.y == f93Var.y && this.z == f93Var.z && this.A == f93Var.A && this.B == f93Var.B && this.C == f93Var.C && this.D == f93Var.D && this.E == f93Var.E && ye4.p(this.F, f93Var.F) && ye4.p(this.G, f93Var.G) && ye4.p(this.H, f93Var.H) && ye4.p(this.I, f93Var.I) && ye4.p(this.J, f93Var.J) && ye4.p(this.K, f93Var.K) && ye4.p(this.L, f93Var.L) && ye4.p(this.M, f93Var.M) && ye4.p(this.N, f93Var.N) && ye4.p(this.O, f93Var.O) && ye4.p(this.P, f93Var.P) && ye4.p(this.Q, f93Var.Q) && ye4.p(this.R, f93Var.R) && ye4.p(this.S, f93Var.S) && ye4.p(this.T, f93Var.T) && ye4.p(this.U, f93Var.U) && ye4.p(this.V, f93Var.V) && ye4.p(this.W, f93Var.W) && ye4.p(this.X, f93Var.X) && ye4.p(this.Y, f93Var.Y) && ye4.p(this.Z, f93Var.Z) && ye4.p(this.a0, f93Var.a0) && ye4.p(this.b0, f93Var.b0) && ye4.p(this.c0, f93Var.c0) && ye4.p(this.d0, f93Var.d0) && ye4.p(this.e0, f93Var.e0) && ye4.p(this.f0, f93Var.f0) && ye4.p(this.g0, f93Var.g0) && ye4.p(this.h0, f93Var.h0) && ye4.p(this.i0, f93Var.i0) && ye4.p(this.j0, f93Var.j0) && ye4.p(this.k0, f93Var.k0) && ye4.p(this.l0, f93Var.l0) && ye4.p(this.m0, f93Var.m0) && ye4.p(this.n0, f93Var.n0) && ye4.p(this.o0, f93Var.o0) && ye4.p(this.p0, f93Var.p0) && ye4.p(this.q0, f93Var.q0) && ye4.p(this.r0, f93Var.r0) && ye4.p(this.s0, f93Var.s0) && ye4.p(this.t0, f93Var.t0) && ye4.p(this.u0, f93Var.u0) && ye4.p(this.v0, f93Var.v0) && ye4.p(this.w0, f93Var.w0) && ye4.p(this.x0, f93Var.x0) && ye4.p(this.y0, f93Var.y0) && ye4.p(this.z0, f93Var.z0) && ye4.p(this.A0, f93Var.A0) && ye4.p(this.B0, f93Var.B0) && ye4.p(this.C0, f93Var.C0) && ye4.p(this.D0, f93Var.D0) && ye4.p(this.E0, f93Var.E0) && ye4.p(this.F0, f93Var.F0) && ye4.p(this.G0, f93Var.G0) && ye4.p(this.H0, f93Var.H0) && ye4.p(this.I0, f93Var.I0) && ye4.p(this.J0, f93Var.J0) && ye4.p(this.K0, f93Var.K0) && ye4.p(this.L0, f93Var.L0) && ye4.p(this.M0, f93Var.M0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        return this.M0.hashCode() + rx1.d(rx1.d(rx1.g(this.J0, rx1.d(pk0.b(pk0.b(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.A0, pk0.b(pk0.b(pk0.b(rx1.f(this.w0, rx1.f(this.v0, pk0.b(pk0.b(pk0.b(rx1.d(pk0.b(rx1.d(pk0.b(rx1.f(this.n0, rx1.d(rx1.g(this.l0, rx1.g(this.k0, (this.j0.hashCode() + rx1.g(this.i0, rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.f(this.R, rx1.f(this.Q, rx1.f(this.P, rx1.f(this.O, rx1.d(rx1.d(rx1.f(this.L, rx1.f(this.K, pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.F, (this.E.hashCode() + a68.d(a68.d((this.B.hashCode() + qv7.b(this.A, a68.d(j55.d(this.y, (this.x.hashCode() + ((this.w.hashCode() + ((this.v.hashCode() + ((this.u.hashCode() + ((this.t.hashCode() + ((this.s.hashCode() + ((this.r.hashCode() + f33.c(this.q, (this.p.hashCode() + ((this.o.hashCode() + ((this.n.hashCode() + ((this.m.hashCode() + ((this.l.hashCode() + ((this.k.hashCode() + ((this.j.hashCode() + ((this.i.hashCode() + ((this.h.hashCode() + rx1.j(this.g, rx1.e(this.f, (this.e.hashCode() + ((this.d.hashCode() + rx1.i(this.c, rx1.h(this.b, this.a.hashCode() * 31, 31), 31)) * 31)) * 31, 31), 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), 31, this.z), 31)) * 31, 31, this.C), 31, this.D)) * 31, 31), this.G, 31), this.H, 31), this.I, 31), this.J, 31), 31), 31), 31, this.M), 31, this.N), 31), 31), 31), 31), 31, this.S), 31, this.T), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), 31, this.b0), 31, this.c0), 31, this.d0), 31, this.e0), 31, this.f0), 31, this.g0), 31, this.h0), 31)) * 31, 31), 31), 31, this.m0), 31), this.o0, 31), 31, this.p0), this.q0, 31), 31, this.r0), this.s0, 31), this.t0, 31), this.u0, 31), 31), 31), this.x0, 31), this.y0, 31), this.z0, 31), 31), this.B0, 31), this.C0, 31), this.D0, 31), this.E0, 31), 31, this.F0), this.G0, 31), this.H0, 31), 31, this.I0), 31), 31, this.K0), 31, this.L0);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomeDialogSystemHostLayerOwnerDeps(context=");
        sb.append(this.a);
        sb.append(", runtimeState=");
        sb.append(this.b);
        sb.append(", callbacks=");
        sb.append(this.c);
        sb.append(", systemPickerRequests=");
        sb.append(this.d);
        sb.append(", addTabState=");
        sb.append(this.e);
        sb.append(", browserState=");
        sb.append(this.f);
        sb.append(", scraperState=");
        sb.append(this.g);
        sb.append(", quickAccessWidgetPolicyRuntimeOwners=");
        sb.append(this.h);
        sb.append(", quickAccessWidgetActions=");
        sb.append(this.i);
        sb.append(", activeTaskMenuBindings=");
        sb.append(this.j);
        sb.append(", globalSearchDialogActions=");
        sb.append(this.k);
        sb.append(", globalSearchSessionState=");
        sb.append(this.l);
        sb.append(", globalSearchIntegration=");
        sb.append(this.m);
        sb.append(", iisuSettingsSnapshot=");
        sb.append(this.n);
        sb.append(", iisuSettingsCallbacks=");
        sb.append(this.o);
        sb.append(", themeCreationState=");
        sb.append(this.p);
        sb.append(", retroAchievementsState=");
        sb.append(this.q);
        sb.append(", raTaskRouting=");
        sb.append(this.r);
        sb.append(", dialogRoutes=");
        sb.append(this.s);
        sb.append(", taskScraperSettingsFacade=");
        sb.append(this.t);
        sb.append(", earlyActionOwners=");
        sb.append(this.u);
        sb.append(", categoryBrowserRoutingOwner=");
        sb.append(this.v);
        sb.append(", dialogLaunchActions=");
        sb.append(this.w);
        sb.append(", focusSignalOwner=");
        sb.append(this.x);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.y);
        sb.append(", hasRetroAchievementsSession=");
        sb.append(this.z);
        sb.append(", romBrowserLayoutMode=");
        sb.append(this.A);
        sb.append(", romBrowserListLayout=");
        sb.append(this.B);
        qv7.v(", isOnExternalDisplay=", ", isHomeViewportExternalDisplay=", sb, this.C, this.D);
        sb.append(", onDismissStart=");
        sb.append(this.E);
        sb.append(", onOpenGlobalSearch=");
        sb.append(this.F);
        rx1.C(sb, ", onGlobalSearchResultActivated=", this.G, ", onGlobalSearchResultNavigated=", this.H);
        rx1.C(sb, ", onRetroAchievementFocused=", this.I, ", onRetroAchievementActivated=", this.J);
        rx1.x(this.K, this.L, ", onTopLevelDismiss=", ", persistUiSessionNow=", sb);
        f33.w(sb, ", onSetTabCustomLabel=", this.M, ", onToggleRomShortcut=", this.N);
        rx1.x(this.O, this.P, ", onIncreaseDensity=", ", onDecreaseDensity=", sb);
        rx1.x(this.Q, this.R, ", onIncreaseCategoryGridDensity=", ", onDecreaseCategoryGridDensity=", sb);
        f33.w(sb, ", onSetTabPreferZoomedArtwork=", this.S, ", onSetTabRomArtworkAlignment=", this.T);
        f33.w(sb, ", onSetTabRomTitleSectionMode=", this.U, ", onSetTabTrophyIconCorner=", this.V);
        f33.w(sb, ", onSetTabTrophyIconAlpha=", this.W, ", onSetTabPreferNativeRomIconSize=", this.X);
        f33.w(sb, ", onSetTabsPreferNativeRomIconSize=", this.Y, ", onSetTabRomIconAspectRatioPresetId=", this.Z);
        f33.w(sb, ", onSetRomPreferNativeRomIconSize=", this.a0, ", onSetRomIconAspectRatioPresetId=", this.b0);
        f33.w(sb, ", onSetRomArtworkAlignment=", this.c0, ", onSetRomTitleSectionMode=", this.d0);
        f33.w(sb, ", onSetRomCustomName=", this.e0, ", onSetRomTrophyIconCorner=", this.f0);
        f33.w(sb, ", onSetRomTrophyIconAlpha=", this.g0, ", onUpdateRomLaunchPreference=", this.h0);
        sb.append(", onUpdateRomLinkedPreference=");
        sb.append(this.i0);
        sb.append(", onUpdateRomCommandPreference=");
        sb.append(this.j0);
        sb.append(", onSetRomInCustomCollection=");
        sb.append(this.k0);
        sb.append(", onToggleRomVisibility=");
        sb.append(this.l0);
        sb.append(", onToggleAppVisibility=");
        sb.append(this.m0);
        sb.append(", onShowRetroAchievements=");
        sb.append(this.n0);
        sb.append(", onDownloadRommRom=");
        sb.append(this.o0);
        sb.append(", onDownloadAllRommRoms=");
        sb.append(this.p0);
        sb.append(", onDeleteRommRom=");
        sb.append(this.q0);
        sb.append(", onDeleteAllRommRoms=");
        sb.append(this.r0);
        rx1.C(sb, ", isRommRomDownloaded=", this.s0, ", onManageRomQuickAccessIcon=", this.t0);
        sb.append(", onDeleteRomQuickAccessIcon=");
        sb.append(this.u0);
        sb.append(", onSaveConsole=");
        sb.append(this.v0);
        sb.append(", onDeleteConsole=");
        sb.append(this.w0);
        sb.append(", onSelectConsole=");
        sb.append(this.x0);
        rx1.C(sb, ", onSelectEmulator=", this.y0, ", onSelectEmulatorPackage=", this.z0);
        sb.append(", onDetectInstalledEmulator=");
        sb.append(this.A0);
        sb.append(", onSelectCommand=");
        sb.append(this.B0);
        rx1.C(sb, ", onCustomLaunchCommandChange=", this.C0, ", onTabLabelChange=", this.D0);
        sb.append(", onRequestAddTabDirectory=");
        sb.append(this.E0);
        sb.append(", onAddTabDirectorySelected=");
        sb.append(this.F0);
        rx1.C(sb, ", onRemoveDirectory=", this.G0, ", onDefaultLaunchPreferenceChange=", this.H0);
        sb.append(", onToggleAppShortcut=");
        sb.append(this.I0);
        sb.append(", onUpdateAppLinkedPreference=");
        sb.append(this.J0);
        f33.w(sb, ", onUpdateAppLaunchPreference=", this.K0, ", onUpdateAppClassification=", this.L0);
        sb.append(", onSetAppCustomName=");
        sb.append(this.M0);
        sb.append(")");
        return sb.toString();
    }
}
