package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public abstract class ft0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = tz5.q;
        a = j2;
        b = tz5.f;
        c = tz5.d;
        d = tz5.m;
        e = tz5.G;
        long j3 = tz5.s;
        f = j3;
        g = j3;
        h = tz5.c;
        i = tz5.g;
        long j4 = tz5.I;
        j = j4;
        k = tz5.D;
        long j5 = tz5.F;
        l = j5;
        m = tz5.L;
        long j6 = tz5.P;
        n = j6;
        o = tz5.J;
        long j7 = tz5.M;
        p = j7;
        q = tz5.B;
        r = tz5.S;
        long j8 = tz5.W;
        s = j8;
        t = tz5.Q;
        long j9 = tz5.T;
        u = j9;
        v = tz5.A;
        long j10 = tz5.y;
        w = j10;
        long j11 = tz5.H;
        x = j5;
        y = j4;
        z = j11;
        A = tz5.h;
        long j12 = tz5.O;
        B = j12;
        C = j7;
        D = j6;
        E = j12;
        F = tz5.o;
        G = tz5.k;
        H = tz5.l;
        I = tz5.n;
        J = tz5.i;
        K = tz5.p;
        L = j2;
        M = j10;
        long j13 = tz5.V;
        N = j13;
        O = j9;
        P = j8;
        Q = j13;
    }
}
