package defpackage;

import java.util.List;
import java.util.Map;
import java.util.Set;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class hr3 {
    public final boolean A;
    public final int A0;
    public final ur2 A1;
    public final boolean B;
    public final wi2 B0;
    public final ls2 B1;
    public final boolean C;
    public final boolean C0;
    public final wr2 C1;
    public final tc1 D;
    public final ur2 D0;
    public final wr2 D1;
    public final boolean E;
    public final i42 E0;
    public final ks2 E1;
    public final hc7 F;
    public final wr2 F0;
    public final gq3 F1;
    public final boolean G;
    public final wr2 G0;
    public final a33 G1;
    public final boolean H;
    public final wr2 H0;
    public final wr2 H1;
    public final ga3 I;
    public final gq3 I0;
    public final df3 I1;
    public final ww6 J;
    public final wr2 J0;
    public final q13 J1;
    public final boolean K;
    public final wr2 K0;
    public final ks2 K1;
    public final Map L;
    public final wr2 L0;
    public final ur2 L1;
    public final Set M;
    public final e93 M0;
    public final ur2 M1;
    public final String N;
    public final cj3 N0;
    public final wr2 N1;
    public final Map O;
    public final wr2 O0;
    public final wr2 O1;
    public final int P;
    public final wr2 P0;
    public final wr2 P1;
    public final Map Q;
    public final wr2 Q0;
    public final wr2 Q1;
    public final String R;
    public final mq3 R0;
    public final wr2 R1;
    public final rz5 S;
    public final cj3 S0;
    public final ur2 S1;
    public final int T;
    public final cj3 T0;
    public final ur2 T1;
    public final boolean U;
    public final cj3 U0;
    public final wr2 U1;
    public final int V;
    public final de3 V0;
    public final wr2 V1;
    public final boolean W;
    public final ur2 W0;
    public final fa0 X;
    public final wr2 X0;
    public final ia0 Y;
    public final wr2 Y0;
    public final float Z;
    public final f43 Z0;
    public final ze0 a;
    public final z70 a0;
    public final cj3 a1;
    public final bt2 b;
    public final wr2 b0;
    public final iw3 b1;
    public final List c;
    public final String c0;
    public final wr2 c1;
    public final List d;
    public final rz5 d0;
    public final wr2 d1;
    public final Map e;
    public final int e0;
    public final wr2 e1;
    public final lp3 f;
    public final boolean f0;
    public final ur2 f1;
    public final tu3 g;
    public final boolean g0;
    public final wr2 g1;
    public final ft3 h;
    public final fa0 h0;
    public final ur2 h1;
    public final dj3 i;
    public final ia0 i0;
    public final ur2 i1;
    public final ni3 j;
    public final float j0;
    public final ur2 j1;
    public final ev3 k;
    public final z70 k0;
    public final ks2 k1;
    public final dr3 l;
    public final wj2 l0;
    public final wr2 l1;
    public final dr3 m;
    public final long m0;
    public final gq3 m1;
    public final boolean n;
    public final Object n0;
    public final de3 n1;
    public final boolean o;
    public final Map o0;
    public final jj3 o1;
    public final boolean p;
    public final Map p0;
    public final jj3 p1;
    public final boolean q;
    public final Map q0;
    public final wr2 q1;
    public final boolean r;
    public final Map r0;
    public final ur2 r1;
    public final int s;
    public final int s0;
    public final iw3 s1;
    public final int t;
    public final boolean t0;
    public final f43 t1;
    public final int u;
    public final yq2 u0;
    public final cj3 u1;
    public final vc3 v;
    public final int v0;
    public final wr2 v1;
    public final boolean w;
    public final boolean w0;
    public final wr2 w1;
    public final boolean x;
    public final boolean x0;
    public final wr2 x1;
    public final boolean y;
    public final boolean y0;
    public final wr2 y1;
    public final boolean z;
    public final xm8 z0;
    public final ur2 z1;

    public hr3(ze0 ze0Var, bt2 bt2Var, List list, List list2, Map map, lp3 lp3Var, tu3 tu3Var, ft3 ft3Var, dj3 dj3Var, ni3 ni3Var, ev3 ev3Var, dr3 dr3Var, dr3 dr3Var2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, int i, int i2, int i3, vc3 vc3Var, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, tc1 tc1Var, boolean z13, hc7 hc7Var, boolean z14, boolean z15, ga3 ga3Var, ww6 ww6Var, boolean z16, Map map2, Set set, String str, Map map3, int i4, Map map4, String str2, rz5 rz5Var, int i5, boolean z17, int i6, boolean z18, fa0 fa0Var, ia0 ia0Var, float f, z70 z70Var, wr2 wr2Var, String str3, rz5 rz5Var2, int i7, boolean z19, boolean z20, fa0 fa0Var2, ia0 ia0Var2, float f2, z70 z70Var2, wj2 wj2Var, long j, Object obj, Map map5, Map map6, Map map7, Map map8, int i8, boolean z21, yq2 yq2Var, int i9, boolean z22, boolean z23, boolean z24, xm8 xm8Var, int i10, wi2 wi2Var, boolean z25, ur2 ur2Var, i42 i42Var, gq3 gq3Var, gq3 gq3Var2, gq3 gq3Var3, gq3 gq3Var4, wr2 wr2Var2, wr2 wr2Var3, gq3 gq3Var5, e93 e93Var, cj3 cj3Var, gq3 gq3Var6, gq3 gq3Var7, gq3 gq3Var8, mq3 mq3Var, cj3 cj3Var2, cj3 cj3Var3, cj3 cj3Var4, de3 de3Var, ur2 ur2Var2, wr2 wr2Var4, wr2 wr2Var5, f43 f43Var, cj3 cj3Var5, iw3 iw3Var, wr2 wr2Var6, wr2 wr2Var7, wr2 wr2Var8, ur2 ur2Var3, wr2 wr2Var9, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, ks2 ks2Var, gq3 gq3Var9, gq3 gq3Var10, de3 de3Var2, jj3 jj3Var, jj3 jj3Var2, wr2 wr2Var10, ur2 ur2Var7, iw3 iw3Var2, f43 f43Var2, cj3 cj3Var6, wr2 wr2Var11, wr2 wr2Var12, wr2 wr2Var13, wr2 wr2Var14, ur2 ur2Var8, ur2 ur2Var9, ls2 ls2Var, gq3 gq3Var11, wr2 wr2Var15, ks2 ks2Var2, gq3 gq3Var12, a33 a33Var, wr2 wr2Var16, df3 df3Var, q13 q13Var, ks2 ks2Var3, ur2 ur2Var10, ur2 ur2Var11, wr2 wr2Var17, wr2 wr2Var18, wr2 wr2Var19, wr2 wr2Var20, wr2 wr2Var21, ur2 ur2Var12, ur2 ur2Var13, wr2 wr2Var22, wr2 wr2Var23) {
        ze0Var.getClass();
        bt2Var.getClass();
        list.getClass();
        list2.getClass();
        dr3Var.getClass();
        dr3Var2.getClass();
        ga3Var.getClass();
        ww6Var.getClass();
        set.getClass();
        map4.getClass();
        fa0Var.getClass();
        ia0Var.getClass();
        z70Var.getClass();
        fa0Var2.getClass();
        ia0Var2.getClass();
        z70Var2.getClass();
        map5.getClass();
        yq2Var.getClass();
        gq3Var.getClass();
        gq3Var2.getClass();
        gq3Var3.getClass();
        wr2Var2.getClass();
        wr2Var3.getClass();
        gq3Var5.getClass();
        gq3Var6.getClass();
        gq3Var7.getClass();
        gq3Var8.getClass();
        ur2Var2.getClass();
        wr2Var4.getClass();
        wr2Var5.getClass();
        wr2Var6.getClass();
        wr2Var7.getClass();
        wr2Var8.getClass();
        wr2Var9.getClass();
        ur2Var4.getClass();
        ur2Var5.getClass();
        ur2Var6.getClass();
        ks2Var.getClass();
        gq3Var9.getClass();
        wr2Var10.getClass();
        ur2Var7.getClass();
        wr2Var11.getClass();
        wr2Var12.getClass();
        wr2Var13.getClass();
        wr2Var14.getClass();
        ur2Var9.getClass();
        ls2Var.getClass();
        gq3Var11.getClass();
        wr2Var15.getClass();
        ks2Var2.getClass();
        ks2Var3.getClass();
        ur2Var10.getClass();
        ur2Var11.getClass();
        wr2Var17.getClass();
        wr2Var19.getClass();
        wr2Var20.getClass();
        wr2Var21.getClass();
        ur2Var12.getClass();
        ur2Var13.getClass();
        wr2Var22.getClass();
        wr2Var23.getClass();
        this.a = ze0Var;
        this.b = bt2Var;
        this.c = list;
        this.d = list2;
        this.e = map;
        this.f = lp3Var;
        this.g = tu3Var;
        this.h = ft3Var;
        this.i = dj3Var;
        this.j = ni3Var;
        this.k = ev3Var;
        this.l = dr3Var;
        this.m = dr3Var2;
        this.n = z;
        this.o = z2;
        this.p = z3;
        this.q = z4;
        this.r = z5;
        this.s = i;
        this.t = i2;
        this.u = i3;
        this.v = vc3Var;
        this.w = z6;
        this.x = z7;
        this.y = z8;
        this.z = z9;
        this.A = z10;
        this.B = z11;
        this.C = z12;
        this.D = tc1Var;
        this.E = z13;
        this.F = hc7Var;
        this.G = z14;
        this.H = z15;
        this.I = ga3Var;
        this.J = ww6Var;
        this.K = z16;
        this.L = map2;
        this.M = set;
        this.N = str;
        this.O = map3;
        this.P = i4;
        this.Q = map4;
        this.R = str2;
        this.S = rz5Var;
        this.T = i5;
        this.U = z17;
        this.V = i6;
        this.W = z18;
        this.X = fa0Var;
        this.Y = ia0Var;
        this.Z = f;
        this.a0 = z70Var;
        this.b0 = wr2Var;
        this.c0 = str3;
        this.d0 = rz5Var2;
        this.e0 = i7;
        this.f0 = z19;
        this.g0 = z20;
        this.h0 = fa0Var2;
        this.i0 = ia0Var2;
        this.j0 = f2;
        this.k0 = z70Var2;
        this.l0 = wj2Var;
        this.m0 = j;
        this.n0 = obj;
        this.o0 = map5;
        this.p0 = map6;
        this.q0 = map7;
        this.r0 = map8;
        this.s0 = i8;
        this.t0 = z21;
        this.u0 = yq2Var;
        this.v0 = i9;
        this.w0 = z22;
        this.x0 = z23;
        this.y0 = z24;
        this.z0 = xm8Var;
        this.A0 = i10;
        this.B0 = wi2Var;
        this.C0 = z25;
        this.D0 = ur2Var;
        this.E0 = i42Var;
        this.F0 = gq3Var;
        this.G0 = gq3Var2;
        this.H0 = gq3Var3;
        this.I0 = gq3Var4;
        this.J0 = wr2Var2;
        this.K0 = wr2Var3;
        this.L0 = gq3Var5;
        this.M0 = e93Var;
        this.N0 = cj3Var;
        this.O0 = gq3Var6;
        this.P0 = gq3Var7;
        this.Q0 = gq3Var8;
        this.R0 = mq3Var;
        this.S0 = cj3Var2;
        this.T0 = cj3Var3;
        this.U0 = cj3Var4;
        this.V0 = de3Var;
        this.W0 = ur2Var2;
        this.X0 = wr2Var4;
        this.Y0 = wr2Var5;
        this.Z0 = f43Var;
        this.a1 = cj3Var5;
        this.b1 = iw3Var;
        this.c1 = wr2Var6;
        this.d1 = wr2Var7;
        this.e1 = wr2Var8;
        this.f1 = ur2Var3;
        this.g1 = wr2Var9;
        this.h1 = ur2Var4;
        this.i1 = ur2Var5;
        this.j1 = ur2Var6;
        this.k1 = ks2Var;
        this.l1 = gq3Var9;
        this.m1 = gq3Var10;
        this.n1 = de3Var2;
        this.o1 = jj3Var;
        this.p1 = jj3Var2;
        this.q1 = wr2Var10;
        this.r1 = ur2Var7;
        this.s1 = iw3Var2;
        this.t1 = f43Var2;
        this.u1 = cj3Var6;
        this.v1 = wr2Var11;
        this.w1 = wr2Var12;
        this.x1 = wr2Var13;
        this.y1 = wr2Var14;
        this.z1 = ur2Var8;
        this.A1 = ur2Var9;
        this.B1 = ls2Var;
        this.C1 = gq3Var11;
        this.D1 = wr2Var15;
        this.E1 = ks2Var2;
        this.F1 = gq3Var12;
        this.G1 = a33Var;
        this.H1 = wr2Var16;
        this.I1 = df3Var;
        this.J1 = q13Var;
        this.K1 = ks2Var3;
        this.L1 = ur2Var10;
        this.M1 = ur2Var11;
        this.N1 = wr2Var17;
        this.O1 = wr2Var18;
        this.P1 = wr2Var19;
        this.Q1 = wr2Var20;
        this.R1 = wr2Var21;
        this.S1 = ur2Var12;
        this.T1 = ur2Var13;
        this.U1 = wr2Var22;
        this.V1 = wr2Var23;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof hr3) {
            hr3 hr3Var = (hr3) obj;
            if (ye4.p(this.a, hr3Var.a) && ye4.p(this.b, hr3Var.b) && ye4.p(this.c, hr3Var.c) && ye4.p(this.d, hr3Var.d) && this.e.equals(hr3Var.e) && this.f == hr3Var.f && this.g.equals(hr3Var.g) && this.h == hr3Var.h && this.i == hr3Var.i && this.j == hr3Var.j && this.k == hr3Var.k && ye4.p(this.l, hr3Var.l) && ye4.p(this.m, hr3Var.m) && this.n == hr3Var.n && this.o == hr3Var.o && this.p == hr3Var.p && this.q == hr3Var.q && this.r == hr3Var.r && this.s == hr3Var.s && this.t == hr3Var.t && this.u == hr3Var.u && this.v == hr3Var.v && this.w == hr3Var.w && this.x == hr3Var.x && this.y == hr3Var.y && this.z == hr3Var.z && this.A == hr3Var.A && this.B == hr3Var.B && this.C == hr3Var.C && ye4.p(this.D, hr3Var.D) && this.E == hr3Var.E && ye4.p(this.F, hr3Var.F) && this.G == hr3Var.G && this.H == hr3Var.H && ye4.p(this.I, hr3Var.I) && ye4.p(this.J, hr3Var.J) && this.K == hr3Var.K && this.L.equals(hr3Var.L) && ye4.p(this.M, hr3Var.M) && this.N.equals(hr3Var.N) && this.O.equals(hr3Var.O) && this.P == hr3Var.P && ye4.p(this.Q, hr3Var.Q) && ye4.p(this.R, hr3Var.R) && ye4.p(this.S, hr3Var.S) && this.T == hr3Var.T && this.U == hr3Var.U && this.V == hr3Var.V && this.W == hr3Var.W && this.X == hr3Var.X && this.Y == hr3Var.Y && Float.compare(this.Z, hr3Var.Z) == 0 && ye4.p(this.a0, hr3Var.a0) && this.b0.equals(hr3Var.b0) && this.c0.equals(hr3Var.c0) && ye4.p(this.d0, hr3Var.d0) && this.e0 == hr3Var.e0 && this.f0 == hr3Var.f0 && this.g0 == hr3Var.g0 && this.h0 == hr3Var.h0 && this.i0 == hr3Var.i0 && Float.compare(this.j0, hr3Var.j0) == 0 && ye4.p(this.k0, hr3Var.k0) && ye4.p(this.l0, hr3Var.l0) && this.m0 == hr3Var.m0 && ye4.p(this.n0, hr3Var.n0) && ye4.p(this.o0, hr3Var.o0) && this.p0.equals(hr3Var.p0) && this.q0.equals(hr3Var.q0) && this.r0.equals(hr3Var.r0) && this.s0 == hr3Var.s0 && this.t0 == hr3Var.t0 && ye4.p(this.u0, hr3Var.u0) && this.v0 == hr3Var.v0 && this.w0 == hr3Var.w0 && this.x0 == hr3Var.x0 && this.y0 == hr3Var.y0 && this.z0 == hr3Var.z0 && this.A0 == hr3Var.A0 && this.B0 == hr3Var.B0 && this.C0 == hr3Var.C0 && this.D0.equals(hr3Var.D0) && this.E0.equals(hr3Var.E0) && ye4.p(this.F0, hr3Var.F0) && ye4.p(this.G0, hr3Var.G0) && ye4.p(this.H0, hr3Var.H0) && this.I0.equals(hr3Var.I0) && ye4.p(this.J0, hr3Var.J0) && ye4.p(this.K0, hr3Var.K0) && ye4.p(this.L0, hr3Var.L0) && this.M0.equals(hr3Var.M0) && this.N0.equals(hr3Var.N0) && ye4.p(this.O0, hr3Var.O0) && ye4.p(this.P0, hr3Var.P0) && ye4.p(this.Q0, hr3Var.Q0) && this.R0.equals(hr3Var.R0) && this.S0.equals(hr3Var.S0) && this.T0.equals(hr3Var.T0) && this.U0.equals(hr3Var.U0) && this.V0.equals(hr3Var.V0) && ye4.p(this.W0, hr3Var.W0) && ye4.p(this.X0, hr3Var.X0) && ye4.p(this.Y0, hr3Var.Y0) && this.Z0 == hr3Var.Z0 && this.a1.equals(hr3Var.a1) && this.b1 == hr3Var.b1 && ye4.p(this.c1, hr3Var.c1) && ye4.p(this.d1, hr3Var.d1) && ye4.p(this.e1, hr3Var.e1) && this.f1.equals(hr3Var.f1) && ye4.p(this.g1, hr3Var.g1) && ye4.p(this.h1, hr3Var.h1) && ye4.p(this.i1, hr3Var.i1) && ye4.p(this.j1, hr3Var.j1) && ye4.p(this.k1, hr3Var.k1) && ye4.p(this.l1, hr3Var.l1) && this.m1.equals(hr3Var.m1) && this.n1.equals(hr3Var.n1) && this.o1 == hr3Var.o1 && this.p1 == hr3Var.p1 && ye4.p(this.q1, hr3Var.q1) && ye4.p(this.r1, hr3Var.r1) && this.s1 == hr3Var.s1 && this.t1 == hr3Var.t1 && this.u1.equals(hr3Var.u1) && ye4.p(this.v1, hr3Var.v1) && ye4.p(this.w1, hr3Var.w1) && ye4.p(this.x1, hr3Var.x1) && ye4.p(this.y1, hr3Var.y1) && this.z1.equals(hr3Var.z1) && ye4.p(this.A1, hr3Var.A1) && ye4.p(this.B1, hr3Var.B1) && ye4.p(this.C1, hr3Var.C1) && ye4.p(this.D1, hr3Var.D1) && ye4.p(this.E1, hr3Var.E1) && this.F1.equals(hr3Var.F1) && this.G1.equals(hr3Var.G1) && this.H1.equals(hr3Var.H1) && this.I1 == hr3Var.I1 && this.J1 == hr3Var.J1 && ye4.p(this.K1, hr3Var.K1) && ye4.p(this.L1, hr3Var.L1) && ye4.p(this.M1, hr3Var.M1) && ye4.p(this.N1, hr3Var.N1) && this.O1.equals(hr3Var.O1) && ye4.p(this.P1, hr3Var.P1) && ye4.p(this.Q1, hr3Var.Q1) && ye4.p(this.R1, hr3Var.R1) && ye4.p(this.S1, hr3Var.S1) && ye4.p(this.T1, hr3Var.T1) && ye4.p(this.U1, hr3Var.U1) && ye4.p(this.V1, hr3Var.V1)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int iA = f33.a(this.u, f33.a(this.t, f33.a(this.s, a68.d(a68.d(a68.d(a68.d(a68.d((this.m.hashCode() + ((this.l.hashCode() + ((this.k.hashCode() + ((this.j.hashCode() + f33.b(this.i, rx1.i(this.h, (this.g.hashCode() + rx1.h(this.f, a68.f(this.e, a68.e(this.d, a68.e(this.c, (this.b.hashCode() + (this.a.hashCode() * 31)) * 31, 31), 31), 31), 31)) * 31, 31), 31)) * 31)) * 31)) * 31)) * 31, 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31), 31), 31);
        vc3 vc3Var = this.v;
        int iD = a68.d(a68.d(a68.d(a68.d(a68.d(a68.d(a68.d((iA + (vc3Var == null ? 0 : vc3Var.hashCode())) * 31, 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31, this.B), 31, this.C);
        tc1 tc1Var = this.D;
        int iD2 = a68.d((iD + (tc1Var == null ? 0 : tc1Var.hashCode())) * 31, 31, this.E);
        hc7 hc7Var = this.F;
        int iF = a68.f(this.Q, f33.a(this.P, a68.f(this.O, a68.c(pk0.a(a68.f(this.L, a68.d(f33.c(this.J, (this.I.hashCode() + a68.d(a68.d((iD2 + (hc7Var == null ? 0 : hc7Var.hashCode())) * 31, 31, this.G), 31, this.H)) * 31, 31), 31, this.K), 31), 31, this.M), 31, this.N), 31), 31), 31);
        String str = this.R;
        int iHashCode = (iF + (str == null ? 0 : str.hashCode())) * 31;
        rz5 rz5Var = this.S;
        int iC = a68.c(pk0.b((this.a0.hashCode() + rx1.c(this.Z, (this.Y.hashCode() + qv7.b(this.X, a68.d(f33.a(this.V, a68.d(f33.a(this.T, (iHashCode + (rz5Var == null ? 0 : rz5Var.hashCode())) * 31, 31), 31, this.U), 31), 31, this.W), 31)) * 31, 31)) * 31, this.b0, 31), 31, this.c0);
        rz5 rz5Var2 = this.d0;
        int iHashCode2 = (this.k0.hashCode() + rx1.c(this.j0, (this.i0.hashCode() + qv7.b(this.h0, a68.d(a68.d(f33.a(this.e0, (iC + (rz5Var2 == null ? 0 : rz5Var2.hashCode())) * 31, 31), 31, this.f0), 31, this.g0), 31)) * 31, 31)) * 31;
        wj2 wj2Var = this.l0;
        int iD3 = j55.d(this.m0, (iHashCode2 + (wj2Var == null ? 0 : wj2Var.hashCode())) * 31, 31);
        Object obj = this.n0;
        return this.V1.hashCode() + pk0.b(rx1.f(this.T1, rx1.f(this.S1, pk0.b(pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.M1, rx1.f(this.L1, rx1.d((this.J1.hashCode() + ((this.I1.hashCode() + pk0.b((this.G1.hashCode() + ((this.F1.hashCode() + rx1.d(pk0.b(pk0.b(rx1.g(this.B1, rx1.f(this.A1, rx1.f(this.z1, pk0.b(pk0.b(pk0.b(pk0.b((this.u1.hashCode() + ((this.t1.hashCode() + ((this.s1.hashCode() + rx1.f(this.r1, pk0.b((this.p1.hashCode() + ((this.o1.hashCode() + ((this.n1.hashCode() + ((this.m1.hashCode() + pk0.b(rx1.d(rx1.f(this.j1, rx1.f(this.i1, rx1.f(this.h1, pk0.b(rx1.f(this.f1, pk0.b(pk0.b(pk0.b((this.b1.hashCode() + ((this.a1.hashCode() + ((this.Z0.hashCode() + pk0.b(pk0.b(rx1.f(this.W0, (this.V0.hashCode() + ((this.U0.hashCode() + ((this.T0.hashCode() + ((this.S0.hashCode() + ((this.R0.hashCode() + pk0.b(pk0.b(pk0.b((this.N0.hashCode() + ((this.M0.hashCode() + pk0.b(pk0.b(pk0.b((this.I0.hashCode() + pk0.b(pk0.b(pk0.b((this.E0.hashCode() + rx1.f(this.D0, a68.d((this.B0.hashCode() + f33.a(this.A0, (this.z0.hashCode() + a68.d(a68.d(a68.d(f33.a(this.v0, (this.u0.hashCode() + a68.d(f33.a(this.s0, a68.f(this.r0, a68.f(this.q0, a68.f(this.p0, a68.f(this.o0, (iD3 + (obj != null ? obj.hashCode() : 0)) * 31, 31), 31), 31), 31), 31), 31, this.t0)) * 31, 31), 31, this.w0), 31, this.x0), 31, this.y0)) * 31, 31)) * 31, 31, this.C0), 31)) * 31, this.F0, 31), this.G0, 31), this.H0, 31)) * 31, this.J0, 31), this.K0, 31), this.L0, 31)) * 31)) * 31, this.O0, 31), this.P0, 31), this.Q0, 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), this.X0, 31), this.Y0, 31)) * 31)) * 31)) * 31, this.c1, 31), this.d1, 31), this.e1, 31), 31), this.g1, 31), 31), 31), 31), 31, this.k1), this.l1, 31)) * 31)) * 31)) * 31)) * 31, this.q1, 31), 31)) * 31)) * 31)) * 31, this.v1, 31), this.w1, 31), this.x1, 31), this.y1, 31), 31), 31), 31), this.C1, 31), this.D1, 31), 31, this.E1)) * 31)) * 31, this.H1, 31)) * 31)) * 31, 31, this.K1), 31), 31), this.N1, 31), this.O1, 31), this.P1, 31), this.Q1, 31), this.R1, 31), 31), 31), this.U1, 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomeSectionSceneRenderDeps(browserState=");
        sb.append(this.a);
        sb.append(", selectionState=");
        sb.append(this.b);
        sb.append(", appTabs=");
        pk0.z(", romTabs=", ", romsByTab=", sb, this.c, this.d);
        sb.append(this.e);
        sb.append(", runtimeState=");
        sb.append(this.f);
        sb.append(", state=");
        sb.append(this.g);
        sb.append(", callbacks=");
        sb.append(this.h);
        sb.append(", quickAccessWidgetState=");
        sb.append(this.i);
        sb.append(", quickAccessWidgetActions=");
        sb.append(this.j);
        sb.append(", tabMigrationProgressController=");
        sb.append(this.k);
        sb.append(", liveHomeSectionContent=");
        sb.append(this.l);
        sb.append(", frozenHomeSectionContent=");
        sb.append(this.m);
        sb.append(", homeSceneVisibleOrTransitioning=");
        sb.append(this.n);
        sb.append(", earlyHomeRecoveryActive=");
        a68.u(", overlayActive=", ", homeMotionStressActive=", sb, this.o, this.p);
        a68.u(", allowEditing=", ", quickAccessFocusSignal=", sb, this.q, this.r);
        pk0.r(this.s, this.t, ", quickAccessHostFocusSignal=", ", homeHudPromptActionSignal=", sb);
        sb.append(this.u);
        sb.append(", homeHudPromptAction=");
        sb.append(this.v);
        sb.append(", shouldRequestHomeFocus=");
        a68.u(", isCollectionSceneActive=", ", windowHasFocus=", sb, this.w, this.x);
        a68.u(", effectiveWindowFocus=", ", isSingleScreenViewEnabled=", sb, this.y, this.z);
        a68.u(", hasDualDisplay=", ", isMinimalModeActive=", sb, this.A, this.B);
        sb.append(this.C);
        sb.append(", activeCollectionState=");
        sb.append(this.D);
        sb.append(", isOnExternalDisplay=");
        sb.append(this.E);
        sb.append(", scraperVisualPrompt=");
        sb.append(this.F);
        sb.append(", isDialogSystemPickerOpen=");
        a68.u(", isRetroGameDetailsDialogVisible=", ", homeGlassPerformanceConfig=", sb, this.G, this.H);
        sb.append(this.I);
        sb.append(", retroAchievementsState=");
        sb.append(this.J);
        sb.append(", hasRetroAchievementsSession=");
        sb.append(this.K);
        sb.append(", retroConsoleIdByTab=");
        sb.append(this.L);
        sb.append(", romsWithoutAchievements=");
        sb.append(this.M);
        sb.append(", defaultContextMenuTitle=");
        sb.append(this.N);
        sb.append(", retroAchievementGameIdsForRoms=");
        sb.append(this.O);
        sb.append(", collectionSceneFocusSignal=");
        sb.append(this.P);
        sb.append(", tabLabelById=");
        sb.append(this.Q);
        sb.append(", appCategoryInitialFocusId=");
        sb.append(this.R);
        sb.append(", retainedAppCategoryXmbScrollPosition=");
        sb.append(this.S);
        sb.append(", appsCategoryFocusSignal=");
        sb.append(this.T);
        sb.append(", shouldRequestAppsCategoryFocus=");
        pk0.u(this.V, ", appsBrowserFocusSignal=", ", shouldRequestAppsBrowserFocus=", sb, this.U);
        sb.append(this.W);
        sb.append(", appBrowserLayoutMode=");
        sb.append(this.X);
        sb.append(", appBrowserListLayout=");
        sb.append(this.Y);
        sb.append(", appXmbExitProgress=");
        sb.append(this.Z);
        sb.append(", appsBrowserEntryWarmupGate=");
        sb.append(this.a0);
        sb.append(", appXmbReturnOverlayReadySetter=");
        sb.append(this.b0);
        sb.append(", romCategoryInitialFocusId=");
        sb.append(this.c0);
        sb.append(", retainedRomCategoryXmbScrollPosition=");
        sb.append(this.d0);
        sb.append(", romCategoryFocusSignal=");
        rx1.u(this.e0, ", shouldRequestRomCategoryFocus=", ", shouldRequestRomBrowserFocus=", sb, this.f0);
        sb.append(this.g0);
        sb.append(", romBrowserLayoutMode=");
        sb.append(this.h0);
        sb.append(", romBrowserListLayout=");
        sb.append(this.i0);
        sb.append(", romXmbExitProgress=");
        sb.append(this.j0);
        sb.append(", romsBrowserEntryWarmupGate=");
        sb.append(this.k0);
        sb.append(", folderNavigationRequest=");
        sb.append(this.l0);
        sb.append(", retroHashRefreshKey=");
        sb.append(this.m0);
        sb.append(", forceTabMigrationKey=");
        sb.append(this.n0);
        sb.append(", retainedRomBrowserSnapshots=");
        sb.append(this.o0);
        sb.append(", retainedRomBrowserXmbScrollPositions=");
        sb.append(this.p0);
        sb.append(", retroAchievementRomByGameId=");
        sb.append(this.q0);
        sb.append(", retroAchievementPlatformKeyByGameId=");
        sb.append(this.r0);
        sb.append(", retroFocusSignal=");
        sb.append(this.s0);
        sb.append(", shouldRequestRetroFocus=");
        sb.append(this.t0);
        sb.append(", friendsState=");
        sb.append(this.u0);
        sb.append(", friendsFocusSignal=");
        sb.append(this.v0);
        qv7.v(", shouldRequestFriendsFocus=", ", deferSectionTransitionVisualUpdates=", sb, this.w0, this.x0);
        sb.append(", removeLargePanelContainers=");
        sb.append(this.y0);
        sb.append(", sectionTransition=");
        sb.append(this.z0);
        sb.append(", homeFillGapsRequestSignal=");
        sb.append(this.A0);
        sb.append(", homeFillGapsFocusRequester=");
        sb.append(this.B0);
        sb.append(", homeFillGapsFocused=");
        sb.append(this.C0);
        sb.append(", persistUiSessionNow=");
        sb.append(this.D0);
        sb.append(", closeActiveCollectionPopup=");
        sb.append(this.E0);
        sb.append(", handleHomeAppSelected=");
        sb.append(this.F0);
        rx1.C(sb, ", handleHomeRomSelected=", this.G0, ", handleCollectionSelected=", this.H0);
        sb.append(", handleHomeIisuWidgetActivated=");
        sb.append(this.I0);
        sb.append(", handleAppFocused=");
        sb.append(this.J0);
        rx1.C(sb, ", handleRomFocused=", this.K0, ", handleCollectionFocused=", this.L0);
        sb.append(", handleHomePlaceholderFocused=");
        sb.append(this.M0);
        sb.append(", handleHomePlaceholderActivated=");
        sb.append(this.N0);
        rx1.C(sb, ", handleHomeAppLongPress=", this.O0, ", handleHomeRomLongPress=", this.P0);
        sb.append(", handleHomeCollectionLongPress=");
        sb.append(this.Q0);
        sb.append(", onOpenFocusedItemMenu=");
        sb.append(this.R0);
        sb.append(", onHomeQuickAccessMotionActiveChange=");
        sb.append(this.S0);
        sb.append(", onHomeDashboardBoundsChanged=");
        sb.append(this.T0);
        sb.append(", onHomeSceneBoundsChanged=");
        sb.append(this.U0);
        sb.append(", handleRomActivated=");
        sb.append(this.V0);
        sb.append(", onRetroAchievementsShowDetails=");
        sb.append(this.W0);
        sb.append(", onAppCategoryXmbScrollPositionChange=");
        sb.append(this.X0);
        sb.append(", handleAppCategorySelected=");
        sb.append(this.Y0);
        sb.append(", handleAppCategoryFocused=");
        sb.append(this.Z0);
        sb.append(", handleAppCategoryLongPress=");
        sb.append(this.a1);
        sb.append(", handleAppCategoryLayoutModeChange=");
        sb.append(this.b1);
        rx1.C(sb, ", onUpdateAppTabOrder=", this.c1, ", onUpdateAppBrowserLayoutMode=", this.d1);
        sb.append(", onUpdateAppBrowserListLayout=");
        sb.append(this.e1);
        sb.append(", exitAppBrowser=");
        sb.append(this.f1);
        sb.append(", onSearchQueryChange=");
        sb.append(this.g1);
        sb.append(", onRefreshApps=");
        sb.append(this.h1);
        rx1.x(this.i1, this.j1, ", onDecreaseDensity=", ", onIncreaseDensity=", sb);
        sb.append(", onToggleAppVisibility=");
        sb.append(this.k1);
        sb.append(", handleAppLongPress=");
        sb.append(this.l1);
        sb.append(", openAppGameInfo=");
        sb.append(this.m1);
        sb.append(", handleAppActivated=");
        sb.append(this.n1);
        sb.append(", onCategoryMotionActiveChange=");
        sb.append(this.o1);
        sb.append(", onBrowserMotionActiveChange=");
        sb.append(this.p1);
        sb.append(", onRomCategoryXmbScrollPositionChange=");
        sb.append(this.q1);
        sb.append(", onAddTab=");
        sb.append(this.r1);
        sb.append(", handleRomCategorySelected=");
        sb.append(this.s1);
        sb.append(", handleCategoryFocused=");
        sb.append(this.t1);
        sb.append(", handleRomCategoryLongPress=");
        sb.append(this.u1);
        sb.append(", handleRomCategoryLayoutModeChange=");
        sb.append(this.v1);
        rx1.C(sb, ", onUpdatePlatformTabOrder=", this.w1, ", onUpdateRomBrowserLayoutMode=", this.x1);
        sb.append(", onUpdateRomBrowserListLayout=");
        sb.append(this.y1);
        sb.append(", exitRomBrowser=");
        sb.append(this.z1);
        sb.append(", openAppsPopupFromController=");
        sb.append(this.A1);
        sb.append(", onToggleRomVisibility=");
        sb.append(this.B1);
        rx1.C(sb, ", handleRomLongPress=", this.C1, ", onIsRommRomDownloaded=", this.D1);
        sb.append(", handleRetroAchievementsRegisterHashes=");
        sb.append(this.E1);
        sb.append(", openRomBrowserItemOptions=");
        sb.append(this.F1);
        sb.append(", openRomGameInfo=");
        sb.append(this.G1);
        sb.append(", forceTabMigrationKeySetter=");
        sb.append(this.H1);
        sb.append(", onRomCategoryContainerBoundsChanged=");
        sb.append(this.I1);
        sb.append(", onRomXmbReturnConsumed=");
        sb.append(this.J1);
        sb.append(", onRetroAchievementsLogin=");
        sb.append(this.K1);
        sb.append(", onRetroAchievementsLogout=");
        sb.append(this.L1);
        sb.append(", onRetroAchievementsRefresh=");
        sb.append(this.M1);
        sb.append(", onRetroAchievementsGameFocused=");
        sb.append(this.N1);
        rx1.C(sb, ", onRetroAchievementsMotionActiveChange=", this.O1, ", onRetroAchievementsGameActivated=", this.P1);
        rx1.C(sb, ", onRetroAchievementsAchievementFocused=", this.Q1, ", onRetroAchievementsAchievementActivated=", this.R1);
        rx1.x(this.S1, this.T1, ", onRetroAchievementsDismissGameDetails=", ", onRetroAchievementsRetryGameDetails=", sb);
        rx1.C(sb, ", onFriendGameSelected=", this.U1, ", onFriendPostSelected=", this.V1);
        sb.append(")");
        return sb.toString();
    }
}
