package defpackage;

import android.content.Context;
import java.util.Map;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class ih3 {
    public final ur2 A;
    public final ur2 B;
    public final wr2 C;
    public final ks2 D;
    public final ks2 E;
    public final ls2 F;
    public final ls2 G;
    public final ks2 H;
    public final ks2 I;
    public final ks2 J;
    public final ks2 K;
    public final ks2 L;
    public final ks2 M;
    public final wr2 N;
    public final wr2 O;
    public final wr2 P;
    public final ls2 Q;
    public final ls2 R;
    public final ks2 S;
    public final ks2 T;
    public final wr2 U;
    public final wr2 V;
    public final wr2 W;
    public final wr2 X;
    public final wr2 Y;
    public final ks2 Z;
    public final Context a;
    public final ks2 a0;
    public final lp3 b;
    public final ur2 b0;
    public final ze0 c;
    public final ur2 c0;
    public final bt2 d;
    public final wr2 d0;
    public final ft3 e;
    public final ur2 e0;
    public final oh3 f;
    public final y63 f0;
    public final dj3 g;
    public final x63 g0;
    public final ni3 h;
    public final x63 h0;
    public final kw3 i;
    public final x63 i0;
    public final um3 j;
    public final x63 j0;
    public final ww6 k;
    public final f63 k0;
    public final Map l;
    public final Map m;
    public final lc7 n;
    public final Map o;
    public final boolean p;
    public final boolean q;
    public final boolean r;
    public final boolean s;
    public final long t;
    public final String u;
    public final ur2 v;
    public final ur2 w;
    public final ur2 x;
    public final ur2 y;
    public final ur2 z;

    public ih3(Context context, lp3 lp3Var, ze0 ze0Var, bt2 bt2Var, ft3 ft3Var, oh3 oh3Var, dj3 dj3Var, ni3 ni3Var, kw3 kw3Var, um3 um3Var, ww6 ww6Var, Map map, Map map2, lc7 lc7Var, Map map3, boolean z, boolean z2, boolean z3, boolean z4, long j, String str, ur2 ur2Var, ur2 ur2Var2, ur2 ur2Var3, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, ur2 ur2Var7, wr2 wr2Var, ks2 ks2Var, ks2 ks2Var2, ls2 ls2Var, ls2 ls2Var2, ks2 ks2Var3, ks2 ks2Var4, ks2 ks2Var5, ks2 ks2Var6, ks2 ks2Var7, ks2 ks2Var8, wr2 wr2Var2, wr2 wr2Var3, wr2 wr2Var4, ls2 ls2Var3, ls2 ls2Var4, ks2 ks2Var9, ks2 ks2Var10, wr2 wr2Var5, wr2 wr2Var6, wr2 wr2Var7, wr2 wr2Var8, wr2 wr2Var9, ks2 ks2Var11, ks2 ks2Var12, ur2 ur2Var8, ur2 ur2Var9, wr2 wr2Var10, ur2 ur2Var10, y63 y63Var, x63 x63Var, x63 x63Var2, x63 x63Var3, x63 x63Var4, f63 f63Var) {
        ze0Var.getClass();
        bt2Var.getClass();
        kw3Var.getClass();
        um3Var.getClass();
        ww6Var.getClass();
        map.getClass();
        map2.getClass();
        lc7Var.getClass();
        map3.getClass();
        ur2Var.getClass();
        f33.q(ur2Var2, ur2Var3, ur2Var4, ur2Var5, ur2Var6);
        ur2Var7.getClass();
        wr2Var.getClass();
        ks2Var.getClass();
        ks2Var2.getClass();
        ls2Var.getClass();
        ls2Var2.getClass();
        ks2Var3.getClass();
        ks2Var4.getClass();
        ks2Var5.getClass();
        ks2Var6.getClass();
        ks2Var7.getClass();
        ks2Var8.getClass();
        wr2Var2.getClass();
        wr2Var3.getClass();
        wr2Var4.getClass();
        ls2Var3.getClass();
        ls2Var4.getClass();
        ks2Var9.getClass();
        ks2Var10.getClass();
        wr2Var5.getClass();
        wr2Var6.getClass();
        wr2Var7.getClass();
        wr2Var8.getClass();
        wr2Var9.getClass();
        ks2Var11.getClass();
        ks2Var12.getClass();
        ur2Var8.getClass();
        ur2Var9.getClass();
        wr2Var10.getClass();
        ur2Var10.getClass();
        this.a = context;
        this.b = lp3Var;
        this.c = ze0Var;
        this.d = bt2Var;
        this.e = ft3Var;
        this.f = oh3Var;
        this.g = dj3Var;
        this.h = ni3Var;
        this.i = kw3Var;
        this.j = um3Var;
        this.k = ww6Var;
        this.l = map;
        this.m = map2;
        this.n = lc7Var;
        this.o = map3;
        this.p = z;
        this.q = z2;
        this.r = z3;
        this.s = z4;
        this.t = j;
        this.u = str;
        this.v = ur2Var;
        this.w = ur2Var2;
        this.x = ur2Var3;
        this.y = ur2Var4;
        this.z = ur2Var5;
        this.A = ur2Var6;
        this.B = ur2Var7;
        this.C = wr2Var;
        this.D = ks2Var;
        this.E = ks2Var2;
        this.F = ls2Var;
        this.G = ls2Var2;
        this.H = ks2Var3;
        this.I = ks2Var4;
        this.J = ks2Var5;
        this.K = ks2Var6;
        this.L = ks2Var7;
        this.M = ks2Var8;
        this.N = wr2Var2;
        this.O = wr2Var3;
        this.P = wr2Var4;
        this.Q = ls2Var3;
        this.R = ls2Var4;
        this.S = ks2Var9;
        this.T = ks2Var10;
        this.U = wr2Var5;
        this.V = wr2Var6;
        this.W = wr2Var7;
        this.X = wr2Var8;
        this.Y = wr2Var9;
        this.Z = ks2Var11;
        this.a0 = ks2Var12;
        this.b0 = ur2Var8;
        this.c0 = ur2Var9;
        this.d0 = wr2Var10;
        this.e0 = ur2Var10;
        this.f0 = y63Var;
        this.g0 = x63Var;
        this.h0 = x63Var2;
        this.i0 = x63Var3;
        this.j0 = x63Var4;
        this.k0 = f63Var;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof ih3) {
            ih3 ih3Var = (ih3) obj;
            if (this.a.equals(ih3Var.a) && this.b == ih3Var.b && ye4.p(this.c, ih3Var.c) && ye4.p(this.d, ih3Var.d) && this.e == ih3Var.e && this.f == ih3Var.f && this.g == ih3Var.g && this.h == ih3Var.h && ye4.p(this.i, ih3Var.i) && ye4.p(this.j, ih3Var.j) && ye4.p(this.k, ih3Var.k) && ye4.p(this.l, ih3Var.l) && ye4.p(this.m, ih3Var.m) && ye4.p(this.n, ih3Var.n) && ye4.p(this.o, ih3Var.o) && this.p == ih3Var.p && this.q == ih3Var.q && this.r == ih3Var.r && this.s == ih3Var.s && this.t == ih3Var.t && ye4.p(this.u, ih3Var.u) && ye4.p(this.v, ih3Var.v) && ye4.p(this.w, ih3Var.w) && ye4.p(this.x, ih3Var.x) && ye4.p(this.y, ih3Var.y) && ye4.p(this.z, ih3Var.z) && ye4.p(this.A, ih3Var.A) && ye4.p(this.B, ih3Var.B) && ye4.p(this.C, ih3Var.C) && ye4.p(this.D, ih3Var.D) && ye4.p(this.E, ih3Var.E) && ye4.p(this.F, ih3Var.F) && ye4.p(this.G, ih3Var.G) && ye4.p(this.H, ih3Var.H) && ye4.p(this.I, ih3Var.I) && ye4.p(this.J, ih3Var.J) && ye4.p(this.K, ih3Var.K) && ye4.p(this.L, ih3Var.L) && ye4.p(this.M, ih3Var.M) && ye4.p(this.N, ih3Var.N) && ye4.p(this.O, ih3Var.O) && ye4.p(this.P, ih3Var.P) && ye4.p(this.Q, ih3Var.Q) && ye4.p(this.R, ih3Var.R) && ye4.p(this.S, ih3Var.S) && ye4.p(this.T, ih3Var.T) && ye4.p(this.U, ih3Var.U) && ye4.p(this.V, ih3Var.V) && ye4.p(this.W, ih3Var.W) && ye4.p(this.X, ih3Var.X) && ye4.p(this.Y, ih3Var.Y) && ye4.p(this.Z, ih3Var.Z) && ye4.p(this.a0, ih3Var.a0) && ye4.p(this.b0, ih3Var.b0) && ye4.p(this.c0, ih3Var.c0) && ye4.p(this.d0, ih3Var.d0) && ye4.p(this.e0, ih3Var.e0) && this.f0.equals(ih3Var.f0) && this.g0.equals(ih3Var.g0) && this.h0.equals(ih3Var.h0) && this.i0.equals(ih3Var.i0) && this.j0.equals(ih3Var.j0) && this.k0.equals(ih3Var.k0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int iD = j55.d(this.t, a68.d(a68.d(a68.d(a68.d(a68.f(this.o, rx1.j(this.n, a68.f(this.m, a68.f(this.l, f33.c(this.k, (this.j.hashCode() + ((this.i.hashCode() + ((this.h.hashCode() + f33.b(this.g, (this.f.hashCode() + rx1.i(this.e, (this.d.hashCode() + rx1.e(this.c, rx1.h(this.b, this.a.hashCode() * 31, 31), 31)) * 31, 31)) * 31, 31)) * 31)) * 31)) * 31, 31), 31), 31), 31), 31), 31, this.p), 31, this.q), 31, this.r), 31, this.s), 31);
        String str = this.u;
        return this.k0.hashCode() + ((this.j0.hashCode() + ((this.i0.hashCode() + ((this.h0.hashCode() + ((this.g0.hashCode() + ((this.f0.hashCode() + rx1.f(this.e0, pk0.b(rx1.f(this.c0, rx1.f(this.b0, rx1.d(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(rx1.g(this.R, rx1.g(this.Q, pk0.b(pk0.b(pk0.b(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.g(this.G, rx1.g(this.F, rx1.d(rx1.d(pk0.b(rx1.f(this.B, rx1.f(this.A, rx1.f(this.z, rx1.f(this.y, rx1.f(this.x, rx1.f(this.w, rx1.f(this.v, (iD + (str == null ? 0 : str.hashCode())) * 31, 31), 31), 31), 31), 31), 31), 31), this.C, 31), 31, this.D), 31, this.E), 31), 31), 31, this.H), 31, this.I), 31, this.J), 31, this.K), 31, this.L), 31, this.M), this.N, 31), this.O, 31), this.P, 31), 31), 31), 31, this.S), 31, this.T), this.U, 31), this.V, 31), this.W, 31), this.X, 31), this.Y, 31), 31, this.Z), 31, this.a0), 31), 31), this.d0, 31), 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomeQuickAccessContextItemsDeps(stableContext=");
        sb.append(this.a);
        sb.append(", runtimeState=");
        sb.append(this.b);
        sb.append(", browserState=");
        sb.append(this.c);
        sb.append(", selectionState=");
        sb.append(this.d);
        sb.append(", callbacks=");
        sb.append(this.e);
        sb.append(", quickAccessGridValidationController=");
        sb.append(this.f);
        sb.append(", quickAccessWidgetState=");
        sb.append(this.g);
        sb.append(", quickAccessWidgetActions=");
        sb.append(this.h);
        sb.append(", taskScraperOperations=");
        sb.append(this.i);
        sb.append(", scraperTaskCoordinator=");
        sb.append(this.j);
        sb.append(", retroAchievementsState=");
        sb.append(this.k);
        sb.append(", retroHashesByRomId=");
        sb.append(this.l);
        sb.append(", retroAchievementGameIdsForRoms=");
        sb.append(this.m);
        sb.append(", scraperState=");
        sb.append(this.n);
        sb.append(", tabLabelById=");
        sb.append(this.o);
        sb.append(", allowEditing=");
        sb.append(this.p);
        sb.append(", isCollectionPopupOpen=");
        a68.u(", isExternalDisplay=", ", hasSteamGridDbApiKey=", sb, this.q, this.r);
        sb.append(this.s);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.t);
        sb.append(", emptyLabel=");
        sb.append(this.u);
        sb.append(", clearSelectionAction=");
        sb.append(this.v);
        rx1.x(this.w, this.x, ", clearTopLevelMenuIfVisible=", ", persistUiSessionNow=", sb);
        rx1.x(this.y, this.z, ", bumpQuickAccessFocusSignal=", ", onDismiss=", sb);
        rx1.x(this.A, this.B, ", onIncreaseQuickAccessDensity=", ", onDecreaseQuickAccessDensity=", sb);
        sb.append(", onSetMinimalModeEnabled=");
        sb.append(this.C);
        sb.append(", onToggleAppShortcut=");
        sb.append(this.D);
        sb.append(", onToggleRomShortcut=");
        sb.append(this.E);
        sb.append(", onUpdateAppLinkedPreference=");
        sb.append(this.F);
        sb.append(", onUpdateRomLinkedPreference=");
        sb.append(this.G);
        sb.append(", onUpdateAppLaunchPreference=");
        sb.append(this.H);
        f33.w(sb, ", onUpdateRomLaunchPreference=", this.I, ", onSetRomTitleSectionMode=", this.J);
        f33.w(sb, ", onSetRomTrophyIconCorner=", this.K, ", onSetRomTrophyIconAlpha=", this.L);
        sb.append(", onSetRomCustomName=");
        sb.append(this.M);
        sb.append(", onCreateCollection=");
        sb.append(this.N);
        rx1.C(sb, ", onDeleteCollection=", this.O, ", onSetCollectionByNameRows=", this.P);
        sb.append(", onSetCollectionColumns=");
        sb.append(this.Q);
        sb.append(", onSetRomInCollection=");
        sb.append(this.R);
        f33.w(sb, ", onManageCollectionMedia=", this.S, ", onDeleteCollectionMedia=", this.T);
        rx1.C(sb, ", onManageAppQuickAccessIcon=", this.U, ", onManageRomQuickAccessIcon=", this.V);
        rx1.C(sb, ", onDeleteAppQuickAccessIcon=", this.W, ", onDeleteRomQuickAccessIcon=", this.X);
        sb.append(", requestHomeLayoutImport=");
        sb.append(this.Y);
        sb.append(", requestHomeLayoutExport=");
        sb.append(this.Z);
        sb.append(", onScrapeSelectedHomeIcon=");
        sb.append(this.a0);
        sb.append(", onScrapeAllHomeIcons=");
        sb.append(this.b0);
        sb.append(", onRefreshHome=");
        sb.append(this.c0);
        sb.append(", onRetroAchievementsRomFocused=");
        sb.append(this.d0);
        sb.append(", onRetroAchievementsShowDetails=");
        sb.append(this.e0);
        sb.append(", buildBackgroundTaskDetailItems=");
        sb.append(this.f0);
        sb.append(", canContinueBackgroundTask=");
        sb.append(this.g0);
        sb.append(", canCancelBackgroundTask=");
        sb.append(this.h0);
        sb.append(", onContinueBackgroundTask=");
        sb.append(this.i0);
        sb.append(", onCancelBackgroundTask=");
        sb.append(this.j0);
        sb.append(", onShowBackgroundTaskUnavailable=");
        sb.append(this.k0);
        sb.append(")");
        return sb.toString();
    }
}
