package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class jn {
    public final f63 A;
    public final f63 B;
    public final b33 C;
    public final b33 D;
    public final b33 E;
    public final b33 F;
    public final b33 G;
    public final b33 H;
    public final b33 I;
    public final b33 J;
    public final b33 K;
    public final b33 L;
    public final b33 M;
    public final ob0 N;
    public final b33 O;
    public final u63 P;
    public final b33 Q;
    public final u63 R;
    public final x S;
    public final u63 T;
    public final b33 U;
    public final u63 V;
    public final wr2 W;
    public final ob0 X;
    public final r83 Y;
    public final a73 Z;
    public final ks2 a;
    public final ob0 a0;
    public final a73 b;
    public final b33 b0;
    public final ur2 c;
    public final b33 c0;
    public final v63 d;
    public final long d0;
    public final w63 e;
    public final y63 e0;
    public final a33 f;
    public final b33 f0;
    public final a33 g;
    public final b33 g0;
    public final y63 h;
    public final b33 h0;
    public final ls2 i;
    public final x63 i0;
    public final ks2 j;
    public final f63 j0;
    public final ks2 k;
    public final ur2 k0;
    public final ks2 l;
    public final g43 l0;
    public final ls2 m;
    public final f63 m0;
    public final ks2 n;
    public final ur2 n0;
    public final ob0 o;
    public final f63 o0;
    public final ob0 p;
    public final f63 p0;
    public final ob0 q;
    public final ob0 r;
    public final a33 s;
    public final ob0 t;
    public final a33 u;
    public final a73 v;
    public final a73 w;
    public final e93 x;
    public final iw3 y;
    public final f63 z;

    public jn(ks2 ks2Var, a73 a73Var, ur2 ur2Var, v63 v63Var, w63 w63Var, a33 a33Var, a33 a33Var2, y63 y63Var, ls2 ls2Var, ks2 ks2Var2, ks2 ks2Var3, ks2 ks2Var4, ls2 ls2Var2, ks2 ks2Var5, ob0 ob0Var, ob0 ob0Var2, ob0 ob0Var3, ob0 ob0Var4, a33 a33Var3, ob0 ob0Var5, a33 a33Var4, a73 a73Var2, a73 a73Var3, e93 e93Var, iw3 iw3Var, f63 f63Var, f63 f63Var2, f63 f63Var3, b33 b33Var, b33 b33Var2, b33 b33Var3, b33 b33Var4, b33 b33Var5, b33 b33Var6, b33 b33Var7, b33 b33Var8, b33 b33Var9, b33 b33Var10, b33 b33Var11, ob0 ob0Var6, b33 b33Var12, u63 u63Var, b33 b33Var13, u63 u63Var2, x xVar, u63 u63Var3, b33 b33Var14, u63 u63Var4, wr2 wr2Var, ob0 ob0Var7, r83 r83Var, a73 a73Var4, ob0 ob0Var8, b33 b33Var15, b33 b33Var16, long j, y63 y63Var2, b33 b33Var17, b33 b33Var18, b33 b33Var19, x63 x63Var, f63 f63Var4, ur2 ur2Var2, g43 g43Var, f63 f63Var5, ur2 ur2Var3, f63 f63Var6, f63 f63Var7) {
        ks2Var.getClass();
        ur2Var.getClass();
        ls2Var.getClass();
        ks2Var2.getClass();
        ks2Var3.getClass();
        ks2Var4.getClass();
        ls2Var2.getClass();
        ks2Var5.getClass();
        wr2Var.getClass();
        ur2Var3.getClass();
        this.a = ks2Var;
        this.b = a73Var;
        this.c = ur2Var;
        this.d = v63Var;
        this.e = w63Var;
        this.f = a33Var;
        this.g = a33Var2;
        this.h = y63Var;
        this.i = ls2Var;
        this.j = ks2Var2;
        this.k = ks2Var3;
        this.l = ks2Var4;
        this.m = ls2Var2;
        this.n = ks2Var5;
        this.o = ob0Var;
        this.p = ob0Var2;
        this.q = ob0Var3;
        this.r = ob0Var4;
        this.s = a33Var3;
        this.t = ob0Var5;
        this.u = a33Var4;
        this.v = a73Var2;
        this.w = a73Var3;
        this.x = e93Var;
        this.y = iw3Var;
        this.z = f63Var;
        this.A = f63Var2;
        this.B = f63Var3;
        this.C = b33Var;
        this.D = b33Var2;
        this.E = b33Var3;
        this.F = b33Var4;
        this.G = b33Var5;
        this.H = b33Var6;
        this.I = b33Var7;
        this.J = b33Var8;
        this.K = b33Var9;
        this.L = b33Var10;
        this.M = b33Var11;
        this.N = ob0Var6;
        this.O = b33Var12;
        this.P = u63Var;
        this.Q = b33Var13;
        this.R = u63Var2;
        this.S = xVar;
        this.T = u63Var3;
        this.U = b33Var14;
        this.V = u63Var4;
        this.W = wr2Var;
        this.X = ob0Var7;
        this.Y = r83Var;
        this.Z = a73Var4;
        this.a0 = ob0Var8;
        this.b0 = b33Var15;
        this.c0 = b33Var16;
        this.d0 = j;
        this.e0 = y63Var2;
        this.f0 = b33Var17;
        this.g0 = b33Var18;
        this.h0 = b33Var19;
        this.i0 = x63Var;
        this.j0 = f63Var4;
        this.k0 = ur2Var2;
        this.l0 = g43Var;
        this.m0 = f63Var5;
        this.n0 = ur2Var3;
        this.o0 = f63Var6;
        this.p0 = f63Var7;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof jn) {
            jn jnVar = (jn) obj;
            if (ye4.p(this.a, jnVar.a) && this.b.equals(jnVar.b) && ye4.p(this.c, jnVar.c) && this.d.equals(jnVar.d) && this.e.equals(jnVar.e) && this.f.equals(jnVar.f) && this.g.equals(jnVar.g) && this.h.equals(jnVar.h) && ye4.p(this.i, jnVar.i) && ye4.p(this.j, jnVar.j) && ye4.p(this.k, jnVar.k) && ye4.p(this.l, jnVar.l) && ye4.p(this.m, jnVar.m) && ye4.p(this.n, jnVar.n) && this.o.equals(jnVar.o) && this.p.equals(jnVar.p) && this.q.equals(jnVar.q) && this.r.equals(jnVar.r) && this.s.equals(jnVar.s) && this.t.equals(jnVar.t) && this.u.equals(jnVar.u) && this.v.equals(jnVar.v) && this.w.equals(jnVar.w) && this.x.equals(jnVar.x) && this.y == jnVar.y && this.z.equals(jnVar.z) && this.A.equals(jnVar.A) && this.B.equals(jnVar.B) && this.C.equals(jnVar.C) && this.D.equals(jnVar.D) && this.E.equals(jnVar.E) && this.F.equals(jnVar.F) && this.G.equals(jnVar.G) && this.H.equals(jnVar.H) && this.I.equals(jnVar.I) && this.J.equals(jnVar.J) && this.K.equals(jnVar.K) && this.L.equals(jnVar.L) && this.M.equals(jnVar.M) && this.N.equals(jnVar.N) && this.O.equals(jnVar.O) && this.P == jnVar.P && this.Q.equals(jnVar.Q) && this.R == jnVar.R && this.S == jnVar.S && this.T == jnVar.T && this.U.equals(jnVar.U) && this.V == jnVar.V && ye4.p(this.W, jnVar.W) && this.X.equals(jnVar.X) && this.Y == jnVar.Y && this.Z.equals(jnVar.Z) && this.a0.equals(jnVar.a0) && this.b0.equals(jnVar.b0) && this.c0.equals(jnVar.c0) && this.d0 == jnVar.d0 && this.e0.equals(jnVar.e0) && this.f0.equals(jnVar.f0) && this.g0.equals(jnVar.g0) && this.h0.equals(jnVar.h0) && this.i0.equals(jnVar.i0) && this.j0.equals(jnVar.j0) && this.k0.equals(jnVar.k0) && this.l0 == jnVar.l0 && this.m0.equals(jnVar.m0) && ye4.p(this.n0, jnVar.n0) && this.o0.equals(jnVar.o0) && this.p0.equals(jnVar.p0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        return this.p0.hashCode() + ((this.o0.hashCode() + rx1.f(this.n0, (this.m0.hashCode() + ((this.l0.hashCode() + rx1.f(this.k0, (this.j0.hashCode() + ((this.i0.hashCode() + ((this.h0.hashCode() + ((this.g0.hashCode() + ((this.f0.hashCode() + ((this.e0.hashCode() + j55.d(this.d0, (this.c0.hashCode() + ((this.b0.hashCode() + ((this.a0.hashCode() + ((this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + pk0.b((this.V.hashCode() + ((this.U.hashCode() + ((this.T.hashCode() + ((this.S.hashCode() + ((this.R.hashCode() + ((this.Q.hashCode() + ((this.P.hashCode() + ((this.O.hashCode() + ((this.N.hashCode() + ((this.M.hashCode() + ((this.L.hashCode() + ((this.K.hashCode() + ((this.J.hashCode() + ((this.I.hashCode() + ((this.H.hashCode() + ((this.G.hashCode() + ((this.F.hashCode() + ((this.E.hashCode() + ((this.D.hashCode() + ((this.C.hashCode() + ((this.B.hashCode() + ((this.A.hashCode() + ((this.z.hashCode() + ((this.y.hashCode() + ((this.x.hashCode() + ((this.w.hashCode() + ((this.v.hashCode() + ((this.u.hashCode() + ((this.t.hashCode() + ((this.s.hashCode() + ((this.r.hashCode() + ((this.q.hashCode() + ((this.p.hashCode() + ((this.o.hashCode() + rx1.d(rx1.g(this.m, rx1.d(rx1.d(rx1.d(rx1.g(this.i, (this.h.hashCode() + ((this.g.hashCode() + ((this.f.hashCode() + ((this.e.hashCode() + ((this.d.hashCode() + rx1.f(this.c, (this.b.hashCode() + (this.a.hashCode() * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), 31, this.j), 31, this.k), 31, this.l), 31), 31, this.n)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, this.W, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31)) * 31, 31)) * 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("AppMenuHostCallbacks(onToggleAppShortcut=");
        sb.append(this.a);
        sb.append(", onApplySearch=");
        sb.append(this.b);
        sb.append(", onOpenGlobalSearch=");
        sb.append(this.c);
        sb.append(", onScrapeApp=");
        sb.append(this.d);
        sb.append(", onScrapeAppWithMode=");
        sb.append(this.e);
        sb.append(", onScrapeAppCustom=");
        sb.append(this.f);
        sb.append(", onScrapeCategoryMedia=");
        sb.append(this.g);
        sb.append(", onScrapeSelectedHomeIcon=");
        sb.append(this.h);
        sb.append(", onUpdateAppLinkedPreference=");
        sb.append(this.i);
        sb.append(", onUpdateAppLaunchPreference=");
        sb.append(this.j);
        sb.append(", onUpdateAppClassification=");
        f33.v(sb, this.k, ", onSetAppCustomName=", this.l, ", onSetRomInCollection=");
        sb.append(this.m);
        sb.append(", onToggleAppVisibility=");
        sb.append(this.n);
        sb.append(", onManageCategoryMedia=");
        sb.append(this.o);
        sb.append(", onResetCategoryMedia=");
        sb.append(this.p);
        sb.append(", onDeleteCategoryAppsMedia=");
        sb.append(this.q);
        sb.append(", onManageAppMedia=");
        sb.append(this.r);
        sb.append(", onManageAppMediaAtIndex=");
        sb.append(this.s);
        sb.append(", onDeleteAppMedia=");
        sb.append(this.t);
        sb.append(", onDeleteAppMediaAtIndex=");
        sb.append(this.u);
        sb.append(", onManageAppQuickAccessIcon=");
        sb.append(this.v);
        sb.append(", onDeleteAppQuickAccessIcon=");
        sb.append(this.w);
        sb.append(", onRefreshCategoryMetadata=");
        sb.append(this.x);
        sb.append(", onChangeCategoryLayout=");
        sb.append(this.y);
        sb.append(", onToggleEditMode=");
        sb.append(this.z);
        sb.append(", onIncreaseDensity=");
        sb.append(this.A);
        sb.append(", onDecreaseDensity=");
        sb.append(this.B);
        sb.append(", onSetCategoryGridRows=");
        sb.append(this.C);
        sb.append(", onSetCategoryGridColumns=");
        sb.append(this.D);
        sb.append(", onSetCategoryListRows=");
        sb.append(this.E);
        sb.append(", onSetCategoryXmbIconSizeLevel=");
        sb.append(this.F);
        sb.append(", onSetBrowserGridRows=");
        sb.append(this.G);
        sb.append(", onSetBrowserGridColumns=");
        sb.append(this.H);
        sb.append(", onSetBrowserCompactRows=");
        sb.append(this.I);
        sb.append(", onSetBrowserHorizontalIconSizeLevel=");
        sb.append(this.J);
        sb.append(", onSetBrowserVerticalNeighbors=");
        sb.append(this.K);
        sb.append(", onSetBrowserXmbIconSizeLevel=");
        sb.append(this.L);
        sb.append(", onSetAppXmbHorizontalPath=");
        sb.append(this.M);
        sb.append(", onSetHorizontalGridEnabled=");
        sb.append(this.N);
        sb.append(", onSetHorizontalGridOverrideEnabled=");
        sb.append(this.O);
        sb.append(", isMinimalModeEnabled=");
        sb.append(this.P);
        sb.append(", onSetMinimalModeEnabled=");
        sb.append(this.Q);
        sb.append(", isPersistentNavBarOnApps=");
        sb.append(this.R);
        sb.append(", onSetPersistentNavBarOnApps=");
        sb.append(this.S);
        sb.append(", appBrowserIconBorderStyle=");
        sb.append(this.T);
        sb.append(", onSetAppBrowserIconBorderStyle=");
        sb.append(this.U);
        sb.append(", isHideAndroidGamesOnConsolesPageEnabled=");
        sb.append(this.V);
        sb.append(", onSetHideAndroidGamesOnConsolesPageEnabled=");
        sb.append(this.W);
        sb.append(", onChangeLayout=");
        sb.append(this.X);
        sb.append(", isScraperSourceConfigured=");
        sb.append(this.Y);
        sb.append(", onConfigureScraperSource=");
        sb.append(this.Z);
        sb.append(", onShowScraperSelectionMenu=");
        sb.append(this.a0);
        sb.append(", onShowScraperProgressMenu=");
        sb.append(this.b0);
        sb.append(", setScraperContextMenuPinned=");
        sb.append(this.c0);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.d0);
        sb.append(", buildBackgroundTaskDetailItems=");
        sb.append(this.e0);
        sb.append(", canContinueBackgroundTask=");
        sb.append(this.f0);
        sb.append(", canCancelBackgroundTask=");
        sb.append(this.g0);
        sb.append(", onContinueBackgroundTask=");
        sb.append(this.h0);
        sb.append(", onCancelBackgroundTask=");
        sb.append(this.i0);
        sb.append(", onShowBackgroundTaskUnavailable=");
        sb.append(this.j0);
        sb.append(", onDismiss=");
        sb.append(this.k0);
        sb.append(", onDismissStart=");
        sb.append(this.l0);
        sb.append(", onShowIisuSettings=");
        sb.append(this.m0);
        sb.append(", onShowDiscord=");
        sb.append(this.n0);
        sb.append(", onShowThorSettings=");
        sb.append(this.o0);
        sb.append(", onFocusRecovery=");
        sb.append(this.p0);
        sb.append(")");
        return sb.toString();
    }
}
