package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public abstract class kt0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = tz5.x;
        a = j2;
        b = tz5.e;
        c = tz5.g;
        d = tz5.v;
        long j3 = tz5.H;
        e = j3;
        f = tz5.m;
        long j4 = tz5.i;
        g = j4;
        h = tz5.b;
        i = tz5.a;
        j = tz5.E;
        long j5 = tz5.D;
        k = j5;
        l = j5;
        m = tz5.F;
        n = tz5.K;
        long j6 = tz5.J;
        o = j6;
        p = j6;
        q = tz5.M;
        r = j4;
        s = tz5.y;
        t = tz5.R;
        long j7 = tz5.Q;
        u = j7;
        v = j7;
        w = tz5.T;
        x = tz5.z;
        y = tz5.B;
        z = tz5.G;
        long j8 = tz5.I;
        A = j8;
        B = j8;
        C = j3;
        D = tz5.h;
        E = tz5.N;
        long j9 = tz5.P;
        F = j9;
        G = j9;
        H = tz5.O;
        I = j2;
        J = j2;
        K = tz5.u;
        L = tz5.t;
        M = tz5.s;
        N = tz5.w;
        O = tz5.j;
        P = tz5.r;
        Q = tz5.C;
        R = tz5.U;
        long j10 = tz5.W;
        S = j10;
        T = j10;
        U = tz5.V;
    }
}
