package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class m64 {
    public final ur2 A;
    public final lo3 A0;
    public final wr2 A1;
    public final ur2 A2;
    public final ko3 B;
    public final lo3 B0;
    public final wr2 B1;
    public final wr2 B2;
    public final ko3 C;
    public final lo3 C0;
    public final ur2 C1;
    public final wr2 C2;
    public final ko3 D;
    public final sn3 D0;
    public final ur2 D1;
    public final ls2 D2;
    public final zn3 E;
    public final sn3 E0;
    public final ur2 E1;
    public final ur2 E2;
    public final mo3 F;
    public final tn3 F0;
    public final ur2 F1;
    public final ur2 F2;
    public final mo3 G;
    public final sn3 G0;
    public final wr2 G1;
    public final wr2 G2;
    public final z31 H;
    public final sn3 H0;
    public final wr2 H1;
    public final ur2 H2;
    public final no3 I;
    public final sn3 I0;
    public final wr2 I1;
    public final ks2 I2;
    public final no3 J;
    public final sn3 J0;
    public final wr2 J1;
    public final ur2 J2;
    public final oo3 K;
    public final sn3 K0;
    public final wr2 K1;
    public final ur2 K2;
    public final mo3 L;
    public final sn3 L0;
    public final ks2 L1;
    public final ur2 L2;
    public final ko3 M;
    public final sn3 M0;
    public final ur2 M1;
    public final ur2 M2;
    public final zn3 N;
    public final sn3 N0;
    public final wr2 N1;
    public final ur2 N2;
    public final lo3 O;
    public final tn3 O0;
    public final wr2 O1;
    public final ur2 O2;
    public final ko3 P;
    public final sn3 P0;
    public final wr2 P1;
    public final ur2 P2;
    public final zn3 Q;
    public final vn3 Q0;
    public final lo3 Q1;
    public final ur2 Q2;
    public final mo3 R;
    public final vn3 R0;
    public final lo3 R1;
    public final ur2 R2;
    public final wr2 S;
    public final sn3 S0;
    public final lo3 S1;
    public final ur2 S2;
    public final wr2 T;
    public final sn3 T0;
    public final lo3 T1;
    public final fo3 T2;
    public final wr2 U;
    public final sn3 U0;
    public final sn3 U1;
    public final ur2 U2;
    public final wr2 V;
    public final sn3 V0;
    public final sn3 V1;
    public final ur2 V2;
    public final wr2 W;
    public final wn3 W0;
    public final tn3 W1;
    public final ur2 W2;
    public final lo3 X;
    public final sn3 X0;
    public final sn3 X1;
    public final ur2 X2;
    public final q74 Y;
    public final wn3 Y0;
    public final tn3 Y1;
    public final fo3 Y2;
    public final wr2 Z;
    public final sn3 Z0;
    public final sn3 Z1;
    public final ur2 Z2;
    public final wr2 a;
    public final wr2 a0;
    public final eg3 a1;
    public final sn3 a2;
    public final ur2 a3;
    public final wr2 b;
    public final wr2 b0;
    public final t40 b1;
    public final ur2 b2;
    public final ur2 b3;
    public final lo3 c;
    public final wr2 c0;
    public final p7 c1;
    public final bo3 c2;
    public final ur2 c3;
    public final wr2 d;
    public final lo3 d0;
    public final q7 d1;
    public final do3 d2;
    public final ur2 d3;
    public final wr2 e;
    public final lo3 e0;
    public final xn3 e1;
    public final do3 e2;
    public final ur2 e3;
    public final wr2 f;
    public final lo3 f0;
    public final wr2 f1;
    public final do3 f2;
    public final ur2 f3;
    public final wr2 g;
    public final lo3 g0;
    public final yn3 g1;
    public final do3 g2;
    public final ur2 g3;
    public final lo3 h;
    public final lo3 h0;
    public final t40 h1;
    public final eo3 h2;
    public final fo3 h3;
    public final lo3 i;
    public final lo3 i0;
    public final yn3 i1;
    public final eo3 i2;
    public final ur2 i3;
    public final lo3 j;
    public final lo3 j0;
    public final xn3 j1;
    public final ur2 j2;
    public final ur2 j3;
    public final lo3 k;
    public final lo3 k0;
    public final xn3 k1;
    public final ur2 k2;
    public final go3 k3;
    public final un3 l;
    public final lo3 l0;
    public final xn3 l1;
    public final ur2 l2;
    public final ho3 l3;
    public final un3 m;
    public final tn3 m0;
    public final zn3 m1;
    public final ur2 m2;
    public final ur2 m3;
    public final un3 n;
    public final lo3 n0;
    public final bl3 n1;
    public final ur2 n2;
    public final zn3 n3;
    public final un3 o;
    public final tn3 o0;
    public final u5 o1;
    public final ur2 o2;
    public final eo3 o3;
    public final un3 p;
    public final lo3 p0;
    public final xm0 p1;
    public final ur2 p2;
    public final sn3 p3;
    public final un3 q;
    public final kk q0;
    public final sn3 q1;
    public final ur2 q2;
    public final sn3 q3;
    public final wr2 r;
    public final lo3 r0;
    public final do7 r1;
    public final ur2 r2;
    public final sn3 r3;
    public final wr2 s;
    public final lo3 s0;
    public final wr2 s1;
    public final ur2 s2;
    public final io3 s3;
    public final sn3 t;
    public final fd0 t0;
    public final wr2 t1;
    public final eo3 t2;
    public final io3 t3;
    public final io3 u;
    public final p7 u0;
    public final ur2 u1;
    public final od3 u2;
    public final io3 u3;
    public final u5 v;
    public final tn3 v0;
    public final eo3 v1;
    public final wr2 v2;
    public final sn3 v3;
    public final io3 w;
    public final lo3 w0;
    public final eo3 w1;
    public final ur2 w2;
    public final sn3 w3;
    public final jo3 x;
    public final tn3 x0;
    public final eo3 x1;
    public final tn3 x2;
    public final sn3 x3;
    public final jo3 y;
    public final u5 y0;
    public final wr2 y1;
    public final eo3 y2;
    public final ur2 z;
    public final lo3 z0;
    public final wr2 z1;
    public final ur2 z2;

    public m64(wr2 wr2Var, wr2 wr2Var2, lo3 lo3Var, wr2 wr2Var3, wr2 wr2Var4, wr2 wr2Var5, wr2 wr2Var6, lo3 lo3Var2, lo3 lo3Var3, lo3 lo3Var4, lo3 lo3Var5, un3 un3Var, un3 un3Var2, un3 un3Var3, un3 un3Var4, un3 un3Var5, un3 un3Var6, wr2 wr2Var7, wr2 wr2Var8, sn3 sn3Var, io3 io3Var, u5 u5Var, io3 io3Var2, jo3 jo3Var, jo3 jo3Var2, ur2 ur2Var, ur2 ur2Var2, ko3 ko3Var, ko3 ko3Var2, ko3 ko3Var3, zn3 zn3Var, mo3 mo3Var, mo3 mo3Var2, z31 z31Var, no3 no3Var, no3 no3Var2, oo3 oo3Var, mo3 mo3Var3, ko3 ko3Var4, zn3 zn3Var2, lo3 lo3Var6, ko3 ko3Var5, zn3 zn3Var3, mo3 mo3Var4, wr2 wr2Var9, wr2 wr2Var10, wr2 wr2Var11, wr2 wr2Var12, wr2 wr2Var13, lo3 lo3Var7, q74 q74Var, wr2 wr2Var14, wr2 wr2Var15, wr2 wr2Var16, wr2 wr2Var17, lo3 lo3Var8, lo3 lo3Var9, lo3 lo3Var10, lo3 lo3Var11, lo3 lo3Var12, lo3 lo3Var13, lo3 lo3Var14, lo3 lo3Var15, lo3 lo3Var16, tn3 tn3Var, lo3 lo3Var17, tn3 tn3Var2, lo3 lo3Var18, kk kkVar, lo3 lo3Var19, lo3 lo3Var20, fd0 fd0Var, p7 p7Var, tn3 tn3Var3, lo3 lo3Var21, tn3 tn3Var4, u5 u5Var2, lo3 lo3Var22, lo3 lo3Var23, lo3 lo3Var24, lo3 lo3Var25, sn3 sn3Var2, sn3 sn3Var3, tn3 tn3Var5, sn3 sn3Var4, sn3 sn3Var5, sn3 sn3Var6, sn3 sn3Var7, sn3 sn3Var8, sn3 sn3Var9, sn3 sn3Var10, sn3 sn3Var11, tn3 tn3Var6, sn3 sn3Var12, vn3 vn3Var, vn3 vn3Var2, sn3 sn3Var13, sn3 sn3Var14, sn3 sn3Var15, sn3 sn3Var16, wn3 wn3Var, sn3 sn3Var17, wn3 wn3Var2, sn3 sn3Var18, eg3 eg3Var, t40 t40Var, p7 p7Var2, q7 q7Var, xn3 xn3Var, wr2 wr2Var18, yn3 yn3Var, t40 t40Var2, yn3 yn3Var2, xn3 xn3Var2, xn3 xn3Var3, xn3 xn3Var4, zn3 zn3Var4, bl3 bl3Var, u5 u5Var3, xm0 xm0Var, sn3 sn3Var19, do7 do7Var, wr2 wr2Var19, wr2 wr2Var20, ur2 ur2Var3, eo3 eo3Var, eo3 eo3Var2, eo3 eo3Var3, wr2 wr2Var21, wr2 wr2Var22, wr2 wr2Var23, wr2 wr2Var24, ur2 ur2Var4, ur2 ur2Var5, ur2 ur2Var6, ur2 ur2Var7, wr2 wr2Var25, wr2 wr2Var26, wr2 wr2Var27, wr2 wr2Var28, wr2 wr2Var29, ks2 ks2Var, ur2 ur2Var8, wr2 wr2Var30, wr2 wr2Var31, wr2 wr2Var32, lo3 lo3Var26, lo3 lo3Var27, lo3 lo3Var28, lo3 lo3Var29, sn3 sn3Var20, sn3 sn3Var21, tn3 tn3Var7, sn3 sn3Var22, tn3 tn3Var8, sn3 sn3Var23, sn3 sn3Var24, ur2 ur2Var9, bo3 bo3Var, do3 do3Var, do3 do3Var2, do3 do3Var3, do3 do3Var4, eo3 eo3Var4, eo3 eo3Var5, ur2 ur2Var10, ur2 ur2Var11, ur2 ur2Var12, ur2 ur2Var13, ur2 ur2Var14, ur2 ur2Var15, ur2 ur2Var16, ur2 ur2Var17, ur2 ur2Var18, ur2 ur2Var19, eo3 eo3Var6, od3 od3Var, wr2 wr2Var33, ur2 ur2Var20, tn3 tn3Var9, eo3 eo3Var7, ur2 ur2Var21, ur2 ur2Var22, wr2 wr2Var34, wr2 wr2Var35, ls2 ls2Var, ur2 ur2Var23, ur2 ur2Var24, wr2 wr2Var36, ur2 ur2Var25, ks2 ks2Var2, ur2 ur2Var26, ur2 ur2Var27, ur2 ur2Var28, ur2 ur2Var29, ur2 ur2Var30, ur2 ur2Var31, ur2 ur2Var32, ur2 ur2Var33, ur2 ur2Var34, ur2 ur2Var35, fo3 fo3Var, ur2 ur2Var36, ur2 ur2Var37, ur2 ur2Var38, ur2 ur2Var39, fo3 fo3Var2, ur2 ur2Var40, ur2 ur2Var41, ur2 ur2Var42, ur2 ur2Var43, ur2 ur2Var44, ur2 ur2Var45, ur2 ur2Var46, ur2 ur2Var47, fo3 fo3Var3, ur2 ur2Var48, ur2 ur2Var49, go3 go3Var, ho3 ho3Var, ur2 ur2Var50, zn3 zn3Var5, eo3 eo3Var8, sn3 sn3Var25, sn3 sn3Var26, sn3 sn3Var27, io3 io3Var3, io3 io3Var4, io3 io3Var5, sn3 sn3Var28, sn3 sn3Var29, sn3 sn3Var30) {
        f33.r(wr2Var, wr2Var2, wr2Var3, wr2Var4, wr2Var5);
        wr2Var6.getClass();
        wr2Var7.getClass();
        wr2Var8.getClass();
        ur2Var.getClass();
        ur2Var2.getClass();
        f33.r(wr2Var9, wr2Var10, wr2Var11, wr2Var12, wr2Var13);
        f33.r(wr2Var14, wr2Var15, wr2Var16, wr2Var17, wr2Var18);
        wr2Var19.getClass();
        wr2Var20.getClass();
        ur2Var3.getClass();
        wr2Var21.getClass();
        wr2Var22.getClass();
        wr2Var23.getClass();
        wr2Var24.getClass();
        ur2Var4.getClass();
        ur2Var5.getClass();
        ur2Var6.getClass();
        ur2Var7.getClass();
        wr2Var25.getClass();
        wr2Var26.getClass();
        wr2Var27.getClass();
        wr2Var28.getClass();
        wr2Var29.getClass();
        ks2Var.getClass();
        ur2Var8.getClass();
        wr2Var30.getClass();
        wr2Var31.getClass();
        wr2Var32.getClass();
        ur2Var9.getClass();
        ur2Var10.getClass();
        ur2Var11.getClass();
        ur2Var12.getClass();
        f33.q(ur2Var13, ur2Var14, ur2Var15, ur2Var16, ur2Var17);
        ur2Var18.getClass();
        ur2Var19.getClass();
        wr2Var33.getClass();
        ur2Var20.getClass();
        ur2Var21.getClass();
        ur2Var22.getClass();
        wr2Var34.getClass();
        wr2Var35.getClass();
        ls2Var.getClass();
        ur2Var23.getClass();
        ur2Var24.getClass();
        wr2Var36.getClass();
        ur2Var25.getClass();
        ks2Var2.getClass();
        ur2Var26.getClass();
        f33.q(ur2Var27, ur2Var28, ur2Var29, ur2Var30, ur2Var31);
        f33.q(ur2Var32, ur2Var33, ur2Var34, ur2Var35, ur2Var36);
        f33.q(ur2Var37, ur2Var38, ur2Var39, ur2Var40, ur2Var41);
        f33.q(ur2Var42, ur2Var43, ur2Var44, ur2Var45, ur2Var46);
        ur2Var47.getClass();
        ur2Var48.getClass();
        ur2Var49.getClass();
        ur2Var50.getClass();
        this.a = wr2Var;
        this.b = wr2Var2;
        this.c = lo3Var;
        this.d = wr2Var3;
        this.e = wr2Var4;
        this.f = wr2Var5;
        this.g = wr2Var6;
        this.h = lo3Var2;
        this.i = lo3Var3;
        this.j = lo3Var4;
        this.k = lo3Var5;
        this.l = un3Var;
        this.m = un3Var2;
        this.n = un3Var3;
        this.o = un3Var4;
        this.p = un3Var5;
        this.q = un3Var6;
        this.r = wr2Var7;
        this.s = wr2Var8;
        this.t = sn3Var;
        this.u = io3Var;
        this.v = u5Var;
        this.w = io3Var2;
        this.x = jo3Var;
        this.y = jo3Var2;
        this.z = ur2Var;
        this.A = ur2Var2;
        this.B = ko3Var;
        this.C = ko3Var2;
        this.D = ko3Var3;
        this.E = zn3Var;
        this.F = mo3Var;
        this.G = mo3Var2;
        this.H = z31Var;
        this.I = no3Var;
        this.J = no3Var2;
        this.K = oo3Var;
        this.L = mo3Var3;
        this.M = ko3Var4;
        this.N = zn3Var2;
        this.O = lo3Var6;
        this.P = ko3Var5;
        this.Q = zn3Var3;
        this.R = mo3Var4;
        this.S = wr2Var9;
        this.T = wr2Var10;
        this.U = wr2Var11;
        this.V = wr2Var12;
        this.W = wr2Var13;
        this.X = lo3Var7;
        this.Y = q74Var;
        this.Z = wr2Var14;
        this.a0 = wr2Var15;
        this.b0 = wr2Var16;
        this.c0 = wr2Var17;
        this.d0 = lo3Var8;
        this.e0 = lo3Var9;
        this.f0 = lo3Var10;
        this.g0 = lo3Var11;
        this.h0 = lo3Var12;
        this.i0 = lo3Var13;
        this.j0 = lo3Var14;
        this.k0 = lo3Var15;
        this.l0 = lo3Var16;
        this.m0 = tn3Var;
        this.n0 = lo3Var17;
        this.o0 = tn3Var2;
        this.p0 = lo3Var18;
        this.q0 = kkVar;
        this.r0 = lo3Var19;
        this.s0 = lo3Var20;
        this.t0 = fd0Var;
        this.u0 = p7Var;
        this.v0 = tn3Var3;
        this.w0 = lo3Var21;
        this.x0 = tn3Var4;
        this.y0 = u5Var2;
        this.z0 = lo3Var22;
        this.A0 = lo3Var23;
        this.B0 = lo3Var24;
        this.C0 = lo3Var25;
        this.D0 = sn3Var2;
        this.E0 = sn3Var3;
        this.F0 = tn3Var5;
        this.G0 = sn3Var4;
        this.H0 = sn3Var5;
        this.I0 = sn3Var6;
        this.J0 = sn3Var7;
        this.K0 = sn3Var8;
        this.L0 = sn3Var9;
        this.M0 = sn3Var10;
        this.N0 = sn3Var11;
        this.O0 = tn3Var6;
        this.P0 = sn3Var12;
        this.Q0 = vn3Var;
        this.R0 = vn3Var2;
        this.S0 = sn3Var13;
        this.T0 = sn3Var14;
        this.U0 = sn3Var15;
        this.V0 = sn3Var16;
        this.W0 = wn3Var;
        this.X0 = sn3Var17;
        this.Y0 = wn3Var2;
        this.Z0 = sn3Var18;
        this.a1 = eg3Var;
        this.b1 = t40Var;
        this.c1 = p7Var2;
        this.d1 = q7Var;
        this.e1 = xn3Var;
        this.f1 = wr2Var18;
        this.g1 = yn3Var;
        this.h1 = t40Var2;
        this.i1 = yn3Var2;
        this.j1 = xn3Var2;
        this.k1 = xn3Var3;
        this.l1 = xn3Var4;
        this.m1 = zn3Var4;
        this.n1 = bl3Var;
        this.o1 = u5Var3;
        this.p1 = xm0Var;
        this.q1 = sn3Var19;
        this.r1 = do7Var;
        this.s1 = wr2Var19;
        this.t1 = wr2Var20;
        this.u1 = ur2Var3;
        this.v1 = eo3Var;
        this.w1 = eo3Var2;
        this.x1 = eo3Var3;
        this.y1 = wr2Var21;
        this.z1 = wr2Var22;
        this.A1 = wr2Var23;
        this.B1 = wr2Var24;
        this.C1 = ur2Var4;
        this.D1 = ur2Var5;
        this.E1 = ur2Var6;
        this.F1 = ur2Var7;
        this.G1 = wr2Var25;
        this.H1 = wr2Var26;
        this.I1 = wr2Var27;
        this.J1 = wr2Var28;
        this.K1 = wr2Var29;
        this.L1 = ks2Var;
        this.M1 = ur2Var8;
        this.N1 = wr2Var30;
        this.O1 = wr2Var31;
        this.P1 = wr2Var32;
        this.Q1 = lo3Var26;
        this.R1 = lo3Var27;
        this.S1 = lo3Var28;
        this.T1 = lo3Var29;
        this.U1 = sn3Var20;
        this.V1 = sn3Var21;
        this.W1 = tn3Var7;
        this.X1 = sn3Var22;
        this.Y1 = tn3Var8;
        this.Z1 = sn3Var23;
        this.a2 = sn3Var24;
        this.b2 = ur2Var9;
        this.c2 = bo3Var;
        this.d2 = do3Var;
        this.e2 = do3Var2;
        this.f2 = do3Var3;
        this.g2 = do3Var4;
        this.h2 = eo3Var4;
        this.i2 = eo3Var5;
        this.j2 = ur2Var10;
        this.k2 = ur2Var11;
        this.l2 = ur2Var12;
        this.m2 = ur2Var13;
        this.n2 = ur2Var14;
        this.o2 = ur2Var15;
        this.p2 = ur2Var16;
        this.q2 = ur2Var17;
        this.r2 = ur2Var18;
        this.s2 = ur2Var19;
        this.t2 = eo3Var6;
        this.u2 = od3Var;
        this.v2 = wr2Var33;
        this.w2 = ur2Var20;
        this.x2 = tn3Var9;
        this.y2 = eo3Var7;
        this.z2 = ur2Var21;
        this.A2 = ur2Var22;
        this.B2 = wr2Var34;
        this.C2 = wr2Var35;
        this.D2 = ls2Var;
        this.E2 = ur2Var23;
        this.F2 = ur2Var24;
        this.G2 = wr2Var36;
        this.H2 = ur2Var25;
        this.I2 = ks2Var2;
        this.J2 = ur2Var26;
        this.K2 = ur2Var27;
        this.L2 = ur2Var28;
        this.M2 = ur2Var29;
        this.N2 = ur2Var30;
        this.O2 = ur2Var31;
        this.P2 = ur2Var32;
        this.Q2 = ur2Var33;
        this.R2 = ur2Var34;
        this.S2 = ur2Var35;
        this.T2 = fo3Var;
        this.U2 = ur2Var36;
        this.V2 = ur2Var37;
        this.W2 = ur2Var38;
        this.X2 = ur2Var39;
        this.Y2 = fo3Var2;
        this.Z2 = ur2Var40;
        this.a3 = ur2Var41;
        this.b3 = ur2Var42;
        this.c3 = ur2Var43;
        this.d3 = ur2Var44;
        this.e3 = ur2Var45;
        this.f3 = ur2Var46;
        this.g3 = ur2Var47;
        this.h3 = fo3Var3;
        this.i3 = ur2Var48;
        this.j3 = ur2Var49;
        this.k3 = go3Var;
        this.l3 = ho3Var;
        this.m3 = ur2Var50;
        this.n3 = zn3Var5;
        this.o3 = eo3Var8;
        this.p3 = sn3Var25;
        this.q3 = sn3Var26;
        this.r3 = sn3Var27;
        this.s3 = io3Var3;
        this.t3 = io3Var4;
        this.u3 = io3Var5;
        this.v3 = sn3Var28;
        this.w3 = sn3Var29;
        this.x3 = sn3Var30;
    }

    public final ur2 a() {
        return this.o2;
    }

    public final ur2 b() {
        return this.u2;
    }

    public final wr2 c() {
        return this.t3;
    }

    public final wr2 d() {
        return this.v3;
    }

    public final wr2 e() {
        return this.u3;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof m64) {
            m64 m64Var = (m64) obj;
            if (ye4.p(this.a, m64Var.a) && ye4.p(this.b, m64Var.b) && this.c == m64Var.c && ye4.p(this.d, m64Var.d) && ye4.p(this.e, m64Var.e) && ye4.p(this.f, m64Var.f) && ye4.p(this.g, m64Var.g) && this.h == m64Var.h && this.i == m64Var.i && this.j == m64Var.j && this.k == m64Var.k && this.l == m64Var.l && this.m == m64Var.m && this.n == m64Var.n && this.o == m64Var.o && this.p == m64Var.p && this.q == m64Var.q && ye4.p(this.r, m64Var.r) && ye4.p(this.s, m64Var.s) && this.t == m64Var.t && this.u == m64Var.u && this.v == m64Var.v && this.w == m64Var.w && this.x == m64Var.x && this.y == m64Var.y && ye4.p(this.z, m64Var.z) && ye4.p(this.A, m64Var.A) && this.B == m64Var.B && this.C == m64Var.C && this.D == m64Var.D && this.E == m64Var.E && this.F == m64Var.F && this.G == m64Var.G && this.H.equals(m64Var.H) && this.I == m64Var.I && this.J == m64Var.J && this.K == m64Var.K && this.L == m64Var.L && this.M == m64Var.M && this.N == m64Var.N && this.O == m64Var.O && this.P == m64Var.P && this.Q == m64Var.Q && this.R == m64Var.R && ye4.p(this.S, m64Var.S) && ye4.p(this.T, m64Var.T) && ye4.p(this.U, m64Var.U) && ye4.p(this.V, m64Var.V) && ye4.p(this.W, m64Var.W) && this.X == m64Var.X && this.Y == m64Var.Y && ye4.p(this.Z, m64Var.Z) && ye4.p(this.a0, m64Var.a0) && ye4.p(this.b0, m64Var.b0) && ye4.p(this.c0, m64Var.c0) && this.d0 == m64Var.d0 && this.e0 == m64Var.e0 && this.f0 == m64Var.f0 && this.g0 == m64Var.g0 && this.h0 == m64Var.h0 && this.i0 == m64Var.i0 && this.j0 == m64Var.j0 && this.k0 == m64Var.k0 && this.l0 == m64Var.l0 && this.m0 == m64Var.m0 && this.n0 == m64Var.n0 && this.o0 == m64Var.o0 && this.p0 == m64Var.p0 && this.q0 == m64Var.q0 && this.r0 == m64Var.r0 && this.s0 == m64Var.s0 && this.t0 == m64Var.t0 && this.u0 == m64Var.u0 && this.v0 == m64Var.v0 && this.w0 == m64Var.w0 && this.x0 == m64Var.x0 && this.y0 == m64Var.y0 && this.z0 == m64Var.z0 && this.A0 == m64Var.A0 && this.B0 == m64Var.B0 && this.C0 == m64Var.C0 && this.D0 == m64Var.D0 && this.E0 == m64Var.E0 && this.F0 == m64Var.F0 && this.G0 == m64Var.G0 && this.H0 == m64Var.H0 && this.I0 == m64Var.I0 && this.J0 == m64Var.J0 && this.K0 == m64Var.K0 && this.L0 == m64Var.L0 && this.M0 == m64Var.M0 && this.N0 == m64Var.N0 && this.O0 == m64Var.O0 && this.P0 == m64Var.P0 && this.Q0 == m64Var.Q0 && this.R0 == m64Var.R0 && this.S0 == m64Var.S0 && this.T0 == m64Var.T0 && this.U0 == m64Var.U0 && this.V0 == m64Var.V0 && this.W0 == m64Var.W0 && this.X0 == m64Var.X0 && this.Y0 == m64Var.Y0 && this.Z0 == m64Var.Z0 && this.a1 == m64Var.a1 && this.b1 == m64Var.b1 && this.c1 == m64Var.c1 && this.d1 == m64Var.d1 && this.e1 == m64Var.e1 && ye4.p(this.f1, m64Var.f1) && this.g1 == m64Var.g1 && this.h1 == m64Var.h1 && this.i1 == m64Var.i1 && this.j1 == m64Var.j1 && this.k1 == m64Var.k1 && this.l1 == m64Var.l1 && this.m1 == m64Var.m1 && this.n1 == m64Var.n1 && this.o1 == m64Var.o1 && this.p1 == m64Var.p1 && this.q1 == m64Var.q1 && this.r1 == m64Var.r1 && ye4.p(this.s1, m64Var.s1) && ye4.p(this.t1, m64Var.t1) && ye4.p(this.u1, m64Var.u1) && this.v1 == m64Var.v1 && this.w1 == m64Var.w1 && this.x1 == m64Var.x1 && ye4.p(this.y1, m64Var.y1) && ye4.p(this.z1, m64Var.z1) && ye4.p(this.A1, m64Var.A1) && ye4.p(this.B1, m64Var.B1) && ye4.p(this.C1, m64Var.C1) && ye4.p(this.D1, m64Var.D1) && ye4.p(this.E1, m64Var.E1) && ye4.p(this.F1, m64Var.F1) && ye4.p(this.G1, m64Var.G1) && ye4.p(this.H1, m64Var.H1) && ye4.p(this.I1, m64Var.I1) && ye4.p(this.J1, m64Var.J1) && ye4.p(this.K1, m64Var.K1) && ye4.p(this.L1, m64Var.L1) && ye4.p(this.M1, m64Var.M1) && ye4.p(this.N1, m64Var.N1) && ye4.p(this.O1, m64Var.O1) && ye4.p(this.P1, m64Var.P1) && this.Q1 == m64Var.Q1 && this.R1 == m64Var.R1 && this.S1 == m64Var.S1 && this.T1 == m64Var.T1 && this.U1 == m64Var.U1 && this.V1 == m64Var.V1 && this.W1 == m64Var.W1 && this.X1 == m64Var.X1 && ye4.p(this.Y1, m64Var.Y1) && ye4.p(this.Z1, m64Var.Z1) && ye4.p(this.a2, m64Var.a2) && ye4.p(this.b2, m64Var.b2) && ye4.p(this.c2, m64Var.c2) && ye4.p(this.d2, m64Var.d2) && ye4.p(this.e2, m64Var.e2) && ye4.p(this.f2, m64Var.f2) && ye4.p(this.g2, m64Var.g2) && ye4.p(this.h2, m64Var.h2) && ye4.p(this.i2, m64Var.i2) && ye4.p(this.j2, m64Var.j2) && ye4.p(this.k2, m64Var.k2) && ye4.p(this.l2, m64Var.l2) && ye4.p(this.m2, m64Var.m2) && ye4.p(this.n2, m64Var.n2) && ye4.p(this.o2, m64Var.o2) && ye4.p(this.p2, m64Var.p2) && ye4.p(this.q2, m64Var.q2) && ye4.p(this.r2, m64Var.r2) && ye4.p(this.s2, m64Var.s2) && ye4.p(this.t2, m64Var.t2) && ye4.p(this.u2, m64Var.u2) && ye4.p(this.v2, m64Var.v2) && ye4.p(this.w2, m64Var.w2) && ye4.p(this.x2, m64Var.x2) && ye4.p(this.y2, m64Var.y2) && ye4.p(this.z2, m64Var.z2) && ye4.p(this.A2, m64Var.A2) && ye4.p(this.B2, m64Var.B2) && ye4.p(this.C2, m64Var.C2) && ye4.p(this.D2, m64Var.D2) && ye4.p(this.E2, m64Var.E2) && ye4.p(this.F2, m64Var.F2) && ye4.p(this.G2, m64Var.G2) && ye4.p(this.H2, m64Var.H2) && ye4.p(this.I2, m64Var.I2) && ye4.p(this.J2, m64Var.J2) && ye4.p(this.K2, m64Var.K2) && ye4.p(this.L2, m64Var.L2) && ye4.p(this.M2, m64Var.M2) && ye4.p(this.N2, m64Var.N2) && ye4.p(this.O2, m64Var.O2) && ye4.p(this.P2, m64Var.P2) && ye4.p(this.Q2, m64Var.Q2) && ye4.p(this.R2, m64Var.R2) && ye4.p(this.S2, m64Var.S2) && ye4.p(this.T2, m64Var.T2) && ye4.p(this.U2, m64Var.U2) && ye4.p(this.V2, m64Var.V2) && ye4.p(this.W2, m64Var.W2) && ye4.p(this.X2, m64Var.X2) && ye4.p(this.Y2, m64Var.Y2) && ye4.p(this.Z2, m64Var.Z2) && ye4.p(this.a3, m64Var.a3) && ye4.p(this.b3, m64Var.b3) && ye4.p(this.c3, m64Var.c3) && ye4.p(this.d3, m64Var.d3) && ye4.p(this.e3, m64Var.e3) && ye4.p(this.f3, m64Var.f3) && ye4.p(this.g3, m64Var.g3) && ye4.p(this.h3, m64Var.h3) && ye4.p(this.i3, m64Var.i3) && ye4.p(this.j3, m64Var.j3) && ye4.p(this.k3, m64Var.k3) && ye4.p(this.l3, m64Var.l3) && ye4.p(this.m3, m64Var.m3) && ye4.p(this.n3, m64Var.n3) && ye4.p(this.o3, m64Var.o3) && ye4.p(this.p3, m64Var.p3) && ye4.p(this.q3, m64Var.q3) && ye4.p(this.r3, m64Var.r3) && ye4.p(this.s3, m64Var.s3) && ye4.p(this.t3, m64Var.t3) && ye4.p(this.u3, m64Var.u3) && ye4.p(this.v3, m64Var.v3) && ye4.p(this.w3, m64Var.w3) && ye4.p(this.x3, m64Var.x3)) {
                return true;
            }
        }
        return false;
    }

    public final ur2 f() {
        return this.w2;
    }

    public final ur2 g() {
        return this.l2;
    }

    public final ur2 h() {
        return this.p2;
    }

    public final int hashCode() {
        return this.x3.hashCode() + ((this.w3.hashCode() + ((this.v3.hashCode() + ((this.u3.hashCode() + ((this.t3.hashCode() + ((this.s3.hashCode() + ((this.r3.hashCode() + ((this.q3.hashCode() + ((this.p3.hashCode() + ((this.o3.hashCode() + ((this.n3.hashCode() + rx1.f(this.m3, (this.l3.hashCode() + ((this.k3.hashCode() + rx1.f(this.j3, rx1.f(this.i3, (hashCode() + rx1.f(this.g3, rx1.f(this.f3, rx1.f(this.e3, rx1.f(this.d3, rx1.f(this.c3, rx1.f(this.b3, rx1.f(this.a3, rx1.f(this.Z2, (hashCode() + rx1.f(this.X2, rx1.f(this.W2, rx1.f(this.V2, rx1.f(this.U2, (hashCode() + rx1.f(this.S2, rx1.f(this.R2, rx1.f(this.Q2, rx1.f(this.P2, rx1.f(this.O2, rx1.f(this.N2, rx1.f(this.M2, rx1.f(this.L2, rx1.f(this.K2, rx1.f(this.J2, rx1.d(rx1.f(this.H2, pk0.b(rx1.f(this.F2, rx1.f(this.E2, rx1.g(this.D2, pk0.b(pk0.b(rx1.f(this.A2, rx1.f(this.z2, (this.y2.hashCode() + ((this.x2.hashCode() + rx1.f(this.w2, pk0.b((this.u2.hashCode() + ((this.t2.hashCode() + rx1.f(this.s2, rx1.f(this.r2, rx1.f(this.q2, rx1.f(this.p2, rx1.f(this.o2, rx1.f(this.n2, rx1.f(this.m2, rx1.f(this.l2, rx1.f(this.k2, rx1.f(this.j2, (this.i2.hashCode() + ((this.h2.hashCode() + ((this.g2.hashCode() + ((this.f2.hashCode() + ((this.e2.hashCode() + ((this.d2.hashCode() + ((this.c2.hashCode() + rx1.f(this.b2, (this.a2.hashCode() + ((this.Z1.hashCode() + ((this.Y1.hashCode() + ((this.X1.hashCode() + ((this.W1.hashCode() + ((this.V1.hashCode() + ((this.U1.hashCode() + ((this.T1.hashCode() + ((this.S1.hashCode() + ((this.R1.hashCode() + ((this.Q1.hashCode() + pk0.b(pk0.b(pk0.b(rx1.f(this.M1, rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.F1, rx1.f(this.E1, rx1.f(this.D1, rx1.f(this.C1, pk0.b(pk0.b(pk0.b(pk0.b((this.x1.hashCode() + ((this.w1.hashCode() + ((this.v1.hashCode() + rx1.f(this.u1, pk0.b(pk0.b((this.r1.hashCode() + ((this.q1.hashCode() + ((this.p1.hashCode() + ((this.o1.hashCode() + ((this.n1.hashCode() + ((this.m1.hashCode() + ((this.l1.hashCode() + ((this.k1.hashCode() + ((this.j1.hashCode() + ((this.i1.hashCode() + ((this.h1.hashCode() + ((this.g1.hashCode() + pk0.b((this.e1.hashCode() + ((this.d1.hashCode() + ((this.c1.hashCode() + ((this.b1.hashCode() + ((this.a1.hashCode() + ((this.Z0.hashCode() + ((this.Y0.hashCode() + ((this.X0.hashCode() + ((this.W0.hashCode() + ((this.V0.hashCode() + ((this.U0.hashCode() + ((this.T0.hashCode() + ((this.S0.hashCode() + ((hashCode() + ((hashCode() + ((this.P0.hashCode() + ((this.O0.hashCode() + ((this.N0.hashCode() + ((this.M0.hashCode() + ((this.L0.hashCode() + ((this.K0.hashCode() + ((this.J0.hashCode() + ((this.I0.hashCode() + ((this.H0.hashCode() + ((this.G0.hashCode() + ((this.F0.hashCode() + ((this.E0.hashCode() + ((this.D0.hashCode() + ((this.C0.hashCode() + ((this.B0.hashCode() + ((this.A0.hashCode() + ((this.z0.hashCode() + ((this.y0.hashCode() + ((this.x0.hashCode() + ((this.w0.hashCode() + ((this.v0.hashCode() + ((this.u0.hashCode() + ((this.t0.hashCode() + ((this.s0.hashCode() + ((this.r0.hashCode() + ((this.q0.hashCode() + ((this.p0.hashCode() + ((this.o0.hashCode() + ((this.n0.hashCode() + ((this.m0.hashCode() + ((this.l0.hashCode() + ((this.k0.hashCode() + ((this.j0.hashCode() + ((this.i0.hashCode() + ((this.h0.hashCode() + ((this.g0.hashCode() + ((this.f0.hashCode() + ((this.e0.hashCode() + ((this.d0.hashCode() + pk0.b(pk0.b(pk0.b(pk0.b((this.Y.hashCode() + ((this.X.hashCode() + pk0.b(pk0.b(pk0.b(pk0.b(pk0.b((this.R.hashCode() + ((this.Q.hashCode() + ((this.P.hashCode() + ((this.O.hashCode() + ((this.N.hashCode() + ((this.M.hashCode() + ((this.L.hashCode() + ((this.K.hashCode() + ((this.J.hashCode() + ((this.I.hashCode() + ((this.H.hashCode() + ((this.G.hashCode() + ((this.F.hashCode() + ((this.E.hashCode() + ((this.D.hashCode() + ((this.C.hashCode() + ((this.B.hashCode() + rx1.f(this.A, rx1.f(this.z, (hashCode() + ((hashCode() + ((this.w.hashCode() + ((this.v.hashCode() + ((this.u.hashCode() + ((this.t.hashCode() + pk0.b(pk0.b((this.q.hashCode() + ((this.p.hashCode() + ((this.o.hashCode() + ((this.n.hashCode() + ((this.m.hashCode() + ((this.l.hashCode() + ((this.k.hashCode() + ((this.j.hashCode() + ((this.i.hashCode() + ((this.h.hashCode() + pk0.b(pk0.b(pk0.b(pk0.b((this.c.hashCode() + pk0.b(this.a.hashCode() * 31, this.b, 31)) * 31, this.d, 31), this.e, 31), this.f, 31), this.g, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, this.r, 31), this.s, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, this.S, 31), this.T, 31), this.U, 31), this.V, 31), this.W, 31)) * 31)) * 31, this.Z, 31), this.a0, 31), this.b0, 31), this.c0, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, this.f1, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, this.s1, 31), this.t1, 31), 31)) * 31)) * 31)) * 31, this.y1, 31), this.z1, 31), this.A1, 31), this.B1, 31), 31), 31), 31), 31), this.G1, 31), this.H1, 31), this.I1, 31), this.J1, 31), this.K1, 31), 31, this.L1), 31), this.N1, 31), this.O1, 31), this.P1, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31), 31), 31), 31), 31), 31), 31), 31), 31), 31)) * 31)) * 31, this.v2, 31), 31)) * 31)) * 31, 31), 31), this.B2, 31), this.C2, 31), 31), 31), 31), this.G2, 31), 31), 31, this.I2), 31), 31), 31), 31), 31), 31), 31), 31), 31), 31)) * 31, 31), 31), 31), 31)) * 31, 31), 31), 31), 31), 31), 31), 31), 31)) * 31, 31), 31)) * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final ur2 i() {
        return this.y2;
    }

    public final wr2 j() {
        return this.w3;
    }

    public final wr2 k() {
        return this.p3;
    }

    public final ur2 l() {
        return this.w1;
    }

    public final ur2 m() {
        return this.A2;
    }

    public final wr2 n() {
        return this.x2;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("IisuSettingsCallbacks(onAppLanguageChange=");
        sb.append(this.a);
        sb.append(", onForceIiSuOnLaunchChange=");
        sb.append(this.b);
        sb.append(", onDefaultLaunchPageChange=");
        sb.append(this.c);
        sb.append(", onBlackOutUnusedDisplayOnLaunchChange=");
        sb.append(this.d);
        sb.append(", onProfileNudgeEnabledChange=");
        rx1.B(sb, this.e, ", onDualDisplayHomeLocationChange=", this.f, ", onDualDisplayInactiveSurfaceChange=");
        sb.append(this.g);
        sb.append(", onAlwaysShowRomsTitleSectionChange=");
        sb.append(this.h);
        sb.append(", onNeverShowRomsTitleSectionChange=");
        sb.append(this.i);
        sb.append(", onShowConsolesTitleSectionChange=");
        sb.append(this.j);
        sb.append(", onShowAppsTitleSectionChange=");
        sb.append(this.k);
        sb.append(", onHorizontalGridOnSingleScreenChange=");
        sb.append(this.l);
        sb.append(", onHorizontalGridOnDualScreenChange=");
        sb.append(this.m);
        sb.append(", onHorizontalGridOverrideOnHomeChange=");
        sb.append(this.n);
        sb.append(", onHorizontalGridOverrideOnPlatformsChange=");
        sb.append(this.o);
        sb.append(", onHorizontalGridOverrideOnGamesChange=");
        sb.append(this.p);
        sb.append(", onHorizontalGridOverrideOnAppsChange=");
        sb.append(this.q);
        sb.append(", onTouchContextMenuGestureModeChange=");
        sb.append(this.r);
        sb.append(", onBrowser2TapToSelectChange=");
        sb.append(this.s);
        sb.append(", onLauncherRightStickModeChange=");
        sb.append(this.t);
        sb.append(", onRetroAchievementsShortcutButtonChange=");
        sb.append(this.u);
        sb.append(", onScreenSwapShortcutButtonChange=");
        sb.append(this.v);
        sb.append(", onAppDrawerShortcutButtonChange=");
        sb.append(this.w);
        sb.append(", onSwapAbXyChange=");
        sb.append(this.x);
        sb.append(", onSwapAbXyGlyphsChange=");
        sb.append(this.y);
        sb.append(", onRotateMainDisplay=");
        sb.append(this.z);
        sb.append(", onExportLogs=");
        sb.append(this.A);
        sb.append(", onUiSoundsEnabledChange=");
        sb.append(this.B);
        sb.append(", onHapticFeedbackLevelChange=");
        sb.append(this.C);
        sb.append(", onGlobalMusicVolumeChange=");
        sb.append(this.D);
        sb.append(", onGlobalMusicVolumePreview=");
        sb.append(this.E);
        sb.append(", onUseTimeBasedMusicChange=");
        sb.append(this.F);
        sb.append(", onShuffleTimeBasedMusicChange=");
        sb.append(this.G);
        sb.append(", onImportMusic=");
        sb.append(this.H);
        sb.append(", onCreateTimeBasedMusicEntry=");
        sb.append(this.I);
        sb.append(", onUpdateTimeBasedMusicEntrySource=");
        sb.append(this.J);
        sb.append(", onUpdateTimeBasedMusicEntryTime=");
        sb.append(this.K);
        sb.append(", onRemoveTimeBasedMusicEntry=");
        sb.append(this.L);
        sb.append(", onSoundbiteVolumeChange=");
        sb.append(this.M);
        sb.append(", onSoundbiteVolumePreview=");
        sb.append(this.N);
        sb.append(", onHomeSoundbitesEnabledChange=");
        sb.append(this.O);
        sb.append(", onUiEffectsVolumeChange=");
        sb.append(this.P);
        sb.append(", onUiEffectsVolumePreview=");
        sb.append(this.Q);
        sb.append(", onHomeMusicPresetChange=");
        sb.append(this.R);
        sb.append(", onThemeModeChange=");
        rx1.B(sb, this.S, ", onLauncherFontChoiceChange=", this.T, ", onLauncherStandardTextWeightChoiceChange=");
        rx1.B(sb, this.U, ", onLauncherBoldTextWeightChoiceChange=", this.V, ", onMultiWeightFontCompactSpacingEnabledChange=");
        sb.append(this.W);
        sb.append(", onCustomThemeChange=");
        sb.append(this.X);
        sb.append(", onShowThemePicker=");
        sb.append(this.Y);
        sb.append(", onDisableThemeVideosChange=");
        sb.append(this.Z);
        sb.append(", onPreferCompatibleBundledThemeVideosChange=");
        rx1.B(sb, this.a0, ", onDisableDarkModePlatformIconsChange=", this.b0, ", onPlayMediaOnGamesPageChange=");
        sb.append(this.c0);
        sb.append(", onDisableAllHeroesChange=");
        sb.append(this.d0);
        sb.append(", onDisableHeroesOnHomeChange=");
        sb.append(this.e0);
        sb.append(", onDisableHeroesOnGamesGridChange=");
        sb.append(this.f0);
        sb.append(", onDisableHeroesOnSecondaryDisplayChange=");
        sb.append(this.g0);
        sb.append(", onDisableHeroesOnBottomScreenInSingleScreenModeChange=");
        sb.append(this.h0);
        sb.append(", onAnimateHeroesChange=");
        sb.append(this.i0);
        sb.append(", onPauseAnimationsWhenIdleChange=");
        sb.append(this.j0);
        sb.append(", onCategoryTitleWobbleEnabledChange=");
        sb.append(this.k0);
        sb.append(", onCommittedTargetPostIdleSettleDelayMsChange=");
        sb.append(this.l0);
        sb.append(", onPageSwipeAnimationsEnabledChange=");
        sb.append(this.m0);
        sb.append(", onBrowserPageTransitionModeChange=");
        sb.append(this.n0);
        sb.append(", onFocusRingAnimationsEnabledChange=");
        sb.append(this.o0);
        sb.append(", onGridDominoAnimationsEnabledChange=");
        sb.append(this.p0);
        sb.append(", onRendererColumnReductionChange=");
        sb.append(this.q0);
        sb.append(", onPerformanceMetricsOverlayEnabledChange=");
        sb.append(this.r0);
        sb.append(", onHomeGlassCardStyleChange=");
        sb.append(this.s0);
        sb.append(", onRemoveLargePanelContainersChange=");
        sb.append(this.t0);
        sb.append(", onSingleScreenHomeDashboardModeChange=");
        sb.append(this.u0);
        sb.append(", onSingleScreenHomeGlassModeChange=");
        sb.append(this.v0);
        sb.append(", onContextMenuGlassEnabledChange=");
        sb.append(this.w0);
        sb.append(", onGlassOutlineEnabledChange=");
        sb.append(this.x0);
        sb.append(", onSimpleIconsChange=");
        sb.append(this.y0);
        sb.append(", onHomeGlassBlurRadiusDpChange=");
        sb.append(this.z0);
        sb.append(", onHomeGlassOpacityChange=");
        sb.append(this.A0);
        sb.append(", onHomeGlassTintColorArgbChange=");
        sb.append(this.B0);
        sb.append(", onCustomSelectionGradientEnabledChange=");
        sb.append(this.C0);
        sb.append(", onFocusIndicatorPrimaryColorArgbChange=");
        sb.append(this.D0);
        sb.append(", onFocusIndicatorSecondaryColorArgbChange=");
        sb.append(this.E0);
        sb.append(", onTooltipUseTitleImageChange=");
        sb.append(this.F0);
        sb.append(", onTooltipUseForOneRowChange=");
        sb.append(this.G0);
        sb.append(", onTooltipUseForGridsChange=");
        sb.append(this.H0);
        sb.append(", onTooltipUseForRomsAppsChange=");
        sb.append(this.I0);
        sb.append(", onTooltipUseForQuickAccessChange=");
        sb.append(this.J0);
        sb.append(", onTitleImageForHorizontalCarouselChange=");
        sb.append(this.K0);
        sb.append(", onTitleImageForXmbChange=");
        sb.append(this.L0);
        sb.append(", onConsoleTitleImageForXmbChange=");
        sb.append(this.M0);
        sb.append(", onXmbHorizontalPathChange=");
        sb.append(this.N0);
        sb.append(", onXmbDropShadowEnabledChange=");
        sb.append(this.O0);
        sb.append(", onXmbHeroMaskChange=");
        sb.append(this.P0);
        sb.append(", onForceSingleScreenViewOnInternalScreenChange=");
        sb.append(this.Q0);
        sb.append(", onForceOldLayoutChange=");
        sb.append(this.R0);
        sb.append(", onShowFocusedTitleOnHomeChange=");
        sb.append(this.S0);
        sb.append(", onShowFocusedTitleInSingleScreenHudChange=");
        sb.append(this.T0);
        sb.append(", onTitleImageForFocusedInSingleScreenHudChange=");
        sb.append(this.U0);
        sb.append(", onBackgroundSkrimOpacityChange=");
        sb.append(this.V0);
        sb.append(", onBackgroundSkrimOpacityPreview=");
        sb.append(this.W0);
        sb.append(", onDualScreenBackgroundSkrimMaskChange=");
        sb.append(this.X0);
        sb.append(", onDualScreenBackgroundSkrimMaskPreview=");
        sb.append(this.Y0);
        sb.append(", onDualScreenBackgroundSkrimFeatherChange=");
        sb.append(this.Z0);
        sb.append(", onDualScreenBackgroundSkrimFeatherPreview=");
        sb.append(this.a1);
        sb.append(", onRefreshThemes=");
        sb.append(this.b1);
        sb.append(", onDeleteTheme=");
        sb.append(this.c1);
        sb.append(", onRenameTheme=");
        sb.append(this.d1);
        sb.append(", onOptimizeThemeVideos=");
        sb.append(this.e1);
        sb.append(", onThemeVideoFrameRateCapChange=");
        sb.append(this.f1);
        sb.append(", onImportTheme=");
        sb.append(this.g1);
        sb.append(", onRefreshPlatformPacks=");
        sb.append(this.h1);
        sb.append(", onImportPlatformPack=");
        sb.append(this.i1);
        sb.append(", onMovePlatformPackUp=");
        sb.append(this.j1);
        sb.append(", onMovePlatformPackDown=");
        sb.append(this.k1);
        sb.append(", onDeletePlatformPack=");
        sb.append(this.l1);
        sb.append(", onExportTheme=");
        sb.append(this.m1);
        sb.append(", onRequestImagePicker=");
        sb.append(this.n1);
        sb.append(", onCreateTheme=");
        sb.append(this.o1);
        sb.append(", onEditTheme=");
        sb.append(this.p1);
        sb.append(", onAssetStorageLocationChange=");
        sb.append(this.q1);
        sb.append(", onScreenScraperCredentialsChange=");
        sb.append(this.r1);
        sb.append(", onTheGamesDbApiKeyChange=");
        rx1.B(sb, this.s1, ", onSteamGridDbApiKeyChange=", this.t1, ", onStartMultiScrape=");
        sb.append(this.u1);
        sb.append(", onStartScreenScraperScrape=");
        sb.append(this.v1);
        sb.append(", onStartTheGamesDbScrape=");
        sb.append(this.w1);
        sb.append(", onStartSteamGridDbScrape=");
        sb.append(this.x1);
        sb.append(", onDiscordIntegrationEnabledChange=");
        rx1.B(sb, this.y1, ", onDiscordAutoConnectChange=", this.z1, ", onDiscordRichPresenceEnabledChange=");
        rx1.B(sb, this.A1, ", onDiscordUseProfilePictureChange=", this.B1, ", onDiscordLogin=");
        pk0.w(this.C1, this.D1, ", onDiscordDisconnect=", ", onDiscordRefresh=", sb);
        pk0.w(this.E1, this.F1, ", onOpenDiscordSocialExperience=", ", onDiscordPresenceShowCurrentConsoleCategoryChange=", sb);
        rx1.B(sb, this.G1, ", onDiscordPresenceShowCurrentRomAppChange=", this.H1, ", onDiscordPresenceShowBrowsingIiSuChange=");
        rx1.B(sb, this.I1, ", onDiscordShowFriendsCapsuleChange=", this.J1, ", onDiscordHiddenUserIdsChange=");
        sb.append(this.K1);
        sb.append(", onDiscordSetPresence=");
        sb.append(this.L1);
        sb.append(", onDiscordClearPresence=");
        f33.s(sb, this.M1, ", onScraperPreferredLanguageChange=", this.N1, ", onScraperPreferredRegionChange=");
        rx1.B(sb, this.O1, ", onAggressiveScrapingEnabledChange=", this.P1, ", onPreferRetroAchievementsIconChange=");
        sb.append(this.Q1);
        sb.append(", onUseNativeRetroAchievementsMenuIconsChange=");
        sb.append(this.R1);
        sb.append(", onShowSoftcoreRetroAchievementsChange=");
        sb.append(this.S1);
        sb.append(", onRetroAchievementsHeroesEnabledChange=");
        sb.append(this.T1);
        sb.append(", onDualDetailShowSystemStatusChange=");
        sb.append(this.U1);
        sb.append(", onDualDetailShowConnectedFriendsChange=");
        sb.append(this.V1);
        sb.append(", onDualDetailShowAchievementsSummaryChange=");
        sb.append(this.W1);
        sb.append(", onDualDetailShowButtonHintChange=");
        sb.append(this.X1);
        sb.append(", onDualDetailShowGameplaySlidesChange=");
        sb.append(this.Y1);
        sb.append(", onDualDetailMakeTitleBiggerChange=");
        sb.append(this.Z1);
        sb.append(", onDualDetailShowHomeBackgroundOnIdleChange=");
        sb.append(this.a2);
        sb.append(", onRefreshMetadata=");
        sb.append(this.b2);
        sb.append(", onAutoBackupFrequencyDaysChange=");
        sb.append(this.c2);
        sb.append(", onChooseAutoBackupFolder=");
        sb.append(this.d2);
        sb.append(", onUsePrivateAutoBackupFolder=");
        sb.append(this.e2);
        sb.append(", onBackupNow=");
        sb.append(this.f2);
        sb.append(", onRestoreLastBackup=");
        sb.append(this.g2);
        sb.append(", onBackupData=");
        sb.append(this.h2);
        sb.append(", onRestoreData=");
        sb.append(this.i2);
        sb.append(", onResetToDefaultSettings=");
        sb.append(this.j2);
        sb.append(", onRefreshManagedAllMediaStats=");
        pk0.w(this.k2, this.l2, ", onRefreshManagedMediaCacheStats=", ", onClearAllDownloadedMedia=", sb);
        pk0.w(this.m2, this.n2, ", onCancelClearAllDownloadedMedia=", ", onClearManagedMediaCaches=", sb);
        pk0.w(this.o2, this.p2, ", onRegenerateManagedMediaCaches=", ", onClearRetroAchievementsLookupCache=", sb);
        pk0.w(this.q2, this.r2, ", onClearRetroAchievementsHashCache=", ", onClearRetroAchievementsImages=", sb);
        sb.append(this.s2);
        sb.append(", onOpenIisuMediaFolder=");
        sb.append(this.t2);
        sb.append(", onLinkGameLibraryFolder=");
        sb.append(this.u2);
        sb.append(", onRemoveGameLibraryRoot=");
        sb.append(this.v2);
        sb.append(", onOpenManageAllFilesAccessSettings=");
        sb.append(this.w2);
        sb.append(", onUseManagedImageCacheChange=");
        sb.append(this.x2);
        sb.append(", onRequestEsDeFolderLink=");
        sb.append(this.y2);
        sb.append(", onReloadEsDeFolder=");
        sb.append(this.z2);
        sb.append(", onUnlinkEsDeFolder=");
        f33.s(sb, this.A2, ", onEsDeUsePhysicalMediaAsIconChange=", this.B2, ", onEsDePrecacheRomIconThumbnailsOnSyncChange=");
        sb.append(this.C2);
        sb.append(", onLinkRommServer=");
        sb.append(this.D2);
        sb.append(", onReloadRommCatalog=");
        pk0.w(this.E2, this.F2, ", onPreloadRommAssets=", ", onRommMergeConsolesWithLocalChange=", sb);
        f33.t(sb, this.G2, ", onUnlinkRommServer=", this.H2, ", onSetRommCollectionEnabled=");
        sb.append(this.I2);
        sb.append(", onCheckForUpdates=");
        sb.append(this.J2);
        sb.append(", onUpdateDownload=");
        pk0.w(this.K2, this.L2, ", onUpdateViewGitHub=", ", onUpdateInstall=", sb);
        pk0.w(this.M2, this.N2, ", onUpdateDismiss=", ", onUpdateClearError=", sb);
        pk0.w(this.O2, this.P2, ", onLinkSupporterUpdates=", ", onUnlinkSupporterUpdates=", sb);
        sb.append(this.Q2);
        String string = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(string);
        sb2.append(", onCheckEmuladoresJsonUpdates=");
        sb2.append(this.R2);
        sb2.append(", onApplyEmuladoresJsonUpdate=");
        sb2.append(this.S2);
        sb2.append(", onImportEmuladoresJson=");
        sb2.append(this.T2);
        sb2.append(", onOpenEmuladoresJsonUpdatePage=");
        sb2.append(this.U2);
        rx1.x(this.V2, this.W2, ", onClearEmuladoresJsonUpdateError=", ", onCheckSupportedEmulatorsJsonUpdates=", sb2);
        sb2.append(", onApplySupportedEmulatorsJsonUpdate=");
        sb2.append(this.X2);
        sb2.append(", onImportSupportedEmulatorsJson=");
        sb2.append(this.Y2);
        rx1.x(this.Z2, this.a3, ", onOpenSupportedEmulatorsJsonUpdatePage=", ", onClearSupportedEmulatorsJsonUpdateError=", sb2);
        rx1.x(this.b3, this.c3, ", onCheckEmulatorOptionsJsonUpdates=", ", onApplyEmulatorOptionsJsonUpdate=", sb2);
        rx1.x(this.d3, this.e3, ", onOpenEmulatorOptionsJsonUpdatePage=", ", onClearEmulatorOptionsJsonUpdateError=", sb2);
        rx1.x(this.f3, this.g3, ", onCheckStarterPackUpdates=", ", onApplyStarterPackUpdate=", sb2);
        sb2.append(", onImportStarterPack=");
        sb2.append(this.h3);
        sb2.append(", onOpenStarterPackUpdatePage=");
        sb2.append(this.i3);
        sb2.append(", onClearStarterPackUpdateError=");
        sb2.append(this.j3);
        sb2.append(", onRestartAudio=");
        sb2.append(this.k3);
        sb2.append(", onEnableHighPerformanceMode=");
        sb2.append(this.l3);
        sb2.append(", onRestartOnboarding=");
        sb2.append(this.m3);
        sb2.append(", onOpenUrl=");
        sb2.append(this.n3);
        sb2.append(", onOpenGitHub=");
        sb2.append(this.o3);
        sb2.append(", onShowHiddenFilesChange=");
        sb2.append(this.p3);
        sb2.append(", onRomScanDepthChange=");
        sb2.append(this.q3);
        sb2.append(", onNotificationHistoryLimitChange=");
        sb2.append(this.r3);
        sb2.append(", onNotificationPopupPreviewsEnabledChange=");
        sb2.append(this.s3);
        sb2.append(", onNotificationIisuPopupPreviewsEnabledChange=");
        sb2.append(this.t3);
        sb2.append(", onNotificationSystemPopupPreviewsEnabledChange=");
        sb2.append(this.u3);
        sb2.append(", onNotificationPopupSoundEnabledChange=");
        sb2.append(this.v3);
        sb2.append(", onRomImportWarningNotificationsEnabledChange=");
        sb2.append(this.w3);
        sb2.append(", onStarterPackUpdateNotificationsEnabledChange=");
        sb2.append(this.x3);
        sb2.append(")");
        return sb2.toString();
    }
}
