package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class og3 {
    public final wr2 A;
    public final e93 A0;
    public final wr2 B;
    public final wr2 C;
    public final ks2 D;
    public final ks2 E;
    public final ks2 F;
    public final ks2 G;
    public final ks2 H;
    public final ks2 I;
    public final ks2 J;
    public final ks2 K;
    public final ks2 L;
    public final ks2 M;
    public final ks2 N;
    public final ks2 O;
    public final ks2 P;
    public final ks2 Q;
    public final ks2 R;
    public final ks2 S;
    public final ks2 T;
    public final ls2 U;
    public final ms2 V;
    public final ls2 W;
    public final ls2 X;
    public final ks2 Y;
    public final c93 Z;
    public final lp3 a;
    public final ur2 a0;
    public final e73 b;
    public final b93 b0;
    public final lg3 c;
    public final b93 c0;
    public final u83 d;
    public final wr2 d0;
    public final l23 e;
    public final c93 e0;
    public final uv3 f;
    public final wr2 f0;
    public final kw3 g;
    public final c93 g0;
    public final um3 h;
    public final wr2 h0;
    public final bw3 i;
    public final r83 i0;
    public final v33 j;
    public final a73 j0;
    public final o43 k;
    public final y63 k0;
    public final long l;
    public final wr2 l0;
    public final g43 m;
    public final wr2 m0;
    public final ur2 n;
    public final ur2 n0;
    public final ks2 o;
    public final ur2 o0;
    public final wr2 p;
    public final wr2 p0;
    public final ks2 q;
    public final wr2 q0;
    public final ur2 r;
    public final wr2 r0;
    public final a73 s;
    public final ur2 s0;
    public final ur2 t;
    public final wr2 t0;
    public final ur2 u;
    public final wr2 u0;
    public final wr2 v;
    public final wr2 v0;
    public final ur2 w;
    public final wr2 w0;
    public final ur2 x;
    public final ks2 x0;
    public final b33 y;
    public final wr2 y0;
    public final d93 z;
    public final wr2 z0;

    public og3(lp3 lp3Var, e73 e73Var, lg3 lg3Var, u83 u83Var, l23 l23Var, uv3 uv3Var, kw3 kw3Var, um3 um3Var, bw3 bw3Var, v33 v33Var, o43 o43Var, long j, g43 g43Var, ur2 ur2Var, ks2 ks2Var, wr2 wr2Var, ks2 ks2Var2, ur2 ur2Var2, a73 a73Var, ur2 ur2Var3, ur2 ur2Var4, wr2 wr2Var2, ur2 ur2Var5, ur2 ur2Var6, b33 b33Var, d93 d93Var, wr2 wr2Var3, wr2 wr2Var4, wr2 wr2Var5, ks2 ks2Var3, ks2 ks2Var4, ks2 ks2Var5, ks2 ks2Var6, ks2 ks2Var7, ks2 ks2Var8, ks2 ks2Var9, ks2 ks2Var10, ks2 ks2Var11, ks2 ks2Var12, ks2 ks2Var13, ks2 ks2Var14, ks2 ks2Var15, ks2 ks2Var16, ks2 ks2Var17, ks2 ks2Var18, ks2 ks2Var19, ls2 ls2Var, ms2 ms2Var, ls2 ls2Var2, ls2 ls2Var3, ks2 ks2Var20, c93 c93Var, ur2 ur2Var7, b93 b93Var, b93 b93Var2, wr2 wr2Var6, c93 c93Var2, wr2 wr2Var7, c93 c93Var3, wr2 wr2Var8, r83 r83Var, a73 a73Var2, y63 y63Var, wr2 wr2Var9, wr2 wr2Var10, ur2 ur2Var8, ur2 ur2Var9, wr2 wr2Var11, wr2 wr2Var12, wr2 wr2Var13, ur2 ur2Var10, wr2 wr2Var14, wr2 wr2Var15, wr2 wr2Var16, wr2 wr2Var17, ks2 ks2Var21, wr2 wr2Var18, wr2 wr2Var19, e93 e93Var) {
        o43Var.getClass();
        ur2Var.getClass();
        ks2Var.getClass();
        wr2Var.getClass();
        ks2Var2.getClass();
        ur2Var2.getClass();
        ur2Var3.getClass();
        ur2Var4.getClass();
        wr2Var2.getClass();
        ur2Var5.getClass();
        ur2Var6.getClass();
        wr2Var3.getClass();
        wr2Var4.getClass();
        wr2Var5.getClass();
        ks2Var3.getClass();
        ks2Var4.getClass();
        ks2Var5.getClass();
        ks2Var6.getClass();
        ks2Var7.getClass();
        ks2Var8.getClass();
        ks2Var9.getClass();
        ks2Var10.getClass();
        ks2Var11.getClass();
        ks2Var12.getClass();
        ks2Var13.getClass();
        ks2Var14.getClass();
        ks2Var15.getClass();
        ks2Var16.getClass();
        ks2Var17.getClass();
        ks2Var18.getClass();
        ks2Var19.getClass();
        ls2Var.getClass();
        ms2Var.getClass();
        ls2Var2.getClass();
        ls2Var3.getClass();
        ks2Var20.getClass();
        ur2Var7.getClass();
        wr2Var6.getClass();
        wr2Var7.getClass();
        wr2Var8.getClass();
        wr2Var9.getClass();
        wr2Var10.getClass();
        ur2Var8.getClass();
        ur2Var9.getClass();
        wr2Var11.getClass();
        wr2Var12.getClass();
        wr2Var13.getClass();
        ur2Var10.getClass();
        wr2Var14.getClass();
        wr2Var15.getClass();
        wr2Var16.getClass();
        wr2Var17.getClass();
        ks2Var21.getClass();
        wr2Var18.getClass();
        wr2Var19.getClass();
        this.a = lp3Var;
        this.b = e73Var;
        this.c = lg3Var;
        this.d = u83Var;
        this.e = l23Var;
        this.f = uv3Var;
        this.g = kw3Var;
        this.h = um3Var;
        this.i = bw3Var;
        this.j = v33Var;
        this.k = o43Var;
        this.l = j;
        this.m = g43Var;
        this.n = ur2Var;
        this.o = ks2Var;
        this.p = wr2Var;
        this.q = ks2Var2;
        this.r = ur2Var2;
        this.s = a73Var;
        this.t = ur2Var3;
        this.u = ur2Var4;
        this.v = wr2Var2;
        this.w = ur2Var5;
        this.x = ur2Var6;
        this.y = b33Var;
        this.z = d93Var;
        this.A = wr2Var3;
        this.B = wr2Var4;
        this.C = wr2Var5;
        this.D = ks2Var3;
        this.E = ks2Var4;
        this.F = ks2Var5;
        this.G = ks2Var6;
        this.H = ks2Var7;
        this.I = ks2Var8;
        this.J = ks2Var9;
        this.K = ks2Var10;
        this.L = ks2Var11;
        this.M = ks2Var12;
        this.N = ks2Var13;
        this.O = ks2Var14;
        this.P = ks2Var15;
        this.Q = ks2Var16;
        this.R = ks2Var17;
        this.S = ks2Var18;
        this.T = ks2Var19;
        this.U = ls2Var;
        this.V = ms2Var;
        this.W = ls2Var2;
        this.X = ls2Var3;
        this.Y = ks2Var20;
        this.Z = c93Var;
        this.a0 = ur2Var7;
        this.b0 = b93Var;
        this.c0 = b93Var2;
        this.d0 = wr2Var6;
        this.e0 = c93Var2;
        this.f0 = wr2Var7;
        this.g0 = c93Var3;
        this.h0 = wr2Var8;
        this.i0 = r83Var;
        this.j0 = a73Var2;
        this.k0 = y63Var;
        this.l0 = wr2Var9;
        this.m0 = wr2Var10;
        this.n0 = ur2Var8;
        this.o0 = ur2Var9;
        this.p0 = wr2Var11;
        this.q0 = wr2Var12;
        this.r0 = wr2Var13;
        this.s0 = ur2Var10;
        this.t0 = wr2Var14;
        this.u0 = wr2Var15;
        this.v0 = wr2Var16;
        this.w0 = wr2Var17;
        this.x0 = ks2Var21;
        this.y0 = wr2Var18;
        this.z0 = wr2Var19;
        this.A0 = e93Var;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof og3) {
            og3 og3Var = (og3) obj;
            if (this.a == og3Var.a && this.b.equals(og3Var.b) && this.c == og3Var.c && this.d == og3Var.d && this.e == og3Var.e && this.f == og3Var.f && this.g == og3Var.g && this.h == og3Var.h && this.i.equals(og3Var.i) && this.j == og3Var.j && ye4.p(this.k, og3Var.k) && this.l == og3Var.l && this.m == og3Var.m && ye4.p(this.n, og3Var.n) && ye4.p(this.o, og3Var.o) && ye4.p(this.p, og3Var.p) && ye4.p(this.q, og3Var.q) && ye4.p(this.r, og3Var.r) && this.s.equals(og3Var.s) && ye4.p(this.t, og3Var.t) && ye4.p(this.u, og3Var.u) && ye4.p(this.v, og3Var.v) && ye4.p(this.w, og3Var.w) && ye4.p(this.x, og3Var.x) && this.y.equals(og3Var.y) && this.z == og3Var.z && ye4.p(this.A, og3Var.A) && ye4.p(this.B, og3Var.B) && ye4.p(this.C, og3Var.C) && ye4.p(this.D, og3Var.D) && ye4.p(this.E, og3Var.E) && ye4.p(this.F, og3Var.F) && ye4.p(this.G, og3Var.G) && ye4.p(this.H, og3Var.H) && ye4.p(this.I, og3Var.I) && ye4.p(this.J, og3Var.J) && ye4.p(this.K, og3Var.K) && ye4.p(this.L, og3Var.L) && ye4.p(this.M, og3Var.M) && ye4.p(this.N, og3Var.N) && ye4.p(this.O, og3Var.O) && ye4.p(this.P, og3Var.P) && ye4.p(this.Q, og3Var.Q) && ye4.p(this.R, og3Var.R) && ye4.p(this.S, og3Var.S) && ye4.p(this.T, og3Var.T) && ye4.p(this.U, og3Var.U) && ye4.p(this.V, og3Var.V) && ye4.p(this.W, og3Var.W) && ye4.p(this.X, og3Var.X) && ye4.p(this.Y, og3Var.Y) && this.Z == og3Var.Z && ye4.p(this.a0, og3Var.a0) && this.b0 == og3Var.b0 && this.c0 == og3Var.c0 && ye4.p(this.d0, og3Var.d0) && this.e0 == og3Var.e0 && ye4.p(this.f0, og3Var.f0) && this.g0 == og3Var.g0 && ye4.p(this.h0, og3Var.h0) && this.i0 == og3Var.i0 && this.j0.equals(og3Var.j0) && this.k0.equals(og3Var.k0) && ye4.p(this.l0, og3Var.l0) && ye4.p(this.m0, og3Var.m0) && ye4.p(this.n0, og3Var.n0) && ye4.p(this.o0, og3Var.o0) && ye4.p(this.p0, og3Var.p0) && ye4.p(this.q0, og3Var.q0) && ye4.p(this.r0, og3Var.r0) && ye4.p(this.s0, og3Var.s0) && ye4.p(this.t0, og3Var.t0) && ye4.p(this.u0, og3Var.u0) && ye4.p(this.v0, og3Var.v0) && ye4.p(this.w0, og3Var.w0) && ye4.p(this.x0, og3Var.x0) && ye4.p(this.y0, og3Var.y0) && ye4.p(this.z0, og3Var.z0) && this.A0.equals(og3Var.A0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        return this.A0.hashCode() + pk0.b(pk0.b(rx1.d(pk0.b(pk0.b(pk0.b(pk0.b(rx1.f(this.s0, pk0.b(pk0.b(pk0.b(rx1.f(this.o0, rx1.f(this.n0, pk0.b(pk0.b((this.k0.hashCode() + ((this.j0.hashCode() + ((this.i0.hashCode() + pk0.b((hashCode() + pk0.b((hashCode() + pk0.b((this.c0.hashCode() + ((this.b0.hashCode() + rx1.f(this.a0, (hashCode() + rx1.d(rx1.g(this.X, rx1.g(this.W, (this.V.hashCode() + rx1.g(this.U, rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(rx1.d(pk0.b(pk0.b(pk0.b((hashCode() + ((this.y.hashCode() + rx1.f(this.x, rx1.f(this.w, pk0.b(rx1.f(this.u, rx1.f(this.t, (this.s.hashCode() + rx1.f(this.r, rx1.d(pk0.b(rx1.d(rx1.f(this.n, (this.m.hashCode() + j55.d(this.l, (this.k.hashCode() + ((this.j.hashCode() + ((this.i.hashCode() + ((this.h.hashCode() + ((this.g.hashCode() + ((this.f.hashCode() + ((this.e.hashCode() + ((this.d.hashCode() + ((this.c.hashCode() + ((this.b.hashCode() + (this.a.hashCode() * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31, 31), 31, this.o), this.p, 31), 31, this.q), 31)) * 31, 31), 31), this.v, 31), 31), 31)) * 31)) * 31, this.A, 31), this.B, 31), this.C, 31), 31, this.D), 31, this.E), 31, this.F), 31, this.G), 31, this.H), 31, this.I), 31, this.J), 31, this.K), 31, this.L), 31, this.M), 31, this.N), 31, this.O), 31, this.P), 31, this.Q), 31, this.R), 31, this.S), 31, this.T), 31)) * 31, 31), 31), 31, this.Y)) * 31, 31)) * 31)) * 31, this.d0, 31)) * 31, this.f0, 31)) * 31, this.h0, 31)) * 31)) * 31)) * 31, this.l0, 31), this.m0, 31), 31), 31), this.p0, 31), this.q0, 31), this.r0, 31), 31), this.t0, 31), this.u0, 31), this.v0, 31), this.w0, 31), 31, this.x0), this.y0, 31), this.z0, 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomePlatformMenuHostCallbackAssemblyDeps(runtimeState=");
        sb.append(this.a);
        sb.append(", dialogLayerSetup=");
        sb.append(this.b);
        sb.append(", platformAppBrowserCallbacks=");
        sb.append(this.c);
        sb.append(", dialogSystemCallbacks=");
        sb.append(this.d);
        sb.append(", addEditConsoleDialogOwner=");
        sb.append(this.e);
        sb.append(", taskLaunchCoordinator=");
        sb.append(this.f);
        sb.append(", taskScraperOperations=");
        sb.append(this.g);
        sb.append(", scraperTaskCoordinator=");
        sb.append(this.h);
        sb.append(", activeTaskMenuBindings=");
        sb.append(this.i);
        sb.append(", backgroundTaskActions=");
        sb.append(this.j);
        sb.append(", consoleMetadataRefreshCoordinator=");
        sb.append(this.k);
        sb.append(", backgroundTaskUpdateToken=");
        sb.append(this.l);
        sb.append(", beginDialogDismiss=");
        sb.append(this.m);
        sb.append(", onShowDiscord=");
        sb.append(this.n);
        sb.append(", onSetConsoleCustomLabel=");
        sb.append(this.o);
        sb.append(", onGeneratePsVitaFiles=");
        sb.append(this.p);
        sb.append(", onToggleRomShortcut=");
        sb.append(this.q);
        sb.append(", onOpenGlobalSearch=");
        sb.append(this.r);
        sb.append(", onApplyRomSearch=");
        sb.append(this.s);
        sb.append(", onIncreaseDensity=");
        sb.append(this.t);
        sb.append(", onDecreaseDensity=");
        sb.append(this.u);
        sb.append(", onChangeCategoryLayout=");
        sb.append(this.v);
        rx1.x(this.w, this.x, ", onIncreaseCategoryGridDensity=", ", onDecreaseCategoryGridDensity=", sb);
        sb.append(", onSetMinimalModeEnabled=");
        sb.append(this.y);
        sb.append(", isHideEmptyConsolesEnabled=");
        sb.append(this.z);
        rx1.C(sb, ", onSetHideEmptyConsolesEnabled=", this.A, ", onSetPersistentNavBarOnPlatforms=", this.B);
        sb.append(", onSetPersistentNavBarOnGames=");
        sb.append(this.C);
        sb.append(", onSetPreferZoomedArtwork=");
        sb.append(this.D);
        f33.w(sb, ", onSetArtworkAlignment=", this.E, ", onSetTitleSectionMode=", this.F);
        f33.w(sb, ", onSetTrophyIconCorner=", this.G, ", onSetTrophyIconAlpha=", this.H);
        f33.w(sb, ", onSetTabHideDiscFiles=", this.I, ", onSetTabPreferNativeRomIconSize=", this.J);
        f33.w(sb, ", onSetTabsPreferNativeRomIconSize=", this.K, ", onSetTabRomIconAspectRatioPresetId=", this.L);
        f33.w(sb, ", onSetRomPreferNativeRomIconSize=", this.M, ", onSetRomIconAspectRatioPresetId=", this.N);
        f33.w(sb, ", onSetRomArtworkAlignment=", this.O, ", onSetRomTitleSectionMode=", this.P);
        f33.w(sb, ", onSetRomCustomName=", this.Q, ", onSetRomTrophyIconCorner=", this.R);
        f33.w(sb, ", onSetRomTrophyIconAlpha=", this.S, ", onUpdateRomLaunchPreference=", this.T);
        sb.append(", onUpdateRomLinkedPreference=");
        sb.append(this.U);
        sb.append(", onUpdateRomCommandPreference=");
        sb.append(this.V);
        sb.append(", onSetRomInCollection=");
        sb.append(this.W);
        sb.append(", onToggleRomVisibility=");
        sb.append(this.X);
        sb.append(", onToggleAppVisibility=");
        sb.append(this.Y);
        sb.append(", onShowGameInfo=");
        sb.append(this.Z);
        sb.append(", onShowRetroAchievements=");
        sb.append(this.a0);
        sb.append(", onShowRetroAchievementsForRom=");
        sb.append(this.b0);
        sb.append(", onChangeRetroAchievementsTitleForRom=");
        sb.append(this.c0);
        sb.append(", onDownloadRommRom=");
        sb.append(this.d0);
        sb.append(", onDownloadAllRommRoms=");
        sb.append(this.e0);
        sb.append(", onDeleteRommRom=");
        sb.append(this.f0);
        sb.append(", onDeleteAllRommRoms=");
        sb.append(this.g0);
        sb.append(", isRommRomDownloaded=");
        sb.append(this.h0);
        sb.append(", isScraperSourceConfigured=");
        sb.append(this.i0);
        sb.append(", onConfigureScraperSource=");
        sb.append(this.j0);
        sb.append(", onScrapeSelectedHomeIcon=");
        sb.append(this.k0);
        sb.append(", onManageRomQuickAccessIcon=");
        sb.append(this.l0);
        sb.append(", onDeleteRomQuickAccessIcon=");
        sb.append(this.m0);
        sb.append(", onSaveConsole=");
        sb.append(this.n0);
        sb.append(", onDeleteConsole=");
        sb.append(this.o0);
        sb.append(", onSelectConsole=");
        sb.append(this.p0);
        rx1.C(sb, ", onSelectEmulator=", this.q0, ", onSelectEmulatorPackage=", this.r0);
        sb.append(", onDetectInstalledEmulator=");
        sb.append(this.s0);
        sb.append(", onSelectCommand=");
        sb.append(this.t0);
        rx1.C(sb, ", onCustomLaunchCommandChange=", this.u0, ", onTabLabelChange=", this.v0);
        sb.append(", onRequestAddTabDirectory=");
        sb.append(this.w0);
        sb.append(", onAddTabDirectorySelected=");
        sb.append(this.x0);
        rx1.C(sb, ", onRemoveDirectory=", this.y0, ", onDefaultLaunchPreferenceChange=", this.z0);
        sb.append(", bumpRomCategoryFocus=");
        sb.append(this.A0);
        sb.append(")");
        return sb.toString();
    }
}
