package defpackage;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public abstract class vo8 {
    public static final long A;
    public static final long A0;
    public static final pt2 A1;
    public static final long B;
    public static final ol2 B0;
    public static final long B1;
    public static final long C;
    public static final pt2 C0;
    public static final long C1;
    public static final ol2 D;
    public static final long D0;
    public static final long D1;
    public static final pt2 E;
    public static final long E0;
    public static final ol2 E1;
    public static final long F;
    public static final long F0;
    public static final pt2 F1;
    public static final long G;
    public static final ol2 G0;
    public static final long G1;
    public static final long H;
    public static final pt2 H0;
    public static final long H1;
    public static final ol2 I;
    public static final long I0;
    public static final long I1;
    public static final pt2 J;
    public static final long J0;
    public static final ol2 J1;
    public static final long K;
    public static final long K0;
    public static final pt2 K1;
    public static final long L;
    public static final ol2 L0;
    public static final long L1;
    public static final long M;
    public static final pt2 M0;
    public static final long M1;
    public static final ol2 N;
    public static final long N0;
    public static final long N1;
    public static final pt2 O;
    public static final long O0;
    public static final ol2 O1;
    public static final long P;
    public static final long P0;
    public static final pt2 P1;
    public static final long Q;
    public static final ol2 Q0;
    public static final long Q1;
    public static final long R;
    public static final pt2 R0;
    public static final long R1;
    public static final ol2 S;
    public static final long S0;
    public static final long S1;
    public static final pt2 T;
    public static final long T0;
    public static final ol2 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final ol2 V0;
    public static final long W;
    public static final pt2 W0;
    public static final ol2 X;
    public static final long X0;
    public static final pt2 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final pt2 a;
    public static final long a0;
    public static final ol2 a1;
    public static final long b;
    public static final long b0;
    public static final pt2 b1;
    public static final long c;
    public static final ol2 c0;
    public static final long c1;
    public static final long d;
    public static final pt2 d0;
    public static final long d1;
    public static final ol2 e;
    public static final long e0;
    public static final long e1;
    public static final pt2 f;
    public static final long f0;
    public static final ol2 f1;
    public static final long g;
    public static final long g0;
    public static final pt2 g1;
    public static final long h;
    public static final ol2 h0;
    public static final long h1;
    public static final long i;
    public static final pt2 i0;
    public static final long i1;
    public static final ol2 j;
    public static final long j0;
    public static final long j1;
    public static final pt2 k;
    public static final long k0;
    public static final ol2 k1;
    public static final long l;
    public static final long l0;
    public static final pt2 l1;
    public static final long m;
    public static final ol2 m0;
    public static final long m1;
    public static final long n;
    public static final pt2 n0;
    public static final long n1;
    public static final ol2 o;
    public static final long o0;
    public static final long o1;
    public static final pt2 p;
    public static final long p0;
    public static final ol2 p1;
    public static final long q;
    public static final long q0;
    public static final pt2 q1;
    public static final long r;
    public static final ol2 r0;
    public static final long r1;
    public static final long s;
    public static final pt2 s0;
    public static final long s1;
    public static final ol2 t;
    public static final long t0;
    public static final long t1;
    public static final pt2 u;
    public static final long u0;
    public static final ol2 u1;
    public static final long v;
    public static final long v0;
    public static final pt2 v1;
    public static final long w;
    public static final ol2 w0;
    public static final long w1;
    public static final long x;
    public static final pt2 x0;
    public static final long x1;
    public static final ol2 y;
    public static final long y0;
    public static final long y1;
    public static final pt2 z;
    public static final long z0;
    public static final ol2 z1;

    static {
        ol2 ol2Var = dp8.a;
        pt2 pt2Var = ik2.j;
        a = pt2Var;
        b = px7.k(24.0d);
        c = px7.m(16);
        d = px7.k(0.5d);
        ol2 ol2Var2 = dp8.c;
        e = ol2Var2;
        f = pt2Var;
        g = px7.k(20.0d);
        h = px7.m(14);
        i = px7.k(0.2d);
        j = ol2Var2;
        k = pt2Var;
        l = px7.k(16.0d);
        m = px7.m(12);
        n = px7.k(0.4d);
        o = ol2Var2;
        p = pt2Var;
        q = px7.k(64.0d);
        r = px7.m(57);
        long jK = px7.k(0.2d);
        px7.d(jK);
        s = px7.w(-vc8.d(jK), jK & 1095216660480L);
        t = ol2Var2;
        u = pt2Var;
        v = px7.k(52.0d);
        w = px7.m(45);
        x = px7.k(0.0d);
        y = ol2Var2;
        z = pt2Var;
        A = px7.k(44.0d);
        B = px7.m(36);
        C = px7.k(0.0d);
        D = ol2Var2;
        E = pt2Var;
        F = px7.k(40.0d);
        G = px7.m(32);
        H = px7.k(0.0d);
        I = ol2Var2;
        J = pt2Var;
        K = px7.k(36.0d);
        L = px7.m(28);
        M = px7.k(0.0d);
        N = ol2Var2;
        O = pt2Var;
        P = px7.k(32.0d);
        Q = px7.m(24);
        R = px7.k(0.0d);
        S = ol2Var2;
        T = pt2Var;
        U = px7.k(20.0d);
        V = px7.m(14);
        W = px7.k(0.1d);
        ol2 ol2Var3 = dp8.b;
        X = ol2Var3;
        Y = pt2Var;
        Z = px7.k(16.0d);
        a0 = px7.m(12);
        b0 = px7.k(0.5d);
        c0 = ol2Var3;
        d0 = pt2Var;
        e0 = px7.k(16.0d);
        f0 = px7.m(11);
        g0 = px7.k(0.5d);
        h0 = ol2Var3;
        i0 = pt2Var;
        j0 = px7.k(28.0d);
        k0 = px7.m(22);
        l0 = px7.k(0.0d);
        m0 = ol2Var2;
        n0 = pt2Var;
        o0 = px7.k(24.0d);
        p0 = px7.m(16);
        q0 = px7.k(0.2d);
        r0 = ol2Var3;
        s0 = pt2Var;
        t0 = px7.k(20.0d);
        u0 = px7.m(14);
        v0 = px7.k(0.1d);
        w0 = ol2Var3;
        x0 = pt2Var;
        y0 = px7.k(24.0d);
        z0 = px7.m(16);
        A0 = px7.k(0.15d);
        B0 = ol2Var3;
        C0 = pt2Var;
        D0 = px7.k(20.0d);
        E0 = px7.m(14);
        F0 = px7.k(0.25d);
        G0 = ol2Var3;
        H0 = pt2Var;
        I0 = px7.k(16.0d);
        J0 = px7.m(12);
        K0 = px7.k(0.4d);
        L0 = ol2Var3;
        M0 = pt2Var;
        N0 = px7.k(64.0d);
        O0 = px7.m(57);
        P0 = px7.m(0);
        Q0 = ol2Var3;
        R0 = pt2Var;
        S0 = px7.k(52.0d);
        T0 = px7.m(45);
        U0 = px7.m(0);
        V0 = ol2Var3;
        W0 = pt2Var;
        X0 = px7.k(44.0d);
        Y0 = px7.m(36);
        Z0 = px7.m(0);
        a1 = ol2Var3;
        b1 = pt2Var;
        c1 = px7.k(40.0d);
        d1 = px7.m(32);
        e1 = px7.m(0);
        f1 = ol2Var3;
        g1 = pt2Var;
        h1 = px7.k(36.0d);
        i1 = px7.m(28);
        j1 = px7.m(0);
        k1 = ol2Var3;
        l1 = pt2Var;
        m1 = px7.k(32.0d);
        n1 = px7.m(24);
        o1 = px7.m(0);
        p1 = ol2Var3;
        q1 = pt2Var;
        r1 = px7.k(20.0d);
        s1 = px7.m(14);
        t1 = px7.k(0.1d);
        ol2 ol2Var4 = dp8.a;
        u1 = ol2Var4;
        v1 = pt2Var;
        w1 = px7.k(16.0d);
        x1 = px7.m(12);
        y1 = px7.k(0.5d);
        z1 = ol2Var4;
        A1 = pt2Var;
        B1 = px7.k(16.0d);
        C1 = px7.m(11);
        D1 = px7.k(0.5d);
        E1 = ol2Var4;
        F1 = pt2Var;
        G1 = px7.k(28.0d);
        H1 = px7.m(22);
        I1 = px7.m(0);
        J1 = ol2Var3;
        K1 = pt2Var;
        L1 = px7.k(24.0d);
        M1 = px7.m(16);
        N1 = px7.k(0.15d);
        O1 = ol2Var4;
        P1 = pt2Var;
        Q1 = px7.k(20.0d);
        R1 = px7.m(14);
        S1 = px7.k(0.1d);
        T1 = ol2Var4;
    }
}
