package defpackage;

import java.util.List;
import java.util.Map;

/* JADX INFO: compiled from: r8-map-id-2a50c0369e92087812e54748034d27ec95c033a3a5145ed80421924f55507ca7 */
/* JADX INFO: loaded from: classes2.dex */
public final class x83 {
    public final jn A;
    public final String B;
    public final b93 C;
    public final List D;
    public final List E;
    public final bv2 F;
    public final wr2 G;
    public final wr2 H;
    public final ww6 I;
    public final boolean J;
    public final Map K;
    public final Map L;
    public final wr2 M;
    public final wr2 N;
    public final ur2 O;
    public final ur2 P;
    public final wr2 Q;
    public final List R;
    public final b93 S;
    public final d93 T;
    public final Map U;
    public final boolean V;
    public final gz6 W;
    public final fa0 X;
    public final ia0 Y;
    public final fa0 Z;
    public final xz2 a;
    public final ia0 a0;
    public final gs7 b;
    public final aj0 b0;
    public final boolean c;
    public final aj0 c0;
    public final r73 d;
    public final boolean d0;
    public final z71 e;
    public final Map e0;
    public final ur2 f;
    public final List f0;
    public final g43 g;
    public final boolean g0;
    public final d84 h;
    public final String h0;
    public final m64 i;
    public final String i0;
    public final long j;
    public final e93 j0;
    public final String k;
    public final a73 k0;
    public final String l;
    public final List l0;
    public final String m;
    public final a73 m0;
    public final String n;
    public final a73 n0;
    public final e93 o;
    public final a73 o0;
    public final rw3 p;
    public final a73 p0;
    public final boolean q;
    public final t63 q0;
    public final e93 r;
    public final t63 r0;
    public final ur2 s;
    public final int s0;
    public final e93 t;
    public final b93 t0;
    public final b93 u;
    public final ur2 u0;
    public final f8 v;
    public final d93 v0;
    public final ze0 w;
    public final f63 w0;
    public final lc7 x;
    public final boolean x0;
    public final List y;
    public final Object y0;
    public final v66 z;
    public final e93 z0;

    public x83(xz2 xz2Var, gs7 gs7Var, boolean z, r73 r73Var, z71 z71Var, ur2 ur2Var, g43 g43Var, d84 d84Var, m64 m64Var, long j, String str, String str2, String str3, String str4, e93 e93Var, rw3 rw3Var, boolean z2, e93 e93Var2, ur2 ur2Var2, e93 e93Var3, b93 b93Var, f8 f8Var, ze0 ze0Var, lc7 lc7Var, List list, v66 v66Var, jn jnVar, String str5, b93 b93Var2, List list2, List list3, bv2 bv2Var, wr2 wr2Var, wr2 wr2Var2, ww6 ww6Var, boolean z3, Map map, Map map2, wr2 wr2Var3, wr2 wr2Var4, ur2 ur2Var3, ur2 ur2Var4, wr2 wr2Var5, List list4, b93 b93Var3, d93 d93Var, Map map3, boolean z4, gz6 gz6Var, fa0 fa0Var, ia0 ia0Var, fa0 fa0Var2, ia0 ia0Var2, aj0 aj0Var, aj0 aj0Var2, boolean z5, Map map4, List list5, boolean z6, String str6, String str7, e93 e93Var4, a73 a73Var, List list6, a73 a73Var2, a73 a73Var3, a73 a73Var4, a73 a73Var5, t63 t63Var, t63 t63Var2, int i, b93 b93Var4, ur2 ur2Var5, d93 d93Var2, f63 f63Var, boolean z7, Object obj, e93 e93Var5) {
        gs7Var.getClass();
        d84Var.getClass();
        m64Var.getClass();
        rw3Var.getClass();
        ur2Var2.getClass();
        f8Var.getClass();
        ze0Var.getClass();
        lc7Var.getClass();
        list.getClass();
        str5.getClass();
        list2.getClass();
        list3.getClass();
        bv2Var.getClass();
        wr2Var.getClass();
        wr2Var2.getClass();
        ww6Var.getClass();
        wr2Var3.getClass();
        wr2Var4.getClass();
        ur2Var3.getClass();
        ur2Var4.getClass();
        wr2Var5.getClass();
        list4.getClass();
        map3.getClass();
        gz6Var.getClass();
        list5.getClass();
        list6.getClass();
        ur2Var5.getClass();
        this.a = xz2Var;
        this.b = gs7Var;
        this.c = z;
        this.d = r73Var;
        this.e = z71Var;
        this.f = ur2Var;
        this.g = g43Var;
        this.h = d84Var;
        this.i = m64Var;
        this.j = j;
        this.k = str;
        this.l = str2;
        this.m = str3;
        this.n = str4;
        this.o = e93Var;
        this.p = rw3Var;
        this.q = z2;
        this.r = e93Var2;
        this.s = ur2Var2;
        this.t = e93Var3;
        this.u = b93Var;
        this.v = f8Var;
        this.w = ze0Var;
        this.x = lc7Var;
        this.y = list;
        this.z = v66Var;
        this.A = jnVar;
        this.B = str5;
        this.C = b93Var2;
        this.D = list2;
        this.E = list3;
        this.F = bv2Var;
        this.G = wr2Var;
        this.H = wr2Var2;
        this.I = ww6Var;
        this.J = z3;
        this.K = map;
        this.L = map2;
        this.M = wr2Var3;
        this.N = wr2Var4;
        this.O = ur2Var3;
        this.P = ur2Var4;
        this.Q = wr2Var5;
        this.R = list4;
        this.S = b93Var3;
        this.T = d93Var;
        this.U = map3;
        this.V = z4;
        this.W = gz6Var;
        this.X = fa0Var;
        this.Y = ia0Var;
        this.Z = fa0Var2;
        this.a0 = ia0Var2;
        this.b0 = aj0Var;
        this.c0 = aj0Var2;
        this.d0 = z5;
        this.e0 = map4;
        this.f0 = list5;
        this.g0 = z6;
        this.h0 = str6;
        this.i0 = str7;
        this.j0 = e93Var4;
        this.k0 = a73Var;
        this.l0 = list6;
        this.m0 = a73Var2;
        this.n0 = a73Var3;
        this.o0 = a73Var4;
        this.p0 = a73Var5;
        this.q0 = t63Var;
        this.r0 = t63Var2;
        this.s0 = i;
        this.t0 = b93Var4;
        this.u0 = ur2Var5;
        this.v0 = d93Var2;
        this.w0 = f63Var;
        this.x0 = z7;
        this.y0 = obj;
        this.z0 = e93Var5;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof x83) {
            x83 x83Var = (x83) obj;
            if (this.a == x83Var.a && this.b == x83Var.b && this.c == x83Var.c && this.d.equals(x83Var.d) && ye4.p(this.e, x83Var.e) && this.f.equals(x83Var.f) && this.g == x83Var.g && ye4.p(this.h, x83Var.h) && ye4.p(this.i, x83Var.i) && this.j == x83Var.j && ye4.p(this.k, x83Var.k) && ye4.p(this.l, x83Var.l) && ye4.p(this.m, x83Var.m) && ye4.p(this.n, x83Var.n) && this.o.equals(x83Var.o) && ye4.p(this.p, x83Var.p) && this.q == x83Var.q && this.r.equals(x83Var.r) && ye4.p(this.s, x83Var.s) && this.t.equals(x83Var.t) && this.u == x83Var.u && ye4.p(this.v, x83Var.v) && ye4.p(this.w, x83Var.w) && ye4.p(this.x, x83Var.x) && ye4.p(this.y, x83Var.y) && this.z.equals(x83Var.z) && this.A.equals(x83Var.A) && ye4.p(this.B, x83Var.B) && this.C == x83Var.C && ye4.p(this.D, x83Var.D) && ye4.p(this.E, x83Var.E) && ye4.p(this.F, x83Var.F) && ye4.p(this.G, x83Var.G) && ye4.p(this.H, x83Var.H) && ye4.p(this.I, x83Var.I) && this.J == x83Var.J && this.K.equals(x83Var.K) && this.L.equals(x83Var.L) && ye4.p(this.M, x83Var.M) && ye4.p(this.N, x83Var.N) && ye4.p(this.O, x83Var.O) && ye4.p(this.P, x83Var.P) && ye4.p(this.Q, x83Var.Q) && ye4.p(this.R, x83Var.R) && this.S == x83Var.S && this.T == x83Var.T && ye4.p(this.U, x83Var.U) && this.V == x83Var.V && this.W == x83Var.W && this.X == x83Var.X && this.Y == x83Var.Y && this.Z == x83Var.Z && this.a0 == x83Var.a0 && ye4.p(this.b0, x83Var.b0) && ye4.p(this.c0, x83Var.c0) && this.d0 == x83Var.d0 && this.e0.equals(x83Var.e0) && ye4.p(this.f0, x83Var.f0) && this.g0 == x83Var.g0 && ye4.p(this.h0, x83Var.h0) && ye4.p(this.i0, x83Var.i0) && this.j0.equals(x83Var.j0) && this.k0.equals(x83Var.k0) && ye4.p(this.l0, x83Var.l0) && this.m0.equals(x83Var.m0) && this.n0.equals(x83Var.n0) && this.o0.equals(x83Var.o0) && this.p0.equals(x83Var.p0) && this.q0 == x83Var.q0 && this.r0 == x83Var.r0 && this.s0 == x83Var.s0 && this.t0 == x83Var.t0 && ye4.p(this.u0, x83Var.u0) && this.v0 == x83Var.v0 && this.w0.equals(x83Var.w0) && this.x0 == x83Var.x0 && ye4.p(this.y0, x83Var.y0) && this.z0.equals(x83Var.z0)) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int iHashCode = (this.d.hashCode() + a68.d((this.b.hashCode() + (this.a.hashCode() * 31)) * 31, 31, this.c)) * 31;
        z71 z71Var = this.e;
        int iD = j55.d(this.j, (this.i.hashCode() + ((this.h.hashCode() + ((this.g.hashCode() + rx1.f(this.f, (iHashCode + (z71Var == null ? 0 : z71Var.hashCode())) * 31, 31)) * 31)) * 31)) * 31, 31);
        String str = this.k;
        int iHashCode2 = (iD + (str == null ? 0 : str.hashCode())) * 31;
        String str2 = this.l;
        int iHashCode3 = (iHashCode2 + (str2 == null ? 0 : str2.hashCode())) * 31;
        String str3 = this.m;
        int iHashCode4 = (iHashCode3 + (str3 == null ? 0 : str3.hashCode())) * 31;
        String str4 = this.n;
        int iHashCode5 = (this.a0.hashCode() + qv7.b(this.Z, (this.Y.hashCode() + qv7.b(this.X, (this.W.hashCode() + a68.d(a68.f(this.U, (hashCode() + ((this.S.hashCode() + a68.e(this.R, pk0.b(rx1.f(this.P, rx1.f(this.O, pk0.b(pk0.b(a68.f(this.L, a68.f(this.K, a68.d(f33.c(this.I, pk0.b(pk0.b((this.F.hashCode() + a68.e(this.E, a68.e(this.D, (this.C.hashCode() + a68.c((this.A.hashCode() + ((this.z.hashCode() + a68.e(this.y, rx1.j(this.x, rx1.e(this.w, (this.v.hashCode() + ((this.u.hashCode() + ((this.t.hashCode() + rx1.f(this.s, (this.r.hashCode() + a68.d((((this.p.hashCode() + ((this.o.hashCode() + ((iHashCode4 + (str4 == null ? 0 : str4.hashCode())) * 31)) * 31)) * 31) + 1013198401) * 31, 31, this.q)) * 31, 31)) * 31)) * 31)) * 31, 31), 31), 31)) * 31)) * 31, 31, this.B)) * 31, 31), 31)) * 31, this.G, 31), this.H, 31), 31), 31, this.J), 31), 31), this.M, 31), this.N, 31), 31), 31), this.Q, 31), 31)) * 31)) * 31, 31), 31, this.V)) * 31, 31)) * 31, 31)) * 31;
        aj0 aj0Var = this.b0;
        int iHashCode6 = (iHashCode5 + (aj0Var == null ? 0 : aj0Var.hashCode())) * 31;
        aj0 aj0Var2 = this.c0;
        int iD2 = a68.d(a68.e(this.f0, a68.f(this.e0, a68.d((iHashCode6 + (aj0Var2 == null ? 0 : aj0Var2.hashCode())) * 31, 31, this.d0), 31), 31), 31, this.g0);
        String str5 = this.h0;
        int iHashCode7 = (iD2 + (str5 == null ? 0 : str5.hashCode())) * 31;
        String str6 = this.i0;
        int iD3 = a68.d((this.w0.hashCode() + ((hashCode() + rx1.f(this.u0, (this.t0.hashCode() + f33.a(this.s0, (this.r0.hashCode() + ((this.q0.hashCode() + ((this.p0.hashCode() + ((this.o0.hashCode() + ((this.n0.hashCode() + ((this.m0.hashCode() + a68.e(this.l0, (this.k0.hashCode() + ((this.j0.hashCode() + ((iHashCode7 + (str6 == null ? 0 : str6.hashCode())) * 31)) * 31)) * 31, 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31, 31)) * 31, 31)) * 31)) * 31, 31, this.x0);
        Object obj = this.y0;
        return this.z0.hashCode() + ((iD3 + (obj != null ? obj.hashCode() : 0)) * 31);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("HomeDialogSystemHostLayerDeps(homeDialogHazeState=");
        sb.append(this.a);
        sb.append(", singleScreenHomeGlassMode=");
        sb.append(this.b);
        sb.append(", contextMenuGlassEnabled=");
        sb.append(this.c);
        sb.append(", menuState=");
        sb.append(this.d);
        sb.append(", dialogMenuOrigin=");
        sb.append(this.e);
        sb.append(", onDismiss=");
        sb.append(this.f);
        sb.append(", onDismissStart=");
        sb.append(this.g);
        sb.append(", iisuSettingsSnapshot=");
        sb.append(this.h);
        sb.append(", iisuSettingsCallbacks=");
        sb.append(this.i);
        sb.append(", iisuSettingsAutoOpenSubPageRequestId=");
        sb.append(this.j);
        a68.v(sb, ", iisuSettingsAutoOpenSubPageId=", this.k, ", iisuSettingsAutoOpenSubPageTitle=", this.l);
        a68.v(sb, ", iisuSettingsAutoOpenParentPageId=", this.m, ", iisuSettingsAutoOpenTargetItemId=", this.n);
        sb.append(", onIisuSettingsAutoOpenSubPageConsumed=");
        sb.append(this.o);
        sb.append(", themeCreationState=");
        sb.append(this.p);
        sb.append(", appVersion=0.0.7.4, isSystemPickerOpen=");
        sb.append(this.q);
        sb.append(", onShowIisuSettings=");
        sb.append(this.r);
        sb.append(", onShowDiscord=");
        sb.append(this.s);
        sb.append(", onShowThorSettings=");
        sb.append(this.t);
        sb.append(", onSetThorDisplayMode=");
        sb.append(this.u);
        sb.append(", addConsoleState=");
        sb.append(this.v);
        sb.append(", browserState=");
        sb.append(this.w);
        sb.append(", scraperState=");
        sb.append(this.x);
        sb.append(", scrapers=");
        sb.append(this.y);
        sb.append(", platformCallbacks=");
        sb.append(this.z);
        sb.append(", appMenuCallbacks=");
        sb.append(this.A);
        sb.append(", globalSearchQuery=");
        sb.append(this.B);
        sb.append(", onGlobalSearchQueryChange=");
        sb.append(this.C);
        sb.append(", globalSearchResults=");
        sb.append(this.D);
        sb.append(", globalSearchEmptyQueryResults=");
        sb.append(this.E);
        sb.append(", globalSearchStrings=");
        sb.append(this.F);
        rx1.C(sb, ", onGlobalSearchResultActivated=", this.G, ", onGlobalSearchResultNavigated=", this.H);
        sb.append(", retroAchievementsState=");
        sb.append(this.I);
        sb.append(", showSoftcoreAchievements=");
        sb.append(this.J);
        sb.append(", romByGameId=");
        sb.append(this.K);
        sb.append(", iisuPlatformKeyByGameId=");
        sb.append(this.L);
        rx1.C(sb, ", onRetroAchievementFocused=", this.M, ", onRetroAchievementActivated=", this.N);
        rx1.x(this.O, this.P, ", onRetroAchievementsLoadManualSearchGames=", ", onRetroAchievementsDismissManualSearch=", sb);
        sb.append(", onRetroAchievementsManualSearchGameSelected=");
        sb.append(this.Q);
        sb.append(", androidWidgetProviderEntries=");
        sb.append(this.R);
        sb.append(", onAndroidWidgetProviderSelected=");
        sb.append(this.S);
        sb.append(", onAndroidWidgetPickerDismiss=");
        sb.append(this.T);
        sb.append(", retroHashesByRomId=");
        sb.append(this.U);
        sb.append(", hasRetroAchievementsSession=");
        sb.append(this.V);
        sb.append(", categoryLayoutMode=");
        sb.append(this.W);
        sb.append(", currentLayoutMode=");
        sb.append(this.X);
        sb.append(", currentListLayout=");
        sb.append(this.Y);
        sb.append(", appCurrentLayoutMode=");
        sb.append(this.Z);
        sb.append(", appCurrentListLayout=");
        sb.append(this.a0);
        sb.append(", appCurrentBrowserViewport=");
        sb.append(this.b0);
        sb.append(", romCurrentBrowserViewport=");
        sb.append(this.c0);
        sb.append(", isEditMode=");
        sb.append(this.d0);
        sb.append(", romsByTab=");
        sb.append(this.e0);
        sb.append(", allConsolesRoms=");
        sb.append(this.f0);
        sb.append(", platformCategoryIsExternalDisplay=");
        sb.append(this.g0);
        sb.append(", focusedConsoleName=");
        sb.append(this.h0);
        sb.append(", focusedConsoleId=");
        sb.append(this.i0);
        sb.append(", onAddConsole=");
        sb.append(this.j0);
        sb.append(", onEditConsole=");
        sb.append(this.k0);
        sb.append(", platformCategorySubmenuPath=");
        sb.append(this.l0);
        sb.append(", onPlatformCategorySubmenuPathChange=");
        sb.append(this.m0);
        sb.append(", onTopLevelSubmenuPathChange=");
        sb.append(this.n0);
        sb.append(", onRomBrowserSubmenuPathChange=");
        sb.append(this.o0);
        sb.append(", onAppBrowserSubmenuPathChange=");
        sb.append(this.p0);
        sb.append(", homeEmptySlotItemsBuilder=");
        sb.append(this.q0);
        sb.append(", topLevelContextItemsBuilder=");
        sb.append(this.r0);
        sb.append(", topLevelFocusedIndex=");
        sb.append(this.s0);
        sb.append(", onTopLevelFocusedIndexChange=");
        sb.append(this.t0);
        sb.append(", onTopLevelDismiss=");
        sb.append(this.u0);
        sb.append(", onReturnToHomeSelectedMenu=");
        sb.append(this.v0);
        sb.append(", onRetroAchievementsDismiss=");
        sb.append(this.w0);
        sb.append(", isTransitioning=");
        sb.append(this.x0);
        sb.append(", focusKey=");
        sb.append(this.y0);
        sb.append(", onFocusRecovery=");
        sb.append(this.z0);
        sb.append(")");
        return sb.toString();
    }
}
